// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Nethermind.PubSub.Kafka.Avro.Models
{
	using System.Collections.Generic;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Block : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Block"",""namespace"":""Nethermind.PubSub.Kafka.Avro.Models"",""fields"":[{""name"":""blockNumber"",""type"":""long""},{""name"":""blockHash"",""type"":""string""},{""name"":""parentHash"",""type"":""string""},{""name"":""nonce"",""type"":""string""},{""name"":""sha3uncles"",""type"":""string""},{""name"":""logsBloom"",""type"":""string""},{""name"":""receiptsRoot"",""type"":""string""},{""name"":""transactionRoot"",""type"":""string""},{""name"":""stateRoot"",""type"":""string""},{""name"":""miner"",""type"":""string""},{""name"":""difficulty"",""type"":""string""},{""name"":""totalDifficulty"",""type"":""string""},{""name"":""extraData"",""type"":""bytes""},{""name"":""size"",""type"":""long""},{""name"":""gasLimit"",""type"":""long""},{""name"":""gasUsed"",""type"":""long""},{""name"":""timestamp"",""type"":""long""},{""name"":""transactions"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Transaction"",""namespace"":""Nethermind.PubSub.Kafka.Avro.Models"",""fields"":[{""name"":""blockHash"",""type"":""string""},{""name"":""blockNumber"",""type"":""long""},{""name"":""fromAddr"",""type"":""string""},{""name"":""gas"",""type"":""long""},{""name"":""gasPrice"",""type"":""long""},{""name"":""hash"",""type"":""string""},{""name"":""input"",""type"":""bytes""},{""name"":""nonce"",""type"":""int""},{""name"":""toAddr"",""type"":[""null"",""string""]},{""name"":""transactionIndex"",""type"":""int""},{""name"":""weiValue"",""type"":""string""},{""name"":""v"",""type"":""int""},{""name"":""r"",""type"":""string""},{""name"":""s"",""type"":""string""}]}}},{""name"":""uncles"",""type"":{""type"":""array"",""items"":""string""}}]}");
		private long _blockNumber;
		private string _blockHash;
		private string _parentHash;
		private string _nonce;
		private string _sha3uncles;
		private string _logsBloom;
		private string _receiptsRoot;
		private string _transactionRoot;
		private string _stateRoot;
		private string _miner;
		private string _difficulty;
		private string _totalDifficulty;
		private byte[] _extraData;
		private long _size;
		private long _gasLimit;
		private long _gasUsed;
		private long _timestamp;
		private IList<Nethermind.PubSub.Kafka.Avro.Models.Transaction> _transactions;
		private IList<System.String> _uncles;
		public virtual Schema Schema
		{
			get
			{
				return Block._SCHEMA;
			}
		}
		public long blockNumber
		{
			get
			{
				return this._blockNumber;
			}
			set
			{
				this._blockNumber = value;
			}
		}
		public string blockHash
		{
			get
			{
				return this._blockHash;
			}
			set
			{
				this._blockHash = value;
			}
		}
		public string parentHash
		{
			get
			{
				return this._parentHash;
			}
			set
			{
				this._parentHash = value;
			}
		}
		public string nonce
		{
			get
			{
				return this._nonce;
			}
			set
			{
				this._nonce = value;
			}
		}
		public string sha3uncles
		{
			get
			{
				return this._sha3uncles;
			}
			set
			{
				this._sha3uncles = value;
			}
		}
		public string logsBloom
		{
			get
			{
				return this._logsBloom;
			}
			set
			{
				this._logsBloom = value;
			}
		}
		public string receiptsRoot
		{
			get
			{
				return this._receiptsRoot;
			}
			set
			{
				this._receiptsRoot = value;
			}
		}
		public string transactionRoot
		{
			get
			{
				return this._transactionRoot;
			}
			set
			{
				this._transactionRoot = value;
			}
		}
		public string stateRoot
		{
			get
			{
				return this._stateRoot;
			}
			set
			{
				this._stateRoot = value;
			}
		}
		public string miner
		{
			get
			{
				return this._miner;
			}
			set
			{
				this._miner = value;
			}
		}
		public string difficulty
		{
			get
			{
				return this._difficulty;
			}
			set
			{
				this._difficulty = value;
			}
		}
		public string totalDifficulty
		{
			get
			{
				return this._totalDifficulty;
			}
			set
			{
				this._totalDifficulty = value;
			}
		}
		public byte[] extraData
		{
			get
			{
				return this._extraData;
			}
			set
			{
				this._extraData = value;
			}
		}
		public long size
		{
			get
			{
				return this._size;
			}
			set
			{
				this._size = value;
			}
		}
		public long gasLimit
		{
			get
			{
				return this._gasLimit;
			}
			set
			{
				this._gasLimit = value;
			}
		}
		public long gasUsed
		{
			get
			{
				return this._gasUsed;
			}
			set
			{
				this._gasUsed = value;
			}
		}
		public long timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public IList<Nethermind.PubSub.Kafka.Avro.Models.Transaction> transactions
		{
			get
			{
				return this._transactions;
			}
			set
			{
				this._transactions = value;
			}
		}
		public IList<System.String> uncles
		{
			get
			{
				return this._uncles;
			}
			set
			{
				this._uncles = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.blockNumber;
			case 1: return this.blockHash;
			case 2: return this.parentHash;
			case 3: return this.nonce;
			case 4: return this.sha3uncles;
			case 5: return this.logsBloom;
			case 6: return this.receiptsRoot;
			case 7: return this.transactionRoot;
			case 8: return this.stateRoot;
			case 9: return this.miner;
			case 10: return this.difficulty;
			case 11: return this.totalDifficulty;
			case 12: return this.extraData;
			case 13: return this.size;
			case 14: return this.gasLimit;
			case 15: return this.gasUsed;
			case 16: return this.timestamp;
			case 17: return this.transactions;
			case 18: return this.uncles;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.blockNumber = (System.Int64)fieldValue; break;
			case 1: this.blockHash = (System.String)fieldValue; break;
			case 2: this.parentHash = (System.String)fieldValue; break;
			case 3: this.nonce = (System.String)fieldValue; break;
			case 4: this.sha3uncles = (System.String)fieldValue; break;
			case 5: this.logsBloom = (System.String)fieldValue; break;
			case 6: this.receiptsRoot = (System.String)fieldValue; break;
			case 7: this.transactionRoot = (System.String)fieldValue; break;
			case 8: this.stateRoot = (System.String)fieldValue; break;
			case 9: this.miner = (System.String)fieldValue; break;
			case 10: this.difficulty = (System.String)fieldValue; break;
			case 11: this.totalDifficulty = (System.String)fieldValue; break;
			case 12: this.extraData = (System.Byte[])fieldValue; break;
			case 13: this.size = (System.Int64)fieldValue; break;
			case 14: this.gasLimit = (System.Int64)fieldValue; break;
			case 15: this.gasUsed = (System.Int64)fieldValue; break;
			case 16: this.timestamp = (System.Int64)fieldValue; break;
			case 17: this.transactions = (IList<Nethermind.PubSub.Kafka.Avro.Models.Transaction>)fieldValue; break;
			case 18: this.uncles = (IList<System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
