# Test config

# yaml only
MAX_COMMITTEES_PER_SLOT: 11
# json only: TargetCommitteeSize
# both yaml and json
MAX_VALIDATORS_PER_COMMITTEE: 13

# json only, different section: MinimumDepositAmount

# yaml only, no section in json
SECONDS_PER_SLOT: 15
