name: Remove GH Runner
description: "Remove a self-hosted GitHub Actions runner and destroy its machine"
inputs:
  gh-token:
    description: "The token of the GitHub App to use for authentication"
    required: true
  runner-name:
    description: "Name of the runner to remove from GitHub Actions"
    required: true
  workflow-run-id:
    description: "The workflow run ID from the machine creation (used to destroy the machine)"
    required: true

runs:
  using: "composite"

  steps:
    - name: Remove runner from GitHub Actions
      if: ${{ inputs.runner-name != '' }}
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        TARGET_RUNNER_NAME: ${{ inputs.runner-name }}
        ORG_NAME: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      shell: bash
      run: |
        echo "Removing runner '$TARGET_RUNNER_NAME' from GitHub Actions..."

        # Get the runner ID
        RUNNER_ID=$(gh api \
          --method GET \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${ORG_NAME}/${REPO_NAME}/actions/runners" \
          --jq ".runners[] | select(.name == \"$TARGET_RUNNER_NAME\") | .id")

        if [ -z "$RUNNER_ID" ]; then
          echo "Warning: Runner '$TARGET_RUNNER_NAME' not found in repository. It may have already been removed."
        else
          echo "Found runner with ID: $RUNNER_ID"

          # Remove the runner
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${ORG_NAME}/${REPO_NAME}/actions/runners/${RUNNER_ID}"

          echo "Runner removed successfully from GitHub Actions"
        fi

    - name: Trigger machine destruction workflow
      if: ${{ inputs.workflow-run-id != '' }}
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      shell: bash
      run: |
        echo "Triggering machine destruction workflow..."
        echo "Workflow Run ID: ${{ inputs.workflow-run-id }}"

        gh workflow run manual-destroy-smoketests.yml \
          --repo NethermindEth/post-merge-smoke-tests \
          --ref main \
          --field workflow_run_id="${{ inputs.workflow-run-id }}"

        echo "Machine destruction workflow triggered successfully"

    - name: Display removal summary
      shell: bash
      run: |
        echo "### Self-Hosted Runner Removed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Runner Name**: ${{ inputs.runner-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Workflow Run ID**: ${{ inputs.workflow-run-id }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The runner has been removed from GitHub Actions and the machine destruction workflow has been triggered." >> $GITHUB_STEP_SUMMARY
