<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Contracts\ValidatorContract.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Contracts\ValidatorContract.json" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Nethermind.Consensus.Qbft.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Api\Nethermind.Api.csproj" />
    <ProjectReference Include="..\Nethermind.Blockchain\Nethermind.Blockchain.csproj" />
    <ProjectReference Include="..\Nethermind.Consensus\Nethermind.Consensus.csproj" />
    <ProjectReference Include="..\Nethermind.Core\Nethermind.Core.csproj" />
    <ProjectReference Include="..\Nethermind.Init\Nethermind.Init.csproj" />
    <ProjectReference Include="..\Nethermind.JsonRpc\Nethermind.JsonRpc.csproj" />
    <ProjectReference Include="..\Nethermind.Network\Nethermind.Network.csproj" />
    <ProjectReference Include="..\Nethermind.Serialization.Rlp\Nethermind.Serialization.Rlp.csproj" />
    <ProjectReference Include="..\Nethermind.Specs\Nethermind.Specs.csproj" />
    <ProjectReference Include="..\Nethermind.State\Nethermind.State.csproj" />
  </ItemGroup>

</Project>
