// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Text;

namespace Nethermind.Serialization.JsonGenerator;

/// <summary>Emits the converter for one type, mirroring <c>JsonPropertyInfo&lt;T&gt;.GetMemberAndWriteJson</c> per property.</summary>
internal static class JsonWriterEmitter
{
    private const string Runtime = "global::Nethermind.Serialization.Json";
    private const string Stj = "global::System.Text.Json";

    public static string EmitWriter(TypeModel type)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        if (type.Namespace is not null)
        {
            sb.Append("namespace ").Append(type.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        string writer = type.WriterName;
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Nethermind.Serialization.JsonGenerator\", \"1.0.0\")]");
        sb.Append("internal sealed class ").Append(writer).Append(" : ").Append(Runtime).Append(".GeneratedJsonWriter<").Append(type.FullName).Append(", ").Append(writer).AppendLine(".State>");
        sb.AppendLine("{");

        EmitContract(sb, type);
        EmitCreateState(sb, type);
        EmitWrite(sb, type);
        EmitState(sb, type);

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitRegistration(IReadOnlyList<TypeModel> types)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        sb.AppendLine("namespace Nethermind.Generated.Json;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Nethermind.Serialization.JsonGenerator\", \"1.0.0\")]");
        sb.AppendLine("internal static class GeneratedJsonWriterRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Usage\", \"CA2255\", Justification = \"Registers the writers before any code in this assembly serializes.\")]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        EmitRegistrationCall(sb, "Register", types.Where(static t => t.RegisterWithSerializer).ToList());
        EmitRegistrationCall(sb, "RegisterForDispatch", types.Where(static t => !t.RegisterWithSerializer).ToList());
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegistrationCall(StringBuilder sb, string method, List<TypeModel> types)
    {
        if (types.Count == 0) return;
        sb.Append("        ").Append(Runtime).Append(".GeneratedJsonWriters.").Append(method).AppendLine("(");
        for (int i = 0; i < types.Count; i++)
        {
            TypeModel type = types[i];
            string name = type.Namespace is null ? "global::" + type.WriterName : "global::" + type.Namespace + "." + type.WriterName;
            sb.Append("            new ").Append(name).Append("()").AppendLine(i == types.Count - 1 ? ");" : ",");
        }
    }

    private static void EmitContract(StringBuilder sb, TypeModel type)
    {
        sb.Append("    private static readonly ").Append(Runtime).AppendLine(".GeneratedJsonProperty[] Contract =");
        sb.AppendLine("    [");
        foreach (PropertyModel p in type.Contract)
        {
            string explicitName = p.ExplicitName is null ? "null" : Literal(p.ExplicitName);
            string converter = p.ConverterTypeName is null ? "null" : $"typeof({p.ConverterTypeName})";
            string propertyType = p.Kind == ContractKind.Ignored ? "typeof(object)" : $"typeof({p.TypeName})";
            sb.Append("        new(").Append(Literal(p.MemberName)).Append(", ").Append(explicitName).Append(", ").Append(propertyType)
                .Append(", ").Append(converter).Append(", ").Append(Runtime).Append(".GeneratedJsonPropertyKind.").Append(p.Kind).AppendLine("),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
    }

    private static void EmitCreateState(StringBuilder sb, TypeModel type)
    {
        sb.Append("    protected override State CreateState(").Append(Stj).AppendLine(".JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.Append("        if (!").Append(Runtime).AppendLine(".GeneratedJsonWriters.SupportsOptions(options)) return null;");
        sb.Append("        ").Append(Stj).Append(".JsonEncodedText[] names = ").Append(Runtime).Append(".GeneratedJsonWriters.GetPropertyNames<").Append(type.FullName)
            .Append(">(options, Contract, ").Append(Bool(type.HasOnSerializing)).Append(", ").Append(Bool(type.HasOnSerialized)).Append(", out ")
            .Append(Stj).AppendLine(".Serialization.JsonConverter[] propertyConverters);");
        sb.AppendLine("        if (names is null) return null;");
        sb.Append("        ").Append(Stj).Append(".Serialization.JsonConverter[] converters = new ").Append(Stj).Append(".Serialization.JsonConverter[").Append(type.Contract.Length).AppendLine("];");
        for (int i = 0; i < type.Contract.Length; i++)
        {
            PropertyModel p = type.Contract[i];
            if (!p.Emit) continue;
            // A converter for another type that STJ adapts by casting cannot be called directly, so such a contract stays on the metadata path.
            sb.Append("        if (!").Append(Runtime).Append(".GeneratedJsonWriters.TryGetConverter<").Append(p.TypeName).Append(">(")
                .Append(p.ConverterTypeName is null ? "null" : $"propertyConverters[{i}]").Append(", options, out converters[").Append(i).AppendLine("])) return null;");
        }

        sb.AppendLine("        return new State(names, converters, options);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitWrite(StringBuilder sb, TypeModel type)
    {
        sb.Append("    protected override void Write(").Append(Stj).Append(".Utf8JsonWriter writer, ").Append(type.FullName).Append(" value, State state, ")
            .Append(Stj).AppendLine(".JsonSerializerOptions options)");
        sb.AppendLine("    {");
        if (type.HasOnSerializing) sb.Append("        ((").Append(Stj).AppendLine(".Serialization.IJsonOnSerializing)value).OnSerializing();");
        sb.AppendLine("        writer.WriteStartObject();");

        for (int i = 0; i < type.Contract.Length; i++)
        {
            PropertyModel p = type.Contract[i];
            if (!p.Emit) continue;
            EmitProperty(sb, p, i);
        }

        sb.AppendLine("        writer.WriteEndObject();");
        if (type.HasOnSerialized) sb.Append("        ((").Append(Stj).AppendLine(".Serialization.IJsonOnSerialized)value).OnSerialized();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitProperty(StringBuilder sb, PropertyModel p, int i)
    {
        string v = "v" + i;
        sb.AppendLine("        {");
        sb.Append("            ").Append(p.TypeName).Append(' ').Append(v).Append(" = ((").Append(p.DeclaringTypeName).Append(")value).@").Append(p.MemberName).AppendLine(";");
        sb.Append("            if (").Append(WriteCondition(p, v)).AppendLine(")");
        sb.AppendLine("            {");
        sb.Append("                writer.WritePropertyName(state.Name").Append(i).AppendLine(");");

        // A property-level converter replaces the object dispatch, as it does in the metadata path.
        string writeValue = p.IsObject && p.ConverterTypeName is null
            ? $"{Runtime}.TypeInfoJsonSerializer.Serialize(writer, {v}, typeof(object), options);"
            : $"state.Converter{i}.Write(writer, {v}, options);";
        string depthCheck = $"if (writer.CurrentDepth >= state.MaxDepth) {Runtime}.GeneratedJsonWriters.ThrowMaxDepthExceeded(state.MaxDepth);";

        if (p.NullKind == NullKind.Value)
        {
            sb.Append("                ").AppendLine(depthCheck);
            sb.Append("                ").AppendLine(writeValue);
        }
        else
        {
            // The metadata path hands null to the converter only when it handles null, and skips the depth check for it.
            sb.Append("                if (").Append(v).AppendLine(" is null)");
            sb.AppendLine("                {");
            sb.Append("                    if (state.HandleNull").Append(i).Append(") state.Converter").Append(i).Append(".Write(writer, ").Append(v).AppendLine(", options);");
            sb.AppendLine("                    else writer.WriteNullValue();");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.Append("                    ").AppendLine(depthCheck);
            sb.Append("                    ").AppendLine(writeValue);
            sb.AppendLine("                }");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static string WriteCondition(PropertyModel p, string v)
    {
        string isDefault = $"global::System.Collections.Generic.EqualityComparer<{p.TypeName}>.Default.Equals(default, {v})";
        bool canBeNull = p.NullKind != NullKind.Value;
        return p.IgnoreCondition switch
        {
            "Never" or "WhenReading" => "true",
            "WhenWritingNull" or "WhenWritingDefault" when canBeNull => $"{v} is not null",
            "WhenWritingDefault" => $"!{isDefault}",
            _ when canBeNull => $"{v} is not null || !state.SkipNull",
            _ => $"!state.SkipDefault || !{isDefault}",
        };
    }

    private static void EmitState(StringBuilder sb, TypeModel type)
    {
        sb.AppendLine("    internal sealed class State");
        sb.AppendLine("    {");
        sb.AppendLine("        public readonly int MaxDepth;");
        sb.AppendLine("        public readonly bool SkipNull;");
        sb.AppendLine("        public readonly bool SkipDefault;");
        for (int i = 0; i < type.Contract.Length; i++)
        {
            PropertyModel p = type.Contract[i];
            if (!p.Emit) continue;
            sb.Append("        public readonly ").Append(Stj).Append(".JsonEncodedText Name").Append(i).AppendLine(";");
            sb.Append("        public readonly ").Append(Stj).Append(".Serialization.JsonConverter<").Append(p.TypeName).Append("> Converter").Append(i).AppendLine(";");
            sb.Append("        public readonly bool HandleNull").Append(i).AppendLine(";");
        }

        sb.AppendLine();
        sb.Append("        public State(").Append(Stj).Append(".JsonEncodedText[] names, ").Append(Stj).Append(".Serialization.JsonConverter[] converters, ")
            .Append(Stj).AppendLine(".JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.Append("            MaxDepth = ").Append(Runtime).AppendLine(".GeneratedJsonWriters.GetMaxDepth(options);");
        sb.Append("            SkipNull = options.DefaultIgnoreCondition is ").Append(Stj).Append(".Serialization.JsonIgnoreCondition.WhenWritingNull or ")
            .Append(Stj).AppendLine(".Serialization.JsonIgnoreCondition.WhenWritingDefault;");
        sb.Append("            SkipDefault = options.DefaultIgnoreCondition == ").Append(Stj).AppendLine(".Serialization.JsonIgnoreCondition.WhenWritingDefault;");
        for (int i = 0; i < type.Contract.Length; i++)
        {
            PropertyModel p = type.Contract[i];
            if (!p.Emit) continue;
            sb.Append("            Name").Append(i).Append(" = names[").Append(i).AppendLine("];");
            sb.Append("            Converter").Append(i).Append(" = (").Append(Stj).Append(".Serialization.JsonConverter<").Append(p.TypeName).Append(">)converters[").Append(i).AppendLine("];");
            sb.Append("            HandleNull").Append(i).Append(" = Converter").Append(i).AppendLine(".HandleNull;");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Literal(string value) => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);
}
