<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nethermind.Eez.Test" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Api\Nethermind.Api.csproj" />
    <ProjectReference Include="..\Nethermind.Eez.Execution\Nethermind.Eez.Execution.csproj" />
  </ItemGroup>

</Project>
