FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build

COPY . .

RUN apk add git && \
 git submodule update --init src/Dirichlet src/int256 src/Math.Gmp.Native && \
 dotnet publish src/Nethermind/Nethermind.State.Test.Runner -c release -o out

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine

COPY --from=build /out .

ENTRYPOINT [ "./nethtest" ]