FROM alpine:3.12 AS rocksdb
WORKDIR /source

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories
RUN apk upgrade && apk add git build-base linux-headers bash perl snappy-dev@testing
RUN git clone --branch v6.4.6 https://github.com/facebook/rocksdb .
RUN PORTABLE=1 make shared_lib
RUN strip librocksdb.so

FROM alpine:3.12 AS librocksdb
WORKDIR /nethermind
COPY --from=rocksdb /source/librocksdb.so .