##################################################
FROM alpine:3.10 AS rocksdb
WORKDIR /source

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories
RUN apk upgrade && apk add git build-base linux-headers bash perl snappy-dev@testing
RUN git clone --branch v6.4.6 https://github.com/facebook/rocksdb .
RUN PORTABLE=1 make shared_lib
RUN strip librocksdb.so

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

COPY . .

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    echo "@v3.8 http://dl-cdn.alpinelinux.org/alpine/v3.8/main/" >> /etc/apk/repositories && \
    apk upgrade && apk add git openssl-dev@testing libssl1.0@v3.8 && \
    git submodule update --init src/Dirichlet src/rocksdb-sharp && \
    dotnet publish src/Nethermind/Nethermind.Runner -c release -o out && \
    git describe --tags --always --long > out/git-hash

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    apk upgrade && apk add coreutils gosu@testing snappy-dev@testing && rm -rf /var/cache/apk/*

WORKDIR /nethermind

COPY --from=build /out .
COPY --from=rocksdb /source/librocksdb.so /nethermind/librocksdb.so

ARG GIT_COMMIT=unspecified
LABEL git_commit=$GIT_COMMIT

ENTRYPOINT ["./Nethermind.Runner"]