##################################################
FROM alpine:3.10 as rocksdb
WORKDIR /source

RUN apk upgrade && apk add git build-base linux-headers bash perl
RUN git clone --branch v6.4.6 https://github.com/facebook/rocksdb .
RUN PORTABLE=1 make shared_lib
RUN strip librocksdb.so

##################################################
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

COPY . source/
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.8/main' >> /etc/apk/repositories
RUN apk upgrade && apk add git openssl-dev libssl1.0
RUN cd source/ && git submodule update --init src/Dirichlet src/rocksdb-sharp
RUN dotnet publish /source/src/Nethermind/Nethermind.Runner --configuration Release --output /artifacts
RUN cd source/ && git describe --tags --long > /artifacts/git-hash

##################################################
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

COPY scripts/entrypoint.sh /entrypoint.sh

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    apk upgrade && apk add coreutils gosu@testing snappy-dev@testing && rm -rf /var/cache/apk/* && \
    addgroup -g 1337 nethermind && adduser nethermind -u 1337 -D -G nethermind && \
    chmod +x /entrypoint.sh && \
    mkdir /data

COPY --from=build --chown=nethermind:nethermind /artifacts /nethermind
COPY --from=rocksdb --chown=nethermind:nethermind /source/librocksdb.so /nethermind/librocksdb.so

ENTRYPOINT ["/entrypoint.sh"]
