FROM debian@sha256:acf7795dc91df17e10effee064bd229580a9c34213b4dba578d64768af5d8c51 AS rocksdb
WORKDIR /source

ARG TARGETPLATFORM

RUN apt-get update && apt-get install -y git build-essential perl libzstd-dev liblz4-dev zlib1g-dev libsnappy-dev libbz2-dev

RUN if [ "$TARGETPLATFORM" = "linux/arm/v7" ] ; then git clone --branch v5.15.10 https://github.com/facebook/rocksdb . ; else git clone --branch v6.15.5 https://github.com/facebook/rocksdb . ; fi
RUN PORTABLE=1 make -j16 shared_lib

RUN strip librocksdb.so

FROM debian@sha256:acf7795dc91df17e10effee064bd229580a9c34213b4dba578d64768af5d8c51 AS librocksdb
WORKDIR /nethermind
COPY --from=rocksdb /source/librocksdb.so .
