FROM microsoft/dotnet:2.2-sdk AS build
COPY . .
RUN git submodule update --init
RUN apt-get update && apt-get -y install libsnappy-dev libc6-dev libc6 unzip
RUN cd src/Nethermind && dotnet build Nethermind.sln -c Release

EXPOSE 8345 30312

WORKDIR src/Nethermind





