##################################################
FROM alpine:3.10 AS secp256k1
WORKDIR /source

RUN apk upgrade && apk add git build-base autoconf automake libtool
RUN git clone https://github.com/bitcoin-core/secp256k1 .
RUN ./autogen.sh
RUN ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
RUN make
RUN strip .libs/libsecp256k1.so

##################################################
FROM alpine:3.10 AS rocksdb
WORKDIR /source

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories
RUN apk upgrade && apk add git build-base linux-headers bash perl snappy-dev@testing
RUN git clone --branch v6.1.2 https://github.com/facebook/rocksdb .
RUN PORTABLE=1 make shared_lib
RUN strip librocksdb.so

##################################################
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

COPY . .
RUN apt-get update && apt-get install -y libsnappy-dev libc6-dev libc6 libzstd1 libgflags-dev libssl1.0
RUN git submodule update --init src/Dirichlet src/rocksdb-sharp
RUN dotnet publish src/Nethermind/Nethermind.Runner --configuration Release --runtime linux-musl-arm64 --output out
RUN git describe --tags --always --long > out/git-hash

##################################################
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine-arm64v8

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    apk upgrade && apk add coreutils gosu@testing snappy-dev@testing && rm -rf /var/cache/apk/*

WORKDIR /nethermind

COPY --from=build /out .
COPY --from=secp256k1 /source/.libs/libsecp256k1.so /nethermind/runtimes/linux-x64/native/libsecp256k1.so
COPY --from=rocksdb /source/librocksdb.so /nethermind/runtimes/linux-arm64/native/librocksdb.so

ARG GIT_COMMIT=unspecified
LABEL git_commit=$GIT_COMMIT

ENTRYPOINT ["./Nethermind.Runner"]