FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

ARG TARGETPLATFORM
ARG BUILDPLATFORM

COPY . .

RUN git submodule update --init src/Dirichlet src/rocksdb-sharp && \
    dotnet publish src/Nethermind/Nethermind.Runner -r linux-arm -c release -o out && \
    git describe --tags --always --long > out/git-hash

FROM --platform=$TARGETPLATFORM mcr.microsoft.com/dotnet/core/aspnet:3.1
RUN apt-get update && apt-get -y install libsnappy-dev libc6-dev libc6 libzstd1 libgflags-dev libssl1.0
WORKDIR /nethermind
COPY --from=build /out .

ARG GIT_COMMIT=unspecified
LABEL git_commit=$GIT_COMMIT

COPY arm/arm32/librocksdb.so /nethermind/librocksdb.so
COPY arm/arm32/libsecp256k1.so /nethermind/runtimes/linux-x64/native/libsecp256k1.so

ENTRYPOINT ["./Nethermind.Runner"]
