// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System;
using Nethermind.Core;
using Nethermind.Core.Crypto;
using Nethermind.Crypto;
using NUnit.Framework;

namespace Nethermind.Crypto.LeanFfi.Test;

/// <summary>
/// Live test of the EIP-8288 native Lean verifier binding: it P/Invokes the real
/// <c>nethermind_lean</c> dylib (built from <c>tools/lean-ffi</c>) and checks that proofs generated by
/// the managed placeholder verify natively (proving the Rust and C# relations agree byte-for-byte),
/// and that tampered proofs are rejected. Skips if the native library is not present.
/// </summary>
public class NativeLeanProofVerifierTests
{
    private static readonly ILeanProofVerifier Native = NativeLeanProofVerifier.Instance;
    private static readonly byte[] Vk = Eip8288Constants.AggregatedVk;

    [OneTimeSetUp]
    public void EnsureNativeLibraryLoads()
    {
        try
        {
            Assert.That(NativeLeanProofVerifier.AbiVersion, Is.EqualTo(1u), "native ABI version mismatch");
        }
        catch (DllNotFoundException e)
        {
            Assert.Ignore($"native nethermind_lean library not available: {e.Message}");
        }
    }

    [Test]
    public void Recursive_proof_from_managed_prover_verifies_natively()
    {
        ValueHash256 depsHash = Keccak.Compute("deps").ValueHash256;
        byte[] proof = PlaceholderLeanProofVerifier.ProveRecursive(in depsHash, Vk);

        Assert.That(Native.VerifyRecursiveStark(in depsHash, Vk, proof), Is.True, "native must accept a managed-produced proof");
        Assert.That(Native.VerifyRecursiveStark(in depsHash, Vk, [9, 9, 9]), Is.False, "native must reject a tampered proof");
    }

    [Test]
    public void LeanSphincs_witness_from_managed_prover_verifies_natively()
    {
        ValueHash256 dataHash = Keccak.Compute("msg").ValueHash256;
        ValueHash256 vk = Keccak.Compute("pubkey").ValueHash256;
        byte[] witness = PlaceholderLeanProofVerifier.ProveLeanSphincs(in dataHash, in vk);

        Assert.That(Native.VerifyLeanSphincs(in dataHash, in vk, witness), Is.True);
        Assert.That(Native.VerifyLeanSphincs(in dataHash, in vk, [1]), Is.False);
    }

    [Test]
    public void LeanStark_witness_from_managed_prover_verifies_natively()
    {
        ValueHash256 dataHash = Keccak.Compute("pub_input").ValueHash256;
        ValueHash256 vk = Keccak.Compute("stark_vk").ValueHash256;
        byte[] witness = PlaceholderLeanProofVerifier.ProveLeanStark(in dataHash, in vk);

        Assert.That(Native.VerifyLeanStark(in dataHash, in vk, witness), Is.True);
        Assert.That(Native.VerifyLeanStark(in dataHash, in vk, [1]), Is.False);
    }

    [Test]
    public void Native_and_managed_verifiers_agree()
    {
        // The whole point of the placeholder matching: a node producing with the managed prover must
        // validate under the native verifier, and vice versa.
        ValueHash256 depsHash = Keccak.Compute("block").ValueHash256;
        byte[] proof = PlaceholderLeanProofVerifier.ProveRecursive(in depsHash, Vk);

        Assert.That(PlaceholderLeanProofVerifier.Instance.VerifyRecursiveStark(in depsHash, Vk, proof), Is.True);
        Assert.That(Native.VerifyRecursiveStark(in depsHash, Vk, proof), Is.True);
    }
}
