<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Api\Nethermind.Api.csproj" />
    <ProjectReference Include="..\Nethermind.Init\Nethermind.Init.csproj" />
  </ItemGroup>

</Project>
