#!/bin/bash

arch=$(uname -m)

if [[ $arch == x86_64* ]]; then
  curl -s https://api.github.com/repos/NethermindEth/nethermind/releases/latest | jq -r ".assets[] | select(.name) | .browser_download_url" | grep linux-x64 | xargs wget -O nethermind.zip -q
  ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so > /dev/null 2>&1
elif  [[ $arch == arm* ]] || [[ $arch = aarch64 ]]; then
  curl -s https://api.github.com/repos/NethermindEth/nethermind/releases/latest | jq -r ".assets[] | select(.name) | .browser_download_url" | grep linux-arm64 | xargs wget -O nethermind.zip -q
  ln -s /usr/lib/aarch64-linux-gnu/libdl.so.2 /usr/lib/aarch64-linux-gnu/libdl.so > /dev/null 2>&1
  apt update > /dev/null 2>&1 && apt install libgflags-dev -y > /dev/null 2>&1
fi

unzip nethermind.zip -d nethermind
rm -rf nethermind.zip
mkdir -p /usr/share/nethermind
cp -r nethermind/* /usr/share/nethermind
rm -rf nethermind

wget https://raw.githubusercontent.com/NethermindEth/nethermind/master/scripts/execution.sh -O /usr/bin/nethermind
chmod +x /usr/bin/nethermind
