// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

/// <summary>Emits concrete JSON writer bodies from explicit field bindings while retaining their original method boundaries.</summary>
[Generator]
public sealed class BeaconJsonShapeGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<AdditionalText> schemas = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".beacon-json", StringComparison.Ordinal));
        context.RegisterSourceOutput(schemas.Collect().Combine(context.CompilationProvider), static (output, input) =>
        {
            if (input.Left.Length == 0) return;
            try
            {
                if (input.Left.Length != 1) throw new InvalidOperationException("Exactly one Beacon JSON schema is supported.");
                output.AddSource("BeaconJsonWriter.g.cs", SourceText.From(Generate(input.Left[0].GetText(output.CancellationToken)!.ToString(), input.Right), Encoding.UTF8));
            }
            catch (InvalidOperationException e)
            {
                string path = input.Left[0].Path.Replace("\\", "\\\\").Replace("\"", "\\\"");
                string message = e.Message.Replace('\r', ' ').Replace('\n', ' ');
                output.AddSource("BeaconJsonWriter.g.cs", SourceText.From($"#line 1 \"{path}\"\n#error Beacon JSON generation failed: {message}\n", Encoding.UTF8));
            }
        });
    }

    private sealed record Field(IPropertySymbol Property, string WireName);
    private sealed record Method(string Access, string Name, string Type, string Parameter, string Prefix, bool Array);

    private static string Generate(string schema, Compilation compilation)
    {
        Dictionary<string, Field[]> fields = new(StringComparer.Ordinal);
        Dictionary<string, Method> methods = new(StringComparer.Ordinal);
        foreach (string raw in schema.Replace("\r", "").Split('\n'))
        {
            string[] parts = raw.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 0 || parts[0].StartsWith("#", StringComparison.Ordinal)) continue;
            if (parts[0] == "method")
            {
                if (parts.Length != 7) throw new InvalidOperationException("Expected method access name type parameter prefix.");
                string type = parts[3];
                methods.Add(type, new(parts[1], parts[2], type, parts[4], parts[5], parts[6] == "array"));
                continue;
            }
            INamedTypeSymbol symbol = compilation.GetTypeByMetadataName("Nethermind.BeaconChain.Types." + parts[0])
                ?? throw new InvalidOperationException("Unknown type " + parts[0]);
            IPropertySymbol[] properties = SszType.GetOrderedPublicProperties(symbol).ToArray();
            if (parts.Length != properties.Length + 1) throw new InvalidOperationException("Field count does not match SSZ schema: " + symbol.Name);
            Field[] table = new Field[properties.Length];
            for (int index = 0; index < properties.Length; index++)
            {
                string[] binding = parts[index + 1].Split('=');
                if (binding.Length != 2 || binding[0] != properties[index].Name) throw new InvalidOperationException("Unknown or reordered property in " + symbol.Name);
                table[index] = new(properties[index], binding[1]);
            }
            fields.Add(symbol.Name, table);
        }
        StringBuilder code = new("// <auto-generated/>\n#nullable enable\nusing System.Text.Json;\nusing System.Threading.Tasks;\nusing Nethermind.Merge.Plugin.SszRest;\nusing Nethermind.BeaconChain.Types;\nusing Nethermind.Core.Crypto;\nnamespace Nethermind.BeaconChain.Api.Common;\ninternal static partial class BeaconJsonWriter\n{\n");
        foreach (Method method in methods.Values)
        {
            if (method.Access == "retained") continue;
            bool async = method.Name == "WriteBeaconStateAsync";
            string type = method.Array ? method.Type + "[]" : method.Type;
            code.Append($"{method.Access} static {(async ? "async partial Task" : "partial void")} {method.Name}({(async ? "BeaconJsonStream s" : "Utf8JsonWriter w")}, {type} {method.Parameter})\n{{\n");
            if (async) code.Append("Utf8JsonWriter w = s.Writer;\n");
            if (method.Prefix != "-") code.Append(method.Array ? $"w.WriteStartArray(\"{method.Prefix}\");\n" : $"w.WritePropertyName(\"{method.Prefix}\");\n");
            if (method.Array)
            {
                if (method.Prefix == "-") code.Append("w.WriteStartArray();\n");
                EmitArray(code, method.Type, method.Parameter, fields, methods,
                    compilation.GetTypeByMetadataName((method.Type == "SszKzgCommitment" ? "Nethermind.Merge.Plugin.SszRest." : "Nethermind.BeaconChain.Types.") + method.Type));
                code.Append("w.WriteEndArray();\n");
            }
            else
            {
                if (method.Type is "SignedExecutionPayloadBid" or "SignedExecutionPayloadEnvelope")
                {
                    Field message = fields[method.Type][0];
                    string variable = method.Type == "SignedExecutionPayloadBid" ? "bid" : "message";
                    code.Append($"{message.Property.Type.Name} {variable} = {method.Parameter}.Message!;\n");
                }
                EmitObject(code, method.Type, method.Parameter, fields, methods, async);
            }
            code.Append("}\n");
        }
        return code.Append("}\n").ToString();
    }

    private static void EmitObject(StringBuilder code, string type, string value, Dictionary<string, Field[]> fields, Dictionary<string, Method> methods, bool async)
    {
        code.Append("w.WriteStartObject();\n");
        foreach (Field field in fields[type])
        {
            string expression = value + "." + field.Property.Name + "!";
            if (field.Property.Name == "Message")
            {
                if (type == "SignedExecutionPayloadBid") expression = "bid";
                if (type == "SignedExecutionPayloadEnvelope") expression = "message";
            }
            if (async && field.Property.Type is IArrayTypeSymbol array)
            {
                string helper = array.ElementType.Name switch
                {
                    "Hash256" => "WriteHashArrayAsync",
                    "UInt64" => "WriteUIntArrayAsync",
                    "Byte" => "WriteParticipationAsync",
                    _ => "WriteArrayAsync",
                };
                code.Append($"await {helper}(s, \"{field.WireName}\", {expression}");
                if (helper == "WriteArrayAsync")
                {
                    if (methods.TryGetValue(array.ElementType.Name, out Method? itemMethod)) code.Append($", {itemMethod.Name}");
                    else
                    {
                        code.Append(", static (w, summary) =>\n{\n");
                        EmitObject(code, array.ElementType.Name, "summary", fields, methods, false);
                        code.Append("}");
                    }
                }
                code.Append(");\n");
                continue;
            }
            if (async && field.Property.Type.Name == "SyncCommittee")
            {
                code.Append($"await WriteSyncCommitteeAsync(s, \"{field.WireName}\", {expression});\n");
                continue;
            }
            EmitField(code, field, expression, fields, methods);
        }
        if (type == "BeaconStateElectra") code.Append("if (state is BeaconStateFulu fulu) await WriteUIntArrayAsync(s, \"proposer_lookahead\", fulu.ProposerLookahead!);\n");
        code.Append("w.WriteEndObject();\n");
    }

    private static void EmitField(StringBuilder code, Field field, string value, Dictionary<string, Field[]> fields, Dictionary<string, Method> methods)
    {
        ITypeSymbol type = field.Property.Type;
        if (type.Name == "IndexedAttestationGloas")
        {
            code.Append($"w.WritePropertyName(\"{field.WireName}\");\n");
            code.Append($"WriteIndexedAttestation(w, {value}.AttestingIndices!, {value}.Data!, {value}.Signature);\n");
            return;
        }
        if (type is IArrayTypeSymbol array && array.ElementType.SpecialType != SpecialType.System_Byte)
        {
            if (methods.TryGetValue(array.ElementType.Name, out Method? method) && method.Array)
            {
                if (method.Prefix == "-") code.Append($"w.WritePropertyName(\"{field.WireName}\");\n");
                code.Append($"{method.Name}(w, {value});\n");
            }
            else
            {
                code.Append($"w.WriteStartArray(\"{field.WireName}\");\n");
                EmitArray(code, array.ElementType.Name, value, fields, methods, array.ElementType);
                code.Append("w.WriteEndArray();\n");
            }
            return;
        }
        if (!fields.ContainsKey(type.Name))
        {
            EmitPrimitive(code, type, value, field.WireName, field.Property);
            return;
        }
        if (methods.TryGetValue(type.Name, out Method? container) && !container.Array)
        {
            if (container.Prefix == "-") code.Append($"w.WritePropertyName(\"{field.WireName}\");\n");
            code.Append($"{container.Name}(w, {value});\n");
            return;
        }
        code.Append($"w.WritePropertyName(\"{field.WireName}\");\n");
        if (type.Name == "BeaconBlockGloas")
        {
            code.Append($"BeaconBlockGloas message = {value};\n");
            value = "message";
        }
        EmitObject(code, type.Name, value, fields, methods, false);
    }

    private static void EmitArray(StringBuilder code, string type, string value, Dictionary<string, Field[]> fields,
        Dictionary<string, Method> methods, ITypeSymbol? symbol)
    {
        string item = type switch
        {
            "AttesterSlashing" or "AttesterSlashingGloas" or "ProposerSlashing" => "slashing",
            "PayloadAttestation" => "attestation",
            "BuilderDepositRequest" or "Deposit" or "DepositRequest" => "deposit",
            "BuilderExitRequest" or "SignedVoluntaryExit" => "exit",
            "SignedBlsToExecutionChange" => "change",
            "SszKzgCommitment" => "commitment",
            "Hash256" => "node",
            "Transaction" or "TransactionGloas" => "transaction",
            "Withdrawal" or "WithdrawalRequest" => "withdrawal",
            "ConsolidationRequest" => "consolidation",
            _ => throw new InvalidOperationException("No original loop binding for " + type),
        };
        string spelling = type is "Transaction" or "Withdrawal" ? "Types." + type : type;
        code.Append($"foreach ({spelling} {item} in {value})\n");
        if (fields.ContainsKey(type))
        {
            code.Append("{\n");
            EmitObject(code, type, item, fields, methods, false);
            code.Append("}\n");
        }
        else EmitPrimitive(code, symbol ?? throw new InvalidOperationException("Unknown primitive " + type), item, null, null);
    }

    private static void EmitPrimitive(StringBuilder code, ITypeSymbol type, string value, string? name, IPropertySymbol? property)
    {
        string argument = name is null ? string.Empty : $"\"{name}\", ";
        string suffix = name is null ? "Value" : string.Empty;
        switch (type.SpecialType)
        {
            case SpecialType.System_UInt64:
            case SpecialType.System_Byte:
                code.Append($"WriteUInt{suffix}(w, {argument}{value});\n");
                return;
            case SpecialType.System_Boolean:
                code.Append($"w.WriteBoolean{suffix}({argument}{value});\n");
                return;
        }
        if (type.Name == "UInt256") code.Append($"w.WriteString{suffix}({argument}{value}.ToString());\n");
        else if (type.Name == "BitArray")
        {
            bool list = property!.GetAttributes().Any(attribute => attribute.AttributeClass?.Name is "SszListAttribute" or "SszProgressiveBitlistAttribute");
            code.Append($"WriteBit{(list ? "List" : "Vector")}(w, {argument}{value});\n");
        }
        else
        {
            string bytes = type.Name switch
            {
                "SszKzgCommitment" => value + ".AsSpan()",
                "Transaction" or "TransactionGloas" => value + ".Bytes!",
                _ when type is IArrayTypeSymbol => value,
                _ => value + ".Bytes",
            };
            code.Append($"WriteHex{suffix}(w, {argument}{bytes});\n");
        }
    }
}
