using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Nethermind.Serialization.Ssz;
using System.Text;
using System.Text.RegularExpressions;

[Generator]
public class SszGenerator : IIncrementalGenerator
{
    private const string GeneratedSourceHeader = "// <auto-generated/>\n#nullable enable\n";

    private static readonly DiagnosticDescriptor GenerationFailureRule = new(
        "SSZ003",
        "SSZ source generation failed",
        "Failed to generate SSZ code for '{0}': {1}",
        "SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NestedTypeNotSupportedRule = new(
        "SSZ004",
        "SSZ types must be top-level",
        "SSZ container '{0}' is nested inside another type and is not supported by the source generator",
        "SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static spc =>
            spc.AddSource("Serialization.SszCodec.Helpers.cs", SourceText.From(GenerateHelpersCode(), Encoding.UTF8)));

        IncrementalValuesProvider<(SszType Type, List<SszType> FoundTypes, Location? Location, bool IsNested)?> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => IsClassWithAttribute(syntaxNode),
                transform: (context, _) => GetClassWithAttribute(context))
            .Where(classNode => classNode is not null);

        context.RegisterSourceOutput(classDeclarations, (spc, decl) =>
        {
            if (decl is null)
            {
                return;
            }

            if (decl.Value.IsNested)
            {
                spc.ReportDiagnostic(Diagnostic.Create(NestedTypeNotSupportedRule, decl.Value.Location ?? Location.None, decl.Value.Type.Name));
                return;
            }

            string? generatedCode = GenerateClassCode(spc, decl.Value.Type, decl.Value.FoundTypes, decl.Value.Location);
            if (generatedCode is not null)
            {
                spc.AddSource($"Serialization.SszCodec.{decl.Value.Type.Name}.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
        });
    }

    private static string PartialTypeDeclaration(SszType decl) =>
        $"partial {(decl.IsStruct ? "struct" : "class")} {decl.Name} : ISszCodec<{decl.Name}>";

    private static string NamespaceLine(SszType decl) =>
        string.IsNullOrEmpty(decl.Namespace) ? string.Empty : $"namespace {decl.Namespace};";

    private static bool IsClassWithAttribute(SyntaxNode syntaxNode) =>
        syntaxNode is TypeDeclarationSyntax classDeclaration &&
        classDeclaration.AttributeLists.Any(x => x.Attributes.Any());

    private static (SszType Type, List<SszType> FoundTypes, Location? Location, bool IsNested)? GetClassWithAttribute(GeneratorSyntaxContext context)
    {
        TypeDeclarationSyntax classDeclaration = (TypeDeclarationSyntax)context.Node;
        foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
        {
            foreach (AttributeSyntax attribute in attributeList.Attributes)
            {
                IMethodSymbol? methodSymbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
                if (methodSymbol is not null && IsSszRootAttribute(methodSymbol.ContainingType))
                {
                    INamedTypeSymbol typeSymbol = (INamedTypeSymbol)context.SemanticModel.GetDeclaredSymbol(classDeclaration)!;
                    List<SszType> foundTypes = new(SszType.BasicTypes);
                    return (
                        SszType.From(context.SemanticModel, foundTypes, typeSymbol),
                        foundTypes,
                        classDeclaration.Identifier.GetLocation(),
                        typeSymbol.ContainingType is not null);
                }
            }
        }
        return null;
    }

    private static bool IsSszRootAttribute(INamedTypeSymbol attributeType) =>
        attributeType.Name is nameof(SszContainerAttribute) or nameof(SszCompatibleUnionAttribute);

    const string Whitespace = "/**/";
    private const int UnboundedBitlistLimit = 0;
    static readonly Regex OpeningWhiteSpaceRegex = new("{/(\\n\\s+)+\\n/");
    static readonly Regex ClosingWhiteSpaceRegex = new("/(\\s+\\n)+    }/");
    public static string FixWhitespace(string data) => OpeningWhiteSpaceRegex.Replace(
                                                        ClosingWhiteSpaceRegex.Replace(
                                                            string.Join("\n", data.Split('\n').Where(x => !string.IsNullOrWhiteSpace(x)).Select(x => x.Contains(Whitespace) ? "" : x)),
                                                            "    }"),
                                                        "{\n"
        );
    public static string Shift(int tabCount, string data) => string.Empty.PadLeft(4 * tabCount) + data;
    public static string Shift(int tabCount, IEnumerable<string> data, string? end = null) => string.Join("\n", data.Select(d => Shift(tabCount, d))) + (end is null || !data.Any() ? "" : end);

    private static string GenerateHelpersCode() =>
"""
// <auto-generated/>
#nullable enable
using Nethermind.Int256;
using Nethermind.Merkleization;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;

namespace Nethermind.Serialization;

internal static class SszCodecHelpers
{
    private const int SszOffsetSize = 4;

    internal static T ThrowInvalidSszData<T>(string typeName, string message) =>
        throw new InvalidDataException($"Invalid SSZ data for {typeName}: {message}");

    internal static void ThrowInvalidSszData(string typeName, string message) =>
        throw new InvalidDataException($"Invalid SSZ data for {typeName}: {message}");

    internal static void ThrowInvalidSszValue(string typeName, string fieldName, string message) =>
        throw new InvalidDataException($"Invalid SSZ value for {typeName}.{fieldName}: {message}");

    internal static void ValidateSszExactLength(int actualLength, int expectedLength, string typeName)
    {
        if (actualLength != expectedLength)
        {
            ThrowInvalidSszData(typeName, $"expected {expectedLength} bytes but found {actualLength}.");
        }
    }

    internal static void ValidateSszMinimumLength(int actualLength, int minimumLength, string typeName)
    {
        if (actualLength < minimumLength)
        {
            ThrowInvalidSszData(typeName, $"expected at least {minimumLength} bytes but found {actualLength}.");
        }
    }

    internal static void ValidateSszMultipleOf(int actualLength, int itemLength, string typeName)
    {
        if (actualLength % itemLength != 0)
        {
            ThrowInvalidSszData(typeName, $"expected a multiple of {itemLength} bytes but found {actualLength}.");
        }
    }

    internal static void ValidateSszDynamicOffsets(ReadOnlySpan<byte> data, int fixedLength, string typeName, ReadOnlySpan<int> offsets)
    {
        ValidateSszMinimumLength(data.Length, fixedLength, typeName);

        if (offsets.Length is 0)
        {
            return;
        }

        if (offsets[0] != fixedLength)
        {
            ThrowInvalidSszData(typeName, $"expected the first offset to be {fixedLength} but found {offsets[0]}.");
        }

        int previous = fixedLength;
        for (int index = 0; index < offsets.Length; index++)
        {
            int current = offsets[index];
            if (current < previous)
            {
                ThrowInvalidSszData(typeName, $"offset #{index} is out of order ({current} < {previous}).");
            }

            if (current > data.Length)
            {
                ThrowInvalidSszData(typeName, $"offset #{index} ({current}) exceeds the input length {data.Length}.");
            }

            previous = current;
        }
    }

    internal static int ValidateSszVariableItemCount(ReadOnlySpan<byte> data, int firstOffset, string typeName)
    {
        ValidateSszMinimumLength(data.Length, SszOffsetSize, typeName);

        if (firstOffset < SszOffsetSize)
        {
            ThrowInvalidSszData(typeName, $"expected the first offset to be at least {SszOffsetSize} but found {firstOffset}.");
        }

        if (firstOffset > data.Length)
        {
            ThrowInvalidSszData(typeName, $"the first offset {firstOffset} exceeds the input length {data.Length}.");
        }

        if (firstOffset % SszOffsetSize != 0)
        {
            ThrowInvalidSszData(typeName, $"the first offset {firstOffset} is not aligned to {SszOffsetSize}-byte offsets.");
        }

        return firstOffset / SszOffsetSize;
    }

    internal static void ValidateSszNextOffset(ReadOnlySpan<byte> data, int currentOffset, int nextOffset, string typeName)
    {
        if (nextOffset < currentOffset)
        {
            ThrowInvalidSszData(typeName, $"offsets are out of order ({nextOffset} < {currentOffset}).");
        }

        if (nextOffset > data.Length)
        {
            ThrowInvalidSszData(typeName, $"offset {nextOffset} exceeds the input length {data.Length}.");
        }
    }

    internal static void ValidateSszVectorLength<T>(ReadOnlySpan<T> items, int expectedLength, string typeName, string fieldName)
    {
        if (items.Length != expectedLength)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected {expectedLength} elements but found {items.Length}.");
        }
    }

    internal static void ValidateSszListLimit<T>(ReadOnlySpan<T> items, int limit, string typeName, string fieldName)
    {
        if (items.Length > limit)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected at most {limit} elements but found {items.Length}.");
        }
    }

    internal static void ValidateSszBitvectorLength(BitArray? bits, int expectedLength, string typeName, string fieldName)
    {
        int actualLength = bits?.Length ?? 0;
        if (bits is null || actualLength != expectedLength)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected {expectedLength} bits but found {actualLength}.");
        }
    }

    internal static void ValidateSszBitlistLimit(BitArray? bits, int limit, string typeName, string fieldName)
    {
        if (bits is not null && bits.Length > limit)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected at most {limit} bits but found {bits.Length}.");
        }
    }

    internal static void DecodeSszBitVector(ReadOnlySpan<byte> data, int vectorLength, out BitArray value)
    {
        ValidateSszExactLength(data.Length, (vectorLength + 7) / 8, $"bitvector[{vectorLength}]");
        Nethermind.Serialization.Ssz.Ssz.Decode(data, vectorLength, out value);
    }

    internal static void DecodeSszBitList(ReadOnlySpan<byte> data, string typeName, out BitArray value)
    {
        ValidateSszMinimumLength(data.Length, 1, typeName);
        Nethermind.Serialization.Ssz.Ssz.Decode(data, out value);
    }

    internal static void MerkleizeBasicVector<T>(ReadOnlySpan<T> values, int itemSize, ulong length, out UInt256 root)
        where T : struct
    {
        ulong chunkCount = (length * (ulong)itemSize + 31UL) / 32UL;
        Merkle.Merkleize(out root, MemoryMarshal.AsBytes(values), chunkCount);
    }

    internal static void MerkleizeBasicList<T>(ReadOnlySpan<T> values, int itemSize, ulong limit, out UInt256 root)
        where T : struct
    {
        ulong chunkCount = (limit * (ulong)itemSize + 31UL) / 32UL;
        Merkle.Merkleize(out root, MemoryMarshal.AsBytes(values), chunkCount);
        Merkle.MixIn(ref root, values.Length);
    }

    private static void MerkleizeProgressiveBytes(ReadOnlySpan<byte> value, out UInt256 root)
    {
        if (value.Length is 0)
        {
            root = UInt256.Zero;
            return;
        }

        int chunkCount = (value.Length + 31) / 32;
        UInt256[] chunks = new UInt256[chunkCount];
        int fullByteLength = value.Length / 32 * 32;
        if (fullByteLength > 0)
        {
            MemoryMarshal.Cast<byte, UInt256>(value[..fullByteLength]).CopyTo(chunks);
        }

        if (fullByteLength != value.Length)
        {
            Span<byte> lastChunk = stackalloc byte[32];
            value[fullByteLength..].CopyTo(lastChunk);
            chunks[^1] = new UInt256(lastChunk);
        }

        Merkle.MerkleizeProgressive(out root, chunks);
    }

    internal static void MerkleizeProgressiveBasicList<T>(ReadOnlySpan<T> values, out UInt256 root)
        where T : struct
    {
        MerkleizeProgressiveBytes(MemoryMarshal.AsBytes(values), out root);
        Merkle.MixIn(ref root, values.Length);
    }

    internal static void MerkleizeProgressiveBitList(BitArray? value, out UInt256 root)
    {
        BitArray bits = value ?? new BitArray(0);
        int byteLength = (bits.Length + 7) / 8;
        byte[] bytes = new byte[byteLength];
        bits.CopyTo(bytes, 0);
        MerkleizeProgressiveBytes(bytes, out root);
        Merkle.MixIn(ref root, bits.Length);
    }
}
""";

    private static string VarName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;

        string lowerCased = name.Substring(0, 1).ToLower() + name.Substring(1);

        return lowerCased == "data" || lowerCased == "container" || lowerCased.Contains("offset") ? $"_{lowerCased}" : lowerCased;
    }

    private static string ValidationStatement(SszType decl, SszProperty property, string expression)
    {
        return property.Kind switch
        {
            Kind.Vector when property.Type.Name == "BitArray" => $"ValidateSszBitvectorLength({expression}, {property.Length}, nameof({decl.Name}), nameof({decl.Name}.{property.Name}));",
            Kind.Vector => $"ValidateSszVectorLength({SpanExpression(property, expression)}, {property.Length}, nameof({decl.Name}), nameof({decl.Name}.{property.Name}));",
            Kind.List when property.Type.Name == "BitArray" => $"ValidateSszBitlistLimit({expression}, {property.Limit}, nameof({decl.Name}), nameof({decl.Name}.{property.Name}));",
            Kind.List => $"ValidateSszListLimit({SpanExpression(property, expression)}, {property.Limit}, nameof({decl.Name}), nameof({decl.Name}.{property.Name}));",
            Kind.BitVector => $"ValidateSszBitvectorLength({expression}, {property.Length}, nameof({decl.Name}), nameof({decl.Name}.{property.Name}));",
            Kind.BitList => $"ValidateSszBitlistLimit({expression}, {property.Limit}, nameof({decl.Name}), nameof({decl.Name}.{property.Name}));",
            _ => string.Empty,
        };
    }

    private static string EncodeValueExpression(SszProperty property, string expression) =>
        property.Kind is Kind.BitList or Kind.ProgressiveBitList ? $"{expression} ?? new BitArray(0)" : expression;

    /// <summary>
    /// Wraps <paramref name="expression"/> in a <see cref="System.ReadOnlySpan{T}"/>.
    /// Both bridges return an empty span when the source is null.
    /// </summary>
    /// <remarks>
    /// The non-array branch emits <c>CollectionsMarshal.AsSpan(...)</c>, which only accepts
    /// <see cref="System.Collections.Generic.List{T}"/>. Declaring an SSZ property as
    /// <c>IList&lt;T&gt;?</c>, <c>IReadOnlyList&lt;T&gt;?</c>, or any custom collection type will
    /// produce a generated file that fails to compile — surface a clearer contract here if that
    /// ever becomes a real constraint.
    /// </remarks>
    private static string SpanExpression(SszProperty property, string expression) =>
        property.IsArrayProperty ? $"{expression}.AsSpan()" : $"CollectionsMarshal.AsSpan({expression})";

    private static IEnumerable<string> ValidationStatements(SszType decl, IEnumerable<SszProperty> properties, string expressionPrefix)
    {
        foreach (SszProperty property in properties)
        {
            string validation = ValidationStatement(decl, property, $"{expressionPrefix}.{property.Name}");
            if (!string.IsNullOrEmpty(validation))
            {
                yield return validation;
            }
        }
    }

    private static string DecodeAndAssign(SszType decl, SszProperty property, string sliceExpression)
    {
        string variableName = VarName(property.Name);
        string outType = property.Kind switch
        {
            Kind.BitVector or Kind.BitList or Kind.ProgressiveBitList => "BitArray",
            _ when property.IsCollection => property.HandledByStd ? $"ReadOnlySpan<{property.Type.Name}>" : $"{property.Type.Name}[]",
            _ => property.Type.Name,
        };

        string decode = property.Kind switch
        {
            Kind.BitVector => $"DecodeSszBitVector({sliceExpression}, {property.Length}, out {outType} {variableName});",
            Kind.BitList or Kind.ProgressiveBitList => $"DecodeSszBitList({sliceExpression}, nameof({decl.Name}), out {outType} {variableName});",
            _ when property.HandledByStd => $"SszLib.Decode({sliceExpression}, out {outType} {variableName});",
            _ => $"{property.Type.Name}.Decode({sliceExpression}, out {outType} {variableName});",
        };

        string assignment = property.IsCollection ? $"container.{property.Name} = [ ..{variableName}];" : $"container.{property.Name} = {variableName};";
        string validation = ValidationStatement(decl, property, $"container.{property.Name}");
        return string.IsNullOrEmpty(validation) ? $"{decode} {assignment}" : $"{decode} {assignment} {validation}";
    }

    private static string MerkleizeRootStatement(SszProperty property, string expression, string rootName)
    {
        return property.Kind switch
        {
            Kind.Basic => $"Merkle.Merkleize(out {rootName}, {expression});",
            Kind.BitVector => $"Merkle.Merkleize(out {rootName}, {expression}!);",
            Kind.BitList => $"Merkle.Merkleize(out {rootName}, {expression} ?? new BitArray(0), {property.Limit});",
            Kind.ProgressiveBitList => $"MerkleizeProgressiveBitList({expression}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic => $"MerkleizeBasicVector({SpanExpression(property, expression)}, {property.Type.StaticLength}, {property.Length}, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic => $"MerkleizeBasicList({SpanExpression(property, expression)}, {property.Type.StaticLength}, {property.Limit}, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic => $"MerkleizeProgressiveBasicList({SpanExpression(property, expression)}, out {rootName});",
            Kind.Vector => $"{property.Type.Name}.MerkleizeVector({SpanExpression(property, expression)}, out {rootName});",
            Kind.List => $"{property.Type.Name}.MerkleizeList({SpanExpression(property, expression)}, {property.Limit}, out {rootName});",
            Kind.ProgressiveList => $"{property.Type.Name}.MerkleizeProgressiveList({SpanExpression(property, expression)}, out {rootName});",
            _ => $"{property.Type.Name}.Merkleize({expression}, out {rootName});",
        };
    }

    private static string MerkleizeFeedStatement(SszProperty property, string expression)
    {
        return property.Kind switch
        {
            Kind.Basic => $"merkleizer.Feed({expression});",
            Kind.BitVector => $"merkleizer.Feed({expression});",
            Kind.BitList => $"merkleizer.Feed({expression} ?? new BitArray(0), {property.Limit});",
            _ => $"{MerkleizeRootStatement(property, expression, $"UInt256 {VarName(property.Name)}Root")} merkleizer.Feed({VarName(property.Name)}Root);",
        };
    }

    private static string DynamicLength(SszType container, SszProperty m)
    {
        if ((m.Kind & (Kind.Collection | Kind.BitList | Kind.ProgressiveBitList)) != Kind.None && m.Type.Kind == Kind.Basic)
        {
            return m.Kind is Kind.BitList or Kind.ProgressiveBitList
                ? $"(container.{m.Name} is not null ? container.{m.Name}.Length / 8 + 1 : 1)"
                : $"({m.Type.StaticLength} * {SpanExpression(m, $"container.{m.Name}")}.Length)";
        }

        return m.IsCollection
            ? $"{m.Type.Name}.GetLength({SpanExpression(m, $"container.{m.Name}")})"
            : $"{m.Type.Name}.GetLength(container.{m.Name})";
    }

    private static string ByteArrayLiteral(byte[] value) => $"[{string.Join(", ", value)}]";

    private static string ProgressiveContainerMerkleizeBody(SszType decl)
    {
        string activeFields = ByteArrayLiteral(decl.ActiveFieldsBytes ?? []);
        IEnumerable<string> memberRoots = decl.Members!.Select((m, index) =>
        {
            string validation = ValidationStatement(decl, m, $"container.{m.Name}");
            string merkleize = MerkleizeRootStatement(m, $"container.{m.Name}", $"subRoots[{index}]");
            return string.IsNullOrEmpty(validation) ? merkleize : $"{validation} {merkleize}";
        });

        return $@"UInt256[] subRoots = new UInt256[{decl.Members!.Length}];
{Shift(2, memberRoots)}
        Merkle.MerkleizeProgressive(out root, subRoots);
        Merkle.MixInActiveFields(ref root, {activeFields});";
    }

    private static string EncodeStatement(string target, SszProperty property, string expression)
    {
        string arguments = $"{target}, {EncodeValueExpression(property, expression)}";
        if (property.Kind == Kind.BitList)
        {
            arguments += $", {property.Limit}";
        }
        else if (property.Kind == Kind.ProgressiveBitList)
        {
            arguments += $", {UnboundedBitlistLimit}"; // Progressive bitlists are intentionally unbounded.
        }

        return $"{(property.HandledByStd ? "SszLib.Encode" : $"{property.Type.Name}.Encode")}({arguments});";
    }

    private static bool RequiresNullGuard(SszProperty property) => !(property.Type.IsStruct || property.Kind is Kind.BitList or Kind.ProgressiveBitList);

    private static string? GenerateClassCode(SourceProductionContext context, SszType decl, List<SszType> foundTypes, Location? location)
    {
        try
        {
            List<SszProperty> variables = decl.Members.Where(m => m.IsVariable).ToList();
            int encodeOffsetIndex = 0, encodeStaticOffset = 0;
            int offsetIndex = 0, offset = 0;
            string containerMerkleizeBody = decl.Kind == Kind.ProgressiveContainer
                ? ProgressiveContainerMerkleizeBody(decl)
                : $@"Merkleizer merkleizer = new Merkleizer(Merkle.NextPowerOfTwoExponent({decl.Members!.Length}));
{Shift(2, decl.Members.Select(m => MerkleizeFeedStatement(m, $"container.{m.Name}")))}
        merkleizer.CalculateRoot(out root);";
            string result = FixWhitespace(decl.IsSszListItself ?
$@"using Nethermind.Merkleization;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using Nethermind.Serialization.Ssz;
using static Nethermind.Serialization.SszCodecHelpers;
{string.Join("\n", foundTypes.Select(x => x.Namespace).Distinct().OrderBy(x => x).Where(x => !string.IsNullOrEmpty(x) && x != "Nethermind.Serialization.Ssz").Select(n => $"using {n};"))}
{Whitespace}
using SszLib = Nethermind.Serialization.Ssz.Ssz;
{Whitespace}
{NamespaceLine(decl)}
{Whitespace}
{PartialTypeDeclaration(decl)}
{{
    public static int GetLength({decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return 0;
        }")}
{Whitespace}
        {ValidationStatement(decl, variables[0], $"container.{variables[0].Name}")}
        return {DynamicLength(decl, variables[0])};
    }}
{Whitespace}
    public static int GetLength(ReadOnlySpan<{decl.Name}> container)
    {{
        int length = container.Length * {SszType.PointerLength};
        foreach({decl.Name} item in container)
        {{
            length += GetLength(item);
        }}
{Whitespace}
        return length;
    }}
{Whitespace}
    public static byte[] Encode({decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return [];
        }")}
        byte[] buf = new byte[GetLength(container)];
        Encode(buf, container);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, {decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return;
        }")}
{Whitespace}
        {ValidationStatement(decl, variables[0], $"container.{variables[0].Name}")}
        {(RequiresNullGuard(variables[0]) ? $"if (container.{variables[0].Name} is not null) " : string.Empty)}{EncodeStatement("data", variables[0], $"container.{variables[0].Name}")}
    }}
{Whitespace}
    public static byte[] Encode(ReadOnlySpan<{decl.Name}> items)
    {{
        byte[] buf = new byte[GetLength(items)];
        Encode(buf, items);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, ReadOnlySpan<{decl.Name}> items)
    {{
{Whitespace}
        int offset = items.Length * {(SszType.PointerLength)};
        int itemOffset = 0;
{Whitespace}
        foreach({decl.Name} item in items)
        {{
            SszLib.Encode(data.Slice(itemOffset, {(SszType.PointerLength)}), offset);
            itemOffset += {(SszType.PointerLength)};
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.Name} container)
    {{
        container = new();
{Whitespace}
        {DecodeAndAssign(decl, variables[0], "data")}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.Name}[] container)
    {{
        if(data.Length is 0)
        {{
            container = [];
            return;
        }}
{Whitespace}
        {(decl.IsVariable ? $@"ValidateSszMinimumLength(data.Length, {SszType.PointerLength}, ""{decl.Name}[]"");
        SszLib.Decode(data.Slice(0, 4), out int firstOffset);
        int length = ValidateSszVariableItemCount(data, firstOffset, ""{decl.Name}[]"")" : $@"ValidateSszMultipleOf(data.Length, {decl.StaticLength}, ""{decl.Name}[]"");
        int length = data.Length / {decl.StaticLength}")};
        container = new {decl.Name}[length];
{Whitespace}
        {(decl.IsVariable ? @$"int index = 0;
        int offset = firstOffset;
        for(int nextOffsetIndex = {SszType.PointerLength}; index < length - 1; index++, nextOffsetIndex += {SszType.PointerLength})
        {{
            SszLib.Decode(data.Slice(nextOffsetIndex, {SszType.PointerLength}), out int nextOffset);
            ValidateSszNextOffset(data, offset, nextOffset, ""{decl.Name}[]"");
            Decode(data.Slice(offset, nextOffset - offset), out container[index]);
            offset = nextOffset;
        }}
{Whitespace}
        Decode(data.Slice(offset), out container[index]);" : @$"int offset = 0;
        for(int index = 0; index < length; index++)
        {{
            Decode(data.Slice(offset, {decl.StaticLength}), out container[index]);
            offset += {decl.StaticLength};
        }}")}
    }}
{Whitespace}
    public static void Merkleize({decl.Name}{(decl.IsStruct ? "" : "?")} container, out UInt256 root)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            root = 0;
            return;
        }")}
        {ValidationStatement(decl, variables[0], $"container.{variables[0].Name}")}
        {MerkleizeRootStatement(variables[0], $"container.{variables[0].Name}", "root")}
    }}
{Whitespace}
    public static void MerkleizeVector(ReadOnlySpan<{decl.Name}> container, out UInt256 root)
    {{
        UInt256[] subRoots = new UInt256[container.Length];
        for(int i = 0; i < container.Length; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.Merkleize(out root, subRoots);
    }}
{Whitespace}
    public static void MerkleizeList(ReadOnlySpan<{decl.Name}> container, ulong limit, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = new UInt256[count];
        for(int i = 0; i < count; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.Merkleize(out root, subRoots, limit);
        Merkle.MixIn(ref root, count);
    }}
{Whitespace}
    public static void MerkleizeProgressiveList(ReadOnlySpan<{decl.Name}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = new UInt256[count];
        for(int i = 0; i < count; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.MerkleizeProgressive(out root, subRoots);
        Merkle.MixIn(ref root, count);
    }}
}}
" :
(decl.Kind == Kind.Container || decl.Kind == Kind.ProgressiveContainer) ? $@"using Nethermind.Merkleization;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using Nethermind.Serialization.Ssz;
using static Nethermind.Serialization.SszCodecHelpers;
{string.Join("\n", foundTypes.Select(x => x.Namespace).Distinct().OrderBy(x => x).Where(x => !string.IsNullOrEmpty(x) && x != "Nethermind.Serialization.Ssz").Select(n => $"using {n};"))}
{Whitespace}
using SszLib = Nethermind.Serialization.Ssz.Ssz;
{Whitespace}
{NamespaceLine(decl)}
{Whitespace}
{PartialTypeDeclaration(decl)}
{{
    public static int GetLength({decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return 0;
        }")}
{Whitespace}
{Shift(2, ValidationStatements(decl, decl.Members!, "container"))}
{Whitespace}
        return {decl.StaticLength}{(variables.Any() ? "" : ";")}
{Shift(4, variables.Select(m => $"+ {DynamicLength(decl, m)}"), ";")}
    }}
{Whitespace}
    public static int GetLength(ReadOnlySpan<{decl.Name}> container)
    {{
        {(decl.IsVariable ? @$"int length = container.Length * {SszType.PointerLength};
        foreach({decl.Name} item in container)
        {{
            length += GetLength(item);
        }}
{Whitespace}
        return length;" : $"return container.Length * {(decl.StaticLength)};")}
    }}
{Whitespace}
    public static byte[] Encode({decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return [];
        }")}
        byte[] buf = new byte[GetLength(container)];
        Encode(buf, container);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, {decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return;
        }")}
{Whitespace}
{Shift(2, ValidationStatements(decl, decl.Members!, "container"))}
{Whitespace}
{Shift(2, variables.Select((_, i) => $"int offset{i + 1} = {(i == 0 ? decl.StaticLength : $"offset{i} + {DynamicLength(decl, variables[i - 1])}")};"))}
{Whitespace}
{Shift(2, decl.Members.Select(m =>
{
    if (m.IsVariable) encodeOffsetIndex++;
    string result = m.IsVariable ? $"SszLib.Encode(data.Slice({encodeStaticOffset}, 4), offset{encodeOffsetIndex});"
                                    : m.HandledByStd ? $"SszLib.Encode(data.Slice({encodeStaticOffset}, {m.StaticLength}), container.{m.Name});"
                                                     : $"{m.Type.Name}.Encode(data.Slice({encodeStaticOffset}, {m.StaticLength}), container.{m.Name});";
    encodeStaticOffset += m.StaticLength;
    return result;
}))}
{Whitespace}
{Shift(2, variables.Select((m, i) => (RequiresNullGuard(m) ? $"if (container.{m.Name} is not null) " : "") + EncodeStatement($"data.Slice(offset{i + 1}, {(i + 1 == variables.Count ? "data.Length" : $"offset{i + 2}")} - offset{i + 1})", m, $"container.{m.Name}")))}
    }}
{Whitespace}
    public static byte[] Encode(ReadOnlySpan<{decl.Name}> items)
    {{
        byte[] buf = new byte[GetLength(items)];
        Encode(buf, items);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, ReadOnlySpan<{decl.Name}> items)
    {{
{Whitespace}
        {(decl.IsVariable ? @$"int offset = items.Length * {(SszType.PointerLength)};
        int itemOffset = 0;
{Whitespace}
        foreach({decl.Name} item in items)
        {{
            SszLib.Encode(data.Slice(itemOffset, {(SszType.PointerLength)}), offset);
            itemOffset += {(SszType.PointerLength)};
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}" : @$"int offset = 0;
        foreach({decl.Name} item in items)
        {{
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}")}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.Name} container)
    {{
        {(decl.IsVariable ? $"ValidateSszMinimumLength(data.Length, {decl.StaticLength}, nameof({decl.Name}));" : $"ValidateSszExactLength(data.Length, {decl.StaticLength}, nameof({decl.Name}));")}
        container = new();
{Whitespace}
{Shift(2, decl.Members.Select(m =>
{
    if (m.IsVariable) offsetIndex++;
    string result = m.IsVariable ? $"SszLib.Decode(data.Slice({offset}, 4), out int offset{offsetIndex});"
                                    : DecodeAndAssign(decl, m, $"data.Slice({offset}, {m.StaticLength})");
    offset += m.StaticLength;
    return result;
}))}
{Whitespace}
        {(variables.Any() ? $"ValidateSszDynamicOffsets(data, {decl.StaticLength}, nameof({decl.Name}), [{string.Join(", ", Enumerable.Range(1, variables.Count).Select(i => $"offset{i}"))}]);" : string.Empty)}
{Whitespace}
{Shift(2, variables.Select((m, i) => DecodeAndAssign(decl, m, $"data.Slice(offset{i + 1}, {(i + 1 == variables.Count ? "data.Length" : $"offset{i + 2}")} - offset{i + 1})")))}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.Name}[] container)
    {{
        if(data.Length is 0)
        {{
            container = [];
            return;
        }}
{Whitespace}
        {(decl.IsVariable ? $@"ValidateSszMinimumLength(data.Length, {SszType.PointerLength}, ""{decl.Name}[]"");
        SszLib.Decode(data.Slice(0, 4), out int firstOffset);
        int length = ValidateSszVariableItemCount(data, firstOffset, ""{decl.Name}[]"")" : $@"ValidateSszMultipleOf(data.Length, {decl.StaticLength}, ""{decl.Name}[]"");
        int length = data.Length / {decl.StaticLength}")};
        container = new {decl.Name}[length];
{Whitespace}
        {(decl.IsVariable ? @$"int index = 0;
        int offset = firstOffset;
        for(int nextOffsetIndex = {SszType.PointerLength}; index < length - 1; index++, nextOffsetIndex += {SszType.PointerLength})
        {{
            SszLib.Decode(data.Slice(nextOffsetIndex, {SszType.PointerLength}), out int nextOffset);
            ValidateSszNextOffset(data, offset, nextOffset, ""{decl.Name}[]"");
            Decode(data.Slice(offset, nextOffset - offset), out container[index]);
            offset = nextOffset;
        }}
{Whitespace}
        Decode(data.Slice(offset), out container[index]);" : @$"int offset = 0;
        for(int index = 0; index < length; index++)
        {{
            Decode(data.Slice(offset, {decl.StaticLength}), out container[index]);
            offset += {decl.StaticLength};
        }}")}
    }}
{Whitespace}
    public static void Merkleize({decl.Name}{(decl.IsStruct ? "" : "?")} container, out UInt256 root)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            root = 0;
            return;
        }")}
{Shift(2, ValidationStatements(decl, decl.Members!, "container"))}
{Whitespace}
{Shift(2, containerMerkleizeBody.Split('\n'))}
    }}
{Whitespace}
    public static void MerkleizeVector(ReadOnlySpan<{decl.Name}> container, out UInt256 root)
    {{
        UInt256[] subRoots = new UInt256[container.Length];
        for(int i = 0; i < container.Length; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.Merkleize(out root, subRoots);
    }}
{Whitespace}
    public static void MerkleizeList(ReadOnlySpan<{decl.Name}> container, ulong limit, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = new UInt256[count];
        for(int i = 0; i < count; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.Merkleize(out root, subRoots, limit);
        Merkle.MixIn(ref root, count);
    }}
{Whitespace}
    public static void MerkleizeProgressiveList(ReadOnlySpan<{decl.Name}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = new UInt256[count];
        for(int i = 0; i < count; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.MerkleizeProgressive(out root, subRoots);
        Merkle.MixIn(ref root, count);
    }}
}}
" :
// Compatible unions
$@"using Nethermind.Merkleization;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using Nethermind.Serialization.Ssz;
using static Nethermind.Serialization.SszCodecHelpers;
{string.Join("\n", foundTypes.Select(x => x.Namespace).Distinct().OrderBy(x => x).Where(x => !string.IsNullOrEmpty(x) && x != "Nethermind.Serialization.Ssz").Select(n => $"using {n};"))}
{Whitespace}
using SszLib = Nethermind.Serialization.Ssz.Ssz;
{Whitespace}
{NamespaceLine(decl)}
{Whitespace}
{PartialTypeDeclaration(decl)}
{{
    public static int GetLength({decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return 0;
        }")}
        switch(container.Selector)
        {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m =>
{
    string validation = ValidationStatement(decl, m, $"container.{m.Name}");
    string length = m.IsVariable ? DynamicLength(decl, m) : m.StaticLength.ToString();
    return string.IsNullOrEmpty(validation)
        ? $"case {decl.Selector!.Type.Name}.{m.Name}: return 1 + {length};"
        : $"case {decl.Selector!.Type.Name}.{m.Name}: {validation} return 1 + {length};";
}))}
            default:
                return ThrowInvalidSszData<int>(nameof({decl.Name}), $""unsupported union selector {{(byte)container.Selector}}."");
        }}
    }}
{Whitespace}
    public static int GetLength(ReadOnlySpan<{decl.Name}> container)
    {{
        int length = container.Length * {SszType.PointerLength};
        foreach({decl.Name} item in container)
        {{
            length += GetLength(item);
        }}
{Whitespace}
        return length;
    }}
{Whitespace}
    public static byte[] Encode({decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return [];
        }")}
        byte[] buf = new byte[GetLength(container)];
        Encode(buf, container);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, {decl.Name}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return;
        }")}
        ValidateSszExactLength(data.Length, GetLength(container), nameof({decl.Name}));
        SszLib.Encode(data.Slice(0, 1), (byte)container.Selector);
{Whitespace}
        switch(container.Selector) {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m => $"case {decl.Selector!.Type.Name}.{m.Name}: {EncodeStatement("data.Slice(1)", m, $"container.{m.Name}")} break;"))}
            default:
                ThrowInvalidSszData(nameof({decl.Name}), $""unsupported union selector {{(byte)container.Selector}}."");
                break;
        }};
    }}
{Whitespace}
    public static byte[] Encode(ReadOnlySpan<{decl.Name}> items)
    {{
        byte[] buf = new byte[GetLength(items)];
        Encode(buf, items);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, ReadOnlySpan<{decl.Name}> items)
    {{
        int offset = items.Length * {(SszType.PointerLength)};
        int itemOffset = 0;
        foreach({decl.Name} item in items)
        {{
            SszLib.Encode(data.Slice(itemOffset, {(SszType.PointerLength)}), offset);
            itemOffset += {(SszType.PointerLength)};
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.Name}[] container)
    {{
        if(data.Length is 0)
        {{
            container = [];
            return;
        }}
{Whitespace}
        ValidateSszMinimumLength(data.Length, {SszType.PointerLength}, ""{decl.Name}[]"");
        SszLib.Decode(data.Slice(0, 4), out int firstOffset);
        int length = ValidateSszVariableItemCount(data, firstOffset, ""{decl.Name}[]"");
        container = new {decl.Name}[length];
{Whitespace}
        int index = 0;
        int offset = firstOffset;
        for(int nextOffsetIndex = {SszType.PointerLength}; index < length - 1; index++, nextOffsetIndex += {SszType.PointerLength})
        {{
            SszLib.Decode(data.Slice(nextOffsetIndex, {SszType.PointerLength}), out int nextOffset);
            ValidateSszNextOffset(data, offset, nextOffset, ""{decl.Name}[]"");
            Decode(data.Slice(offset, nextOffset - offset), out container[index]);
            offset = nextOffset;
        }}
{Whitespace}
        Decode(data.Slice(offset), out container[index]);
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.Name} container)
    {{
        container = new();
        ValidateSszMinimumLength(data.Length, 1, nameof({decl.Name}));
        container.Selector = ({decl.Selector!.Type.Name})data[0];
        switch(container.Selector) {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m => $"case {decl.Selector!.Type.Name}.{m.Name}: {DecodeAndAssign(decl, m, "data.Slice(1)")} break;"))}
            default:
                ThrowInvalidSszData(nameof({decl.Name}), $""unsupported union selector {{data[0]}}."");
                break;
        }};
        ValidateSszExactLength(data.Length, GetLength(container), nameof({decl.Name}));
    }}
{Whitespace}
    public static void Merkleize({decl.Name}{(decl.IsStruct ? "" : "?")} container, out UInt256 root)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            root = 0;
            return;
        }")}
        switch(container.Selector) {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m =>
{
    string validation = ValidationStatement(decl, m, $"container.{m.Name}");
    string merkleize = MerkleizeRootStatement(m, $"container.{m.Name}", "root");
    return string.IsNullOrEmpty(validation)
        ? $"case {decl.Selector!.Type.Name}.{m.Name}: {merkleize} break;"
        : $"case {decl.Selector!.Type.Name}.{m.Name}: {validation} {merkleize} break;";
}))}
            default:
                root = ThrowInvalidSszData<UInt256>(nameof({decl.Name}), $""unsupported union selector {{(byte)container.Selector}}."");
                break;
        }};
        Merkle.MixIn(ref root, (byte)container.Selector);
    }}
{Whitespace}
    public static void MerkleizeVector(ReadOnlySpan<{decl.Name}> container, out UInt256 root)
    {{
        UInt256[] subRoots = new UInt256[container.Length];
        for(int i = 0; i < container.Length; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.Merkleize(out root, subRoots);
    }}
{Whitespace}
    public static void MerkleizeList(ReadOnlySpan<{decl.Name}> container, ulong limit, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = new UInt256[count];
        for(int i = 0; i < count; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.Merkleize(out root, subRoots, limit);
        Merkle.MixIn(ref root, count);
    }}
{Whitespace}
    public static void MerkleizeProgressiveList(ReadOnlySpan<{decl.Name}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = new UInt256[count];
        for(int i = 0; i < count; i++)
        {{
            Merkleize(container[i], out subRoots[i]);
        }}
{Whitespace}
        Merkle.MerkleizeProgressive(out root, subRoots);
        Merkle.MixIn(ref root, count);
    }}
}}
");
#if DEBUG
#pragma warning disable RS1035 // Allow console for debugging
            Console.WriteLine(WithLineNumbers(result, false));
#pragma warning restore RS1035
#endif
            return GeneratedSourceHeader + result;
        }
        catch (Exception e)
        {
            context.ReportDiagnostic(Diagnostic.Create(GenerationFailureRule, location ?? Location.None, decl.Name, e.Message));
            return null;
        }
    }

#if DEBUG
    static string WithLineNumbers(string input, bool bypass = false)
    {
        if (bypass) return input;

        string[] lines = input.Split('\n');
        int lineNumberWidth = lines.Length.ToString().Length;

        StringBuilder sb = new();
        for (int i = 0; i < lines.Length; i++)
        {
            string lineNumber = (i + 1).ToString().PadLeft(lineNumberWidth);
            sb.AppendLine($"{lineNumber}: {lines[i]}");
        }

        return sb.ToString();
    }
#endif
}
