using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Nethermind.Serialization.Ssz;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;

[Generator]
public class SszGenerator : IIncrementalGenerator
{
    private const string GeneratedSourceHeader = "// <auto-generated/>\n#nullable enable\n";

    private static readonly ConditionalWeakTable<Compilation, Lazy<SszTypeConverterInfo[]>> ConverterCache = new();

    private sealed class SszDeclaration
    {
        public required string TypeName { get; init; }
        public SszType? Type { get; init; }
        public Location? Location { get; init; }
        public bool IsNested { get; init; }
        public string? ErrorMessage { get; init; }
    }

    private static readonly DiagnosticDescriptor GenerationFailureRule = new(
        "SSZ003",
        "SSZ source generation failed",
        "Failed to generate SSZ code for '{0}': {1}",
        "SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NestedTypeNotSupportedRule = new(
        "SSZ004",
        "SSZ types must be top-level",
        "SSZ container '{0}' is nested inside another type and is not supported by the source generator",
        "SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static spc =>
            spc.AddSource("Serialization.SszCodec.Helpers.cs", SourceText.From(GenerateHelpersCode(), Encoding.UTF8)));

        IncrementalValuesProvider<SszDeclaration?> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => IsClassWithAttribute(syntaxNode),
                transform: (context, _) => GetClassWithAttribute(context))
            .Where(classNode => classNode is not null);

        context.RegisterSourceOutput(classDeclarations, (spc, decl) =>
        {
            if (decl is null)
            {
                return;
            }

            if (decl.ErrorMessage is not null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(GenerationFailureRule, decl.Location ?? Location.None, decl.TypeName, decl.ErrorMessage));
                return;
            }

            if (decl.Type is null)
            {
                return;
            }

            if (decl.IsNested)
            {
                spc.ReportDiagnostic(Diagnostic.Create(NestedTypeNotSupportedRule, decl.Location ?? Location.None, decl.Type.Name));
                return;
            }

            string? generatedCode = GenerateClassCode(spc, decl.Type, decl.Location);
            if (generatedCode is not null)
            {
                spc.AddSource($"Serialization.SszCodec.{decl.Type.HintName}.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
        });
    }

    private static string PartialTypeDeclaration(SszType decl) =>
        $"partial {(decl.IsStruct ? "struct" : "class")} {decl.TypeReferenceName} : ISszCodec<{decl.TypeReferenceName}>"
        + (string.IsNullOrEmpty(decl.TypeParameterConstraints) ? string.Empty : $" {decl.TypeParameterConstraints}");

    private static string NamespaceLine(SszType decl) =>
        string.IsNullOrEmpty(decl.Namespace) ? string.Empty : $"namespace {decl.Namespace};";

    private static bool IsClassWithAttribute(SyntaxNode syntaxNode) =>
        syntaxNode is TypeDeclarationSyntax classDeclaration &&
        classDeclaration.AttributeLists.Any(x => x.Attributes.Any());

    private static SszDeclaration? GetClassWithAttribute(GeneratorSyntaxContext context)
    {
        TypeDeclarationSyntax classDeclaration = (TypeDeclarationSyntax)context.Node;
        foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
        {
            foreach (AttributeSyntax attribute in attributeList.Attributes)
            {
                IMethodSymbol? methodSymbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
                if (methodSymbol is not null && IsSszRootAttribute(methodSymbol.ContainingType))
                {
                    INamedTypeSymbol typeSymbol = (INamedTypeSymbol)context.SemanticModel.GetDeclaredSymbol(classDeclaration)!;
                    Location location = classDeclaration.Identifier.GetLocation();
                    try
                    {
                        List<SszType> foundTypes = SszType.CreateKnownTypes(FindConverters(context.SemanticModel.Compilation));
                        SszType sszType = SszType.From(context.SemanticModel, foundTypes, typeSymbol);
                        // Carry the `where T : ...` clauses verbatim from syntax — the symbol-side API
                        // would require us to reassemble each constraint, and the textual form already matches.
                        sszType.TypeParameterConstraints = string.Join(" ", classDeclaration.ConstraintClauses.Select(c => c.ToString()));
                        foreach (ITypeParameterSymbol tp in typeSymbol.TypeParameters)
                        {
                            foreach (ITypeSymbol ct in tp.ConstraintTypes)
                            {
                                string? ns = ct.ContainingNamespace?.ToString();
                                if (!string.IsNullOrEmpty(ns))
                                    sszType.TypeParameterConstraintNamespaces.Add(ns!);
                            }
                        }

                        return new()
                        {
                            TypeName = sszType.Name,
                            Type = sszType,
                            Location = location,
                            IsNested = typeSymbol.ContainingType is not null,
                        };
                    }
                    catch (Exception e)
                    {
                        return new()
                        {
                            TypeName = typeSymbol.Name,
                            Location = location,
                            IsNested = typeSymbol.ContainingType is not null,
                            ErrorMessage = e.Message,
                        };
                    }
                }
            }
        }
        return null;
    }

    private static IEnumerable<SszTypeConverterInfo> FindConverters(Compilation compilation) =>
        ConverterCache.GetValue(
            compilation,
            static currentCompilation => new Lazy<SszTypeConverterInfo[]>(() => SszTypeConverterInfo.Find(currentCompilation).ToArray()))
            .Value;

    private static bool IsSszRootAttribute(INamedTypeSymbol attributeType) =>
        attributeType.Name is nameof(SszContainerAttribute) or nameof(SszCompatibleUnionAttribute);

    const string Whitespace = "/**/";
    private const int UnboundedBitlistLimit = 0;
    static readonly Regex OpeningWhiteSpaceRegex = new("{/(\\n\\s+)+\\n/");
    static readonly Regex ClosingWhiteSpaceRegex = new("/(\\s+\\n)+    }/");
    public static string FixWhitespace(string data) => OpeningWhiteSpaceRegex.Replace(
                                                        ClosingWhiteSpaceRegex.Replace(
                                                            string.Join("\n", data.Split('\n').Where(x => !string.IsNullOrWhiteSpace(x)).Select(x => x.Contains(Whitespace) ? "" : x)),
                                                            "    }"),
                                                        "{\n"
        );
    public static string Shift(int tabCount, string data) => string.Empty.PadLeft(4 * tabCount) + data;
    public static string Shift(int tabCount, IEnumerable<string> data, string? end = null) => string.Join("\n", data.Select(d => Shift(tabCount, d))) + (end is null || !data.Any() ? "" : end);

    private static string GenerateHelpersCode() =>
"""
// <auto-generated/>
#nullable enable
using Nethermind.Int256;
using Nethermind.Serialization.Ssz.Merkleization;
using System;
using System.Buffers.Binary;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Nethermind.Serialization;

internal static class SszCodecHelpers
{
    private const int SszOffsetSize = 4;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static void EncodeSszOffset(Span<byte> data, int offset) =>
        BinaryPrimitives.WriteInt32LittleEndian(data, offset);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static int DecodeSszOffset(ReadOnlySpan<byte> data) =>
        BinaryPrimitives.ReadInt32LittleEndian(data);

    internal static T ThrowInvalidSszData<T>(string typeName, string message) =>
        throw new InvalidDataException($"Invalid SSZ data for {typeName}: {message}");

    internal static void ThrowInvalidSszData(string typeName, string message) =>
        throw new InvalidDataException($"Invalid SSZ data for {typeName}: {message}");

    internal static void ThrowInvalidSszValue(string typeName, string fieldName, string message) =>
        throw new InvalidDataException($"Invalid SSZ value for {typeName}.{fieldName}: {message}");

    internal static void ValidateSszExactLength(int actualLength, int expectedLength, string typeName)
    {
        if (actualLength != expectedLength)
        {
            ThrowInvalidSszData(typeName, $"expected {expectedLength} bytes but found {actualLength}.");
        }
    }

    internal static void ValidateSszMinimumLength(int actualLength, int minimumLength, string typeName)
    {
        if (actualLength < minimumLength)
        {
            ThrowInvalidSszData(typeName, $"expected at least {minimumLength} bytes but found {actualLength}.");
        }
    }

    internal static void ValidateSszMultipleOf(int actualLength, int itemLength, string typeName)
    {
        if (actualLength % itemLength != 0)
        {
            ThrowInvalidSszData(typeName, $"expected a multiple of {itemLength} bytes but found {actualLength}.");
        }
    }

    internal static void ValidateSszDynamicOffsets(ReadOnlySpan<byte> data, int fixedLength, string typeName, ReadOnlySpan<int> offsets)
    {
        ValidateSszMinimumLength(data.Length, fixedLength, typeName);

        if (offsets.Length is 0)
        {
            return;
        }

        if (offsets[0] != fixedLength)
        {
            ThrowInvalidSszData(typeName, $"expected the first offset to be {fixedLength} but found {offsets[0]}.");
        }

        int previous = fixedLength;
        for (int index = 0; index < offsets.Length; index++)
        {
            int current = offsets[index];
            if (current < previous)
            {
                ThrowInvalidSszData(typeName, $"offset #{index} is out of order ({current} < {previous}).");
            }

            if (current > data.Length)
            {
                ThrowInvalidSszData(typeName, $"offset #{index} ({current}) exceeds the input length {data.Length}.");
            }

            previous = current;
        }
    }

    internal static int ValidateSszVariableItemCount(ReadOnlySpan<byte> data, int firstOffset, string typeName)
    {
        ValidateSszMinimumLength(data.Length, SszOffsetSize, typeName);

        if (firstOffset < SszOffsetSize)
        {
            ThrowInvalidSszData(typeName, $"expected the first offset to be at least {SszOffsetSize} but found {firstOffset}.");
        }

        if (firstOffset > data.Length)
        {
            ThrowInvalidSszData(typeName, $"the first offset {firstOffset} exceeds the input length {data.Length}.");
        }

        if (firstOffset % SszOffsetSize != 0)
        {
            ThrowInvalidSszData(typeName, $"the first offset {firstOffset} is not aligned to {SszOffsetSize}-byte offsets.");
        }

        return firstOffset / SszOffsetSize;
    }

    internal static void ValidateSszNextOffset(ReadOnlySpan<byte> data, int currentOffset, int nextOffset, string typeName)
    {
        if (nextOffset < currentOffset)
        {
            ThrowInvalidSszData(typeName, $"offsets are out of order ({nextOffset} < {currentOffset}).");
        }

        if (nextOffset > data.Length)
        {
            ThrowInvalidSszData(typeName, $"offset {nextOffset} exceeds the input length {data.Length}.");
        }
    }

    internal static void ValidateSszVectorLength<T>(ReadOnlySpan<T> items, int expectedLength, string typeName, string fieldName)
    {
        if (items.Length != expectedLength)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected {expectedLength} elements but found {items.Length}.");
        }
    }

    internal static void ValidateSszListLimit<T>(ReadOnlySpan<T> items, ulong limit, string typeName, string fieldName)
    {
        if ((ulong)items.Length > limit)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected at most {limit} elements but found {items.Length}.");
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static byte[] DecodeSszByteList(ReadOnlySpan<byte> data, ulong limit, string typeName, string fieldName)
    {
        ValidateSszListLimit(data, limit, typeName, fieldName);
        byte[] result = global::System.GC.AllocateUninitializedArray<byte>(data.Length);
        data.CopyTo(result);
        return result;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static byte[] DecodeSszByteVector(ReadOnlySpan<byte> data, int expectedLength, string typeName, string fieldName)
    {
        if (data.Length != expectedLength)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected {expectedLength} elements but found {data.Length}.");
        }

        byte[] result = global::System.GC.AllocateUninitializedArray<byte>(expectedLength);
        data.CopyTo(result);
        return result;
    }

    internal static void ValidateSszBitvectorLength(BitArray? bits, int expectedLength, string typeName, string fieldName)
    {
        int actualLength = bits?.Length ?? 0;
        if (bits is null || actualLength != expectedLength)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected {expectedLength} bits but found {actualLength}.");
        }
    }

    internal static void ValidateSszBitlistLimit(BitArray? bits, ulong limit, string typeName, string fieldName)
    {
        if (bits is not null && (ulong)bits.Length > limit)
        {
            ThrowInvalidSszValue(typeName, fieldName, $"expected at most {limit} bits but found {bits.Length}.");
        }
    }

    internal static void DecodeSszBitVector(ReadOnlySpan<byte> data, int vectorLength, out BitArray value)
    {
        ValidateSszExactLength(data.Length, (vectorLength + 7) / 8, $"bitvector[{vectorLength}]");
        value = Nethermind.Serialization.Ssz.Ssz.DecodeBitvector(data, vectorLength);
    }

    internal static void DecodeSszBitList(ReadOnlySpan<byte> data, string typeName, out BitArray value)
    {
        ValidateSszMinimumLength(data.Length, 1, typeName);
        value = Nethermind.Serialization.Ssz.Ssz.DecodeBitlist(data);
    }

    internal static void MerkleizeBasicVector<T>(ReadOnlySpan<T> values, int itemSize, ulong length, out UInt256 root)
        where T : struct
    {
        ulong chunkCount = (length * (ulong)itemSize + 31UL) / 32UL;
        Merkle.Merkleize(out root, MemoryMarshal.AsBytes(values), chunkCount);
    }

    internal static void MerkleizeBasicList<T>(ReadOnlySpan<T> values, int itemSize, ulong limit, out UInt256 root)
        where T : struct
    {
        ulong chunkCount = (limit * (ulong)itemSize + 31UL) / 32UL;
        Merkle.Merkleize(out root, MemoryMarshal.AsBytes(values), chunkCount);
        Merkle.MixIn(ref root, values.Length);
    }

    private static void MerkleizeProgressiveBytes(ReadOnlySpan<byte> value, out UInt256 root)
    {
        if (value.Length is 0)
        {
            root = UInt256.Zero;
            return;
        }

        int chunkCount = (value.Length + 31) / 32;
        // Stack-alloc up to 4 chunks (128 bytes); rent for larger payloads.
        const int StackChunkLimit = 4;
        scoped Span<UInt256> chunks;
        UInt256[]? rented = null;
        if (chunkCount <= StackChunkLimit)
        {
            Span<UInt256> stack = stackalloc UInt256[StackChunkLimit];
            chunks = stack[..chunkCount];
        }
        else
        {
            rented = System.Buffers.ArrayPool<UInt256>.Shared.Rent(chunkCount);
            chunks = rented.AsSpan(0, chunkCount);
        }
        try
        {
            // Clearing the in-use prefix is sufficient; MerkleizeProgressive only reads it.
            chunks.Clear();
            int fullByteLength = value.Length / 32 * 32;
            if (fullByteLength > 0)
            {
                MemoryMarshal.Cast<byte, UInt256>(value[..fullByteLength]).CopyTo(chunks);
            }

            if (fullByteLength != value.Length)
            {
                Span<byte> lastChunk = stackalloc byte[32];
                lastChunk.Clear();
                value[fullByteLength..].CopyTo(lastChunk);
                chunks[chunkCount - 1] = new UInt256(lastChunk);
            }

            Merkle.MerkleizeProgressive(out root, chunks);
        }
        finally
        {
            if (rented is not null) System.Buffers.ArrayPool<UInt256>.Shared.Return(rented);
        }
    }

    internal static void MerkleizeProgressiveBasicList<T>(ReadOnlySpan<T> values, out UInt256 root)
        where T : struct
    {
        MerkleizeProgressiveBytes(MemoryMarshal.AsBytes(values), out root);
        Merkle.MixIn(ref root, values.Length);
    }

    internal delegate void EncodeItems<T>(Span<byte> span, ReadOnlySpan<T> items);
    internal delegate T DecodeItem<T>(ReadOnlySpan<byte> span);

    private static void MerkleizeBasicCollectionWithConverter<T>(
        ReadOnlySpan<T> values, int itemSize, ulong chunkCount, EncodeItems<T> encode, out UInt256 root)
    {
        const int StackByteLimit = 256;
        int byteLength = checked(values.Length * itemSize);
        scoped Span<byte> bytes;
        byte[]? rented = null;
        if (byteLength <= StackByteLimit)
        {
            Span<byte> stack = stackalloc byte[StackByteLimit];
            bytes = stack[..byteLength];
        }
        else
        {
            rented = System.Buffers.ArrayPool<byte>.Shared.Rent(byteLength);
            bytes = rented.AsSpan(0, byteLength);
        }
        try
        {
            Debug.Assert(bytes.Length == byteLength, "SSZ collection buffer length must match item count and item size.");
            encode(bytes, values);
            Merkle.Merkleize(out root, bytes, chunkCount);
        }
        finally
        {
            if (rented is not null) System.Buffers.ArrayPool<byte>.Shared.Return(rented);
        }
    }

    internal static void MerkleizeBasicVectorWithConverter<T>(
        ReadOnlySpan<T> values, int itemSize, ulong length, EncodeItems<T> encode, out UInt256 root)
    {
        ulong chunkCount = (length * (ulong)itemSize + 31UL) / 32UL;
        MerkleizeBasicCollectionWithConverter(values, itemSize, chunkCount, encode, out root);
    }

    internal static void MerkleizeBasicListWithConverter<T>(
        ReadOnlySpan<T> values, int itemSize, ulong limit, EncodeItems<T> encode, out UInt256 root)
    {
        ulong chunkCount = (limit * (ulong)itemSize + 31UL) / 32UL;
        MerkleizeBasicCollectionWithConverter(values, itemSize, chunkCount, encode, out root);
        Merkle.MixIn(ref root, values.Length);
    }

    internal static void MerkleizeProgressiveBasicListWithConverter<T>(
        ReadOnlySpan<T> values, int itemSize, EncodeItems<T> encode, out UInt256 root)
    {
        const int StackByteLimit = 256;
        int byteLength = checked(values.Length * itemSize);
        scoped Span<byte> bytes;
        byte[]? rented = null;
        if (byteLength <= StackByteLimit)
        {
            Span<byte> stack = stackalloc byte[StackByteLimit];
            bytes = stack[..byteLength];
        }
        else
        {
            rented = System.Buffers.ArrayPool<byte>.Shared.Rent(byteLength);
            bytes = rented.AsSpan(0, byteLength);
        }
        try
        {
            Debug.Assert(bytes.Length == byteLength, "SSZ collection buffer length must match item count and item size.");
            encode(bytes, values);
            MerkleizeProgressiveBytes(bytes, out root);
        }
        finally
        {
            if (rented is not null) System.Buffers.ArrayPool<byte>.Shared.Return(rented);
        }
        Merkle.MixIn(ref root, values.Length);
    }

    internal static void MerkleizeProgressiveBitList(BitArray? value, out UInt256 root)
    {
        BitArray bits = value ?? new BitArray(0);
        int byteLength = (bits.Length + 7) / 8;
        // BitArray.CopyTo requires a byte[] target, so we rent regardless of size;
        // the small-chunkCount fast path in MerkleizeProgressiveBytes covers stackalloc.
        byte[] bytes = System.Buffers.ArrayPool<byte>.Shared.Rent(byteLength);
        try
        {
            Array.Clear(bytes, 0, byteLength);
            bits.CopyTo(bytes, 0);
            MerkleizeProgressiveBytes(bytes.AsSpan(0, byteLength), out root);
        }
        finally
        {
            System.Buffers.ArrayPool<byte>.Shared.Return(bytes);
        }
        Merkle.MixIn(ref root, bits.Length);
    }

    internal delegate void FeedItem<T>(ref Merkleizer merkleizer, T item);

    internal enum ConverterCollectionMerkleKind { Vector, List, ProgressiveList }

    private static void MerkleizeCompositeCollectionWithConverter<T>(
        ReadOnlySpan<T> items, FeedItem<T> feed,
        ConverterCollectionMerkleKind kind, ulong limit, out UInt256 root)
    {
        int count = items.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {
            for (int i = 0; i < count; i++)
            {
                MerkleizeWithConverter(items[i], feed, out subRoots[i]);
            }
            ReadOnlySpan<UInt256> active = subRoots.AsSpan(0, count);
            switch (kind)
            {
                case ConverterCollectionMerkleKind.Vector: Merkle.Merkleize(out root, active); break;
                case ConverterCollectionMerkleKind.List: Merkle.Merkleize(out root, active, limit); break;
                default: Merkle.MerkleizeProgressive(out root, active); break;
            }
        }
        finally
        {
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }
        if (kind != ConverterCollectionMerkleKind.Vector) Merkle.MixIn(ref root, count);
    }

    internal static void MerkleizeCompositeVectorWithConverter<T>(ReadOnlySpan<T> items, ulong length, FeedItem<T> feed, out UInt256 root)
    {
        Debug.Assert((ulong)items.Length == length, "Vector items count must equal declared length");
        MerkleizeCompositeCollectionWithConverter(items, feed, ConverterCollectionMerkleKind.Vector, limit: 0, out root);
    }

    internal static void MerkleizeDefaultWithConverter<T>(int itemSize, DecodeItem<T> decode, FeedItem<T> feed, out UInt256 root)
    {
        const int StackByteLimit = 256;
        scoped Span<byte> bytes;
        byte[]? rented = null;
        if (itemSize <= StackByteLimit)
        {
            Span<byte> stack = stackalloc byte[StackByteLimit];
            bytes = stack[..itemSize];
        }
        else
        {
            rented = System.Buffers.ArrayPool<byte>.Shared.Rent(itemSize);
            bytes = rented.AsSpan(0, itemSize);
        }
        try
        {
            bytes.Clear();
            MerkleizeWithConverter(decode(bytes), feed, out root);
        }
        finally
        {
            if (rented is not null) System.Buffers.ArrayPool<byte>.Shared.Return(rented);
        }
    }

    internal static void MerkleizeDefaultCompositeVectorWithConverter<T>(int itemSize, ulong length, DecodeItem<T> decode, FeedItem<T> feed, out UInt256 root)
    {
        if (length == 0)
        {
            root = UInt256.Zero;
            return;
        }

        MerkleizeDefaultWithConverter(itemSize, decode, feed, out UInt256 itemRoot);
        Merkleizer merkleizer = new(Merkle.NextPowerOfTwoExponent(length));
        for (ulong i = 0; i < length; i++)
        {
            merkleizer.Feed(itemRoot);
        }

        merkleizer.CalculateRoot(out root);
    }

    internal static void MerkleizeCompositeListWithConverter<T>(ReadOnlySpan<T> items, ulong limit, FeedItem<T> feed, out UInt256 root)
        => MerkleizeCompositeCollectionWithConverter(items, feed, ConverterCollectionMerkleKind.List, limit, out root);

    internal static void MerkleizeCompositeProgressiveListWithConverter<T>(ReadOnlySpan<T> items, FeedItem<T> feed, out UInt256 root)
        => MerkleizeCompositeCollectionWithConverter(items, feed, ConverterCollectionMerkleKind.ProgressiveList, limit: 0, out root);

    internal static void MerkleizeWithConverter<T>(T value, FeedItem<T> feed, out UInt256 root)
    {
        Span<UInt256> chunk = stackalloc UInt256[1];
        Merkleizer merkleizer = new(chunk);
        feed(ref merkleizer, value);
        root = chunk[0];
    }
}
""";

    private static string VarName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;

        string lowerCased = name.Substring(0, 1).ToLower() + name.Substring(1);

        return lowerCased == "data" || lowerCased == "container" || lowerCased.Contains("offset") ? $"_{lowerCased}" : lowerCased;
    }

    /// <summary>
    /// Emits a `Decode(ReadOnlySequence&lt;byte&gt;, out T)` overload that lets the SSZ-REST
    /// middleware feed a <c>PipeReader</c>'s buffer directly. Single-segment input is
    /// zero-copy; multi-segment consolidates into one pooled buffer before dispatching to
    /// the existing span decoder. (Recursive sequence-aware decode would touch every leaf
    /// primitive — deferred until the bulk-copy shows up as a real cost.)
    /// </summary>
    private static string SequenceDecodeMethod(string typeName) => $@"public static void Decode(System.Buffers.ReadOnlySequence<byte> data, out {typeName} container)
    {{
        if (data.IsSingleSegment)
        {{
            Decode(data.FirstSpan, out container);
            return;
        }}
        int len = (int)data.Length;
        byte[] rented = System.Buffers.ArrayPool<byte>.Shared.Rent(len);
        try
        {{
            System.Buffers.BuffersExtensions.CopyTo(data, rented.AsSpan(0, len));
            Decode(rented.AsSpan(0, len), out container);
        }}
        finally
        {{
            System.Buffers.ArrayPool<byte>.Shared.Return(rented);
        }}
    }}";

    private static string ValidationStatement(SszType decl, SszProperty property, string expression)
    {
        string validation = property.Kind switch
        {
            Kind.Vector when property.Type.Name == "BitArray" => $"ValidateSszBitvectorLength({expression}, {property.Length}, nameof({decl.TypeReferenceName}), nameof({property.Name}));",
            Kind.Vector => $"ValidateSszVectorLength({SpanExpression(property, expression)}, {property.Length}, nameof({decl.TypeReferenceName}), nameof({property.Name}));",
            Kind.List => $"ValidateSszListLimit({SpanExpression(property, expression)}, {property.Limit}UL, nameof({decl.TypeReferenceName}), nameof({property.Name}));",
            Kind.BitVector => $"ValidateSszBitvectorLength({expression}, {property.Length}, nameof({decl.TypeReferenceName}), nameof({property.Name}));",
            Kind.BitList => $"ValidateSszBitlistLimit({expression}, {property.Limit}UL, nameof({decl.TypeReferenceName}), nameof({property.Name}));",
            _ => string.Empty,
        };

        if (!property.IsNullable)
        {
            return validation;
        }

        bool canEncodeNullAsDefault = CanEncodeNullAsDefault(property);

        if (!string.IsNullOrEmpty(validation) && canEncodeNullAsDefault)
        {
            return $"if ({expression} is not null) {validation}";
        }

        if (property.Kind == Kind.Vector)
        {
            return $"if ({expression} is null) throw new System.IO.InvalidDataException(\"Invalid SSZ value for {decl.TypeReferenceName}.{property.Name}: expected {property.Length} elements but found 0.\"); {validation}";
        }

        if (property.IsVariable && !canEncodeNullAsDefault)
        {
            return $"if ({expression} is null) throw new System.IO.InvalidDataException(\"Invalid SSZ value for {decl.TypeReferenceName}.{property.Name}: null variable fields are not decodable.\"); {validation}";
        }

        return validation;
    }

    private static bool CanEncodeNullAsDefault(SszProperty property) =>
        property.Kind switch
        {
            Kind.Vector => property.Type.Kind == Kind.Basic || property.Type.Name == "BitArray",
            Kind.BitVector or Kind.List or Kind.ProgressiveList or Kind.BitList or Kind.ProgressiveBitList => true,
            Kind.Basic when property.Type.HasCustomInlineCodec => true,
            _ => false,
        };

    private static string EncodeValueExpression(SszProperty property, string expression) =>
        property.Kind switch
        {
            Kind.BitList or Kind.ProgressiveBitList => $"{expression} ?? new BitArray(0)",
            _ when property.IsCollection && property.Type.Name != "BitArray" => SpanExpression(property, expression),
            _ => expression,
        };

    private static string EnumSpanExpression(SszProperty property, string expression) =>
        $"System.Runtime.InteropServices.MemoryMarshal.Cast<{property.Type.TypeReferenceName}, {property.Type.EnumType!.TypeReferenceName}>({SpanExpression(property, expression)})";

    private static string SpanExpression(SszProperty property, string expression) =>
        property.IsSpanLikeProperty ? expression
            : property.IsMemoryLikeProperty ? $"{expression}.Span"
            : property.IsArrayProperty ? $"{expression}.AsSpan()"
            : property.HasCollectionAsSpan ? $"{expression}.AsSpan()"
            : $"System.Runtime.InteropServices.CollectionsMarshal.AsSpan({expression})";

    private static IEnumerable<string> ValidationStatements(SszType decl, IEnumerable<SszProperty> properties, string expressionPrefix)
    {
        foreach (SszProperty property in properties)
        {
            string validation = ValidationStatement(decl, property, $"{expressionPrefix}.{property.Name}");
            if (!string.IsNullOrEmpty(validation))
            {
                yield return validation;
            }
        }
    }

    private static string StaticFieldEncodeStatement(SszProperty property, int staticOffset, string containerExpr)
    {
        string destSpan = $"data.Slice({staticOffset}, {property.StaticLength})";
        string valueExpr = $"{containerExpr}.{property.Name}";
        string encodedValueExpr = EncodeValueExpression(property, valueExpr);

        string statement;
        if (property.Kind != Kind.Basic)
        {
            statement = EncodeStatement(destSpan, property, valueExpr);
        }
        else if (property.Type.EnumType is { HasCustomInlineCodec: true } enumType)
        {
            statement = enumType.CustomEncodeTemplate!
                .Replace("{0}", destSpan)
                .Replace("{1}", $"({enumType.TypeReferenceName}){encodedValueExpr}");
        }
        else if (property.Type.HasCustomInlineCodec)
        {
            statement = property.Type.CustomEncodeTemplate!
                .Replace("{0}", destSpan)
                .Replace("{1}", encodedValueExpr);
        }
        else
        {
            statement = property.HandledByStd
                ? $"Nethermind.Serialization.Ssz.Ssz.Encode({destSpan}, {encodedValueExpr});"
                : $"{property.Type.StaticMemberAccess}.Encode({destSpan}, {encodedValueExpr});";
        }

        // Nullable reference-typed static fields encode as zeros when null.
        return NullClearingEncodeStatement(destSpan, property, valueExpr, statement);
    }

    private static string NullClearingEncodeStatement(string target, SszProperty property, string valueExpr, string statement) =>
        property.IsNullable ? $"if ({valueExpr} is null) {target}.Clear(); else {statement}" : statement;

    private static bool IsByteList(SszProperty property) =>
        property.Kind == Kind.List && !property.IsSpanLikeProperty && property.Type is { Name: nameof(Byte), IsSszBasicType: true };

    private static bool IsByteVector(SszProperty property) =>
        property.Kind == Kind.Vector && !property.IsSpanLikeProperty && property.Type is { Name: nameof(Byte), IsSszBasicType: true };

    private static string DecodeAndAssign(SszType decl, SszProperty property, string sliceExpression)
    {
        string variableName = VarName(property.Name);

        if (property.Type.EnumType is { HasCustomInlineCodec: true } enumType && property.Kind == Kind.Basic)
        {
            string decodeStatement = $"container.{property.Name} = ({property.Type.TypeReferenceName}){enumType.CustomDecodeMethod}({sliceExpression});";
            string validation = ValidationStatement(decl, property, $"container.{property.Name}");
            return string.IsNullOrEmpty(validation) ? decodeStatement : $"{decodeStatement} {validation}";
        }

        if (property.Type.HasCustomInlineCodec && property.Kind == Kind.Basic)
        {
            string decodeStatement = property.Type.CustomDecodeTemplate!
                .Replace("{0}", sliceExpression)
                .Replace("{1}", $"container.{property.Name}");
            string validation = ValidationStatement(decl, property, $"container.{property.Name}");
            return string.IsNullOrEmpty(validation) ? decodeStatement : $"{decodeStatement} {validation}";
        }

        if (IsByteList(property))
        {
            string assignment = DecodeAssignmentExpression(property, variableName, sourceIsArray: true);
            return $"{{ byte[] {variableName} = DecodeSszByteList({sliceExpression}, {property.Limit}UL, nameof({decl.TypeReferenceName}), nameof({property.Name})); container.{property.Name} = {assignment}; }}";
        }

        if (IsByteVector(property))
        {
            string assignment = DecodeAssignmentExpression(property, variableName, sourceIsArray: true);
            return $"{{ byte[] {variableName} = DecodeSszByteVector({sliceExpression}, {property.Length}, nameof({decl.TypeReferenceName}), nameof({property.Name})); container.{property.Name} = {assignment}; }}";
        }

        if ((property.Kind is Kind.Vector or Kind.List or Kind.ProgressiveList) && property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec)
        {
            int itemSize = property.Type.StaticLength;
            string remainderGuard = property.Kind is Kind.List or Kind.ProgressiveList
                ? $"ValidateSszMultipleOf({sliceExpression}.Length, {itemSize}, \"{decl.TypeReferenceName}.{property.Name}\");"
                : string.Empty;
            string countDeclaration = property.Kind == Kind.Vector
                ? string.Empty
                : $"int __count = {sliceExpression}.Length / {itemSize};";
            string countExpression = property.Kind == Kind.Vector ? property.Length!.Value.ToString() : "__count";
            // No guard for limits beyond int.MaxValue: an int-typed count can never exceed them
            string limitGuard = (property.Kind == Kind.List && property.Limit is <= int.MaxValue)
                ? $"if (__count > {property.Limit.Value}) throw new System.IO.InvalidDataException($\"{decl.TypeReferenceName}.{property.Name}: list count {{__count}} exceeds SSZ limit {property.Limit.Value}\");"
                : string.Empty;
            string assignment = DecodeAssignmentExpression(property, variableName, sourceIsArray: true);
            string validation = ValidationStatement(decl, property, $"container.{property.Name}");
            string collectionDecode = $"{property.Type.TypeReferenceName}[] {variableName} = new {property.Type.TypeReferenceName}[{countExpression}]; {property.Type.CustomDecodeMethod}({sliceExpression}, {variableName});";
            string block = $"{{ {remainderGuard} {countDeclaration} {limitGuard} {collectionDecode} container.{property.Name} = {assignment}; }}";
            return string.IsNullOrEmpty(validation) ? block : $"{block} {validation}";
        }

        if ((property.Kind is Kind.Vector or Kind.List or Kind.ProgressiveList) && property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true } enumType2)
        {
            int itemSize = property.Type.StaticLength;
            string remainderGuard = property.Kind is Kind.List or Kind.ProgressiveList
                ? $"ValidateSszMultipleOf({sliceExpression}.Length, {itemSize}, \"{decl.TypeReferenceName}.{property.Name}\");"
                : string.Empty;
            string countDeclaration = property.Kind == Kind.Vector
                ? string.Empty
                : $"int __count = {sliceExpression}.Length / {itemSize};";
            string countExpression = property.Kind == Kind.Vector ? property.Length!.Value.ToString() : "__count";
            // No guard for limits beyond int.MaxValue: an int-typed count can never exceed them
            string limitGuard = (property.Kind == Kind.List && property.Limit is <= int.MaxValue)
                ? $"if (__count > {property.Limit.Value}) throw new System.IO.InvalidDataException($\"{decl.TypeReferenceName}.{property.Name}: list count {{__count}} exceeds SSZ limit {property.Limit.Value}\");"
                : string.Empty;
            string assignment = DecodeAssignmentExpression(property, variableName, sourceIsArray: true);
            string validation = ValidationStatement(decl, property, $"container.{property.Name}");
            string collectionDecode = $"{property.Type.TypeReferenceName}[] {variableName} = new {property.Type.TypeReferenceName}[{countExpression}]; {enumType2.CustomDecodeMethod}({sliceExpression}, System.Runtime.InteropServices.MemoryMarshal.Cast<{property.Type.TypeReferenceName}, {enumType2.TypeReferenceName}>({variableName}.AsSpan()));";
            string block = $"{{ {remainderGuard} {countDeclaration} {limitGuard} {collectionDecode} container.{property.Name} = {assignment}; }}";
            return string.IsNullOrEmpty(validation) ? block : $"{block} {validation}";
        }

        string outType = property.Kind switch
        {
            Kind.BitVector or Kind.BitList or Kind.ProgressiveBitList => "BitArray",
            _ when property.IsCollection => property.HandledByStd ? $"ReadOnlySpan<{property.Type.TypeReferenceName}>" : $"{property.Type.TypeReferenceName}[]",
            _ => property.Type.TypeReferenceName,
        };

        string decode = property.Kind switch
        {
            Kind.BitVector => $"DecodeSszBitVector({sliceExpression}, {property.Length}, out {outType} {variableName});",
            Kind.BitList or Kind.ProgressiveBitList => $"DecodeSszBitList({sliceExpression}, nameof({decl.TypeReferenceName}), out {outType} {variableName});",
            _ when property.HandledByStd => $"Nethermind.Serialization.Ssz.Ssz.Decode({sliceExpression}, out {outType} {variableName});",
            _ => $"{property.Type.StaticMemberAccess}.Decode({sliceExpression}, out {outType} {variableName});",
        };

        string assignment2 = $"container.{property.Name} = {DecodeAssignmentExpression(property, variableName, !property.HandledByStd)};";
        string validation2 = ValidationStatement(decl, property, $"container.{property.Name}");

        string preAllocationListGuard = string.Empty;
        // No guard for limits beyond int.MaxValue: an int-typed count can never exceed them
        if (property.Kind == Kind.List && property.Limit is <= int.MaxValue && !property.HandledByStd)
        {
            preAllocationListGuard = property.Type.IsVariable
                ? $"if ({sliceExpression}.Length >= {SszType.PointerLength}) {{ int __firstOffset = DecodeSszOffset({sliceExpression}.Slice(0, {SszType.PointerLength})); int __preCount = __firstOffset / {SszType.PointerLength}; if (__preCount > {property.Limit.Value}) throw new System.IO.InvalidDataException($\"{decl.TypeReferenceName}.{property.Name}: list count {{__preCount}} exceeds SSZ limit {property.Limit.Value}\"); }}"
                : $"{{ int __preCount = {sliceExpression}.Length / {property.Type.StaticLength}; if (__preCount > {property.Limit.Value}) throw new System.IO.InvalidDataException($\"{decl.TypeReferenceName}.{property.Name}: list count {{__preCount}} exceeds SSZ limit {property.Limit.Value}\"); }}";
        }

        List<string> statements = [];
        if (!string.IsNullOrEmpty(preAllocationListGuard))
        {
            statements.Add(preAllocationListGuard);
        }
        statements.Add(decode);
        statements.Add(assignment2);
        if (!string.IsNullOrEmpty(validation2))
        {
            statements.Add(validation2);
        }
        return string.Join(" ", statements);
    }

    private static string DecodeAssignmentExpression(SszProperty property, string variableName, bool sourceIsArray) =>
        property switch
        {
            { IsReadOnlySpanProperty: true } => variableName,
            { IsReadOnlyMemoryProperty: true } => sourceIsArray ? variableName : $"{variableName}.ToArray()",
            { IsSpanLikeProperty: true, HandledByStd: true } => sourceIsArray ? variableName : $"{variableName}.ToArray()",
            { IsSpanLikeProperty: true } => variableName,
            { IsMemoryLikeProperty: true } => sourceIsArray ? variableName : $"{variableName}.ToArray()",
            { IsCollection: true, CanConstructCollectionFromReadOnlySpan: true, CollectionTypeReferenceName: not null } => $"new {property.CollectionTypeReferenceName}({variableName})",
            { IsCollection: true, IsArrayProperty: true } => sourceIsArray ? variableName : $"[ ..{variableName}]",
            { IsCollection: true } => $"[ ..{variableName}]",
            _ => variableName,
        };

    private static string ConverterMerkleizeStatement(SszProperty property, string expression, string rootName) =>
        $"MerkleizeWithConverter({expression}, {property.Type.CustomFeedMethod}, out {rootName});";

    private static string ConverterFeedStatement(SszProperty property, string expression) =>
        property.Type.CustomFeedTemplate!
            .Replace("{0}", "merkleizer")
            .Replace("{1}", expression);

    private static string MerkleizeRootStatement(SszProperty property, string expression, string rootName) =>
        property.Kind switch
        {
            Kind.Basic when property.Type.EnumType?.CustomFeedMethod is not null => $"MerkleizeWithConverter(({property.Type.EnumType.TypeReferenceName}){expression}, {property.Type.EnumType.CustomFeedMethod}, out {rootName});",
            Kind.Basic when property.Type.CustomFeedMethod is not null => ConverterMerkleizeStatement(property, expression, rootName),
            Kind.Basic => $"Merkle.Merkleize(out {rootName}, {expression});",
            Kind.BitVector => $"Merkle.Merkleize(out {rootName}, {expression}!);",
            Kind.BitList => $"Merkle.Merkleize(out {rootName}, {expression} ?? new BitArray(0), {property.Limit}UL);",
            Kind.ProgressiveBitList => $"MerkleizeProgressiveBitList({expression}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true, IsSszBasicType: true } enumType => $"MerkleizeBasicVectorWithConverter<{enumType.TypeReferenceName}>({EnumSpanExpression(property, expression)}, {enumType.StaticLength}, {property.Length}, {enumType.CustomEncodeMethod}, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true, IsSszBasicType: true } enumType => $"MerkleizeBasicListWithConverter<{enumType.TypeReferenceName}>({EnumSpanExpression(property, expression)}, {enumType.StaticLength}, {property.Limit}UL, {enumType.CustomEncodeMethod}, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true, IsSszBasicType: true } enumType => $"MerkleizeProgressiveBasicListWithConverter<{enumType.TypeReferenceName}>({EnumSpanExpression(property, expression)}, {enumType.StaticLength}, {enumType.CustomEncodeMethod}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec && property.Type.IsSszBasicType => $"MerkleizeBasicVectorWithConverter<{property.Type.TypeReferenceName}>({SpanExpression(property, expression)}, {property.Type.StaticLength}, {property.Length}, {property.Type.CustomEncodeMethod}, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec && property.Type.IsSszBasicType => $"MerkleizeBasicListWithConverter<{property.Type.TypeReferenceName}>({SpanExpression(property, expression)}, {property.Type.StaticLength}, {property.Limit}UL, {property.Type.CustomEncodeMethod}, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec && property.Type.IsSszBasicType => $"MerkleizeProgressiveBasicListWithConverter<{property.Type.TypeReferenceName}>({SpanExpression(property, expression)}, {property.Type.StaticLength}, {property.Type.CustomEncodeMethod}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.IsSszBasicType => $"MerkleizeBasicVector({SpanExpression(property, expression)}, {property.Type.StaticLength}, {property.Length}, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.IsSszBasicType => $"MerkleizeBasicList({SpanExpression(property, expression)}, {property.Type.StaticLength}, {property.Limit}UL, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.IsSszBasicType => $"MerkleizeProgressiveBasicList({SpanExpression(property, expression)}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec => $"MerkleizeCompositeVectorWithConverter({SpanExpression(property, expression)}, {property.Length}, {property.Type.CustomFeedMethod}, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec => $"MerkleizeCompositeListWithConverter({SpanExpression(property, expression)}, {property.Limit}UL, {property.Type.CustomFeedMethod}, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec => $"MerkleizeCompositeProgressiveListWithConverter({SpanExpression(property, expression)}, {property.Type.CustomFeedMethod}, out {rootName});",
            Kind.Vector => $"{property.Type.StaticMemberAccess}.MerkleizeVector({SpanExpression(property, expression)}, out {rootName});",
            Kind.List => $"{property.Type.StaticMemberAccess}.MerkleizeList({SpanExpression(property, expression)}, {property.Limit}UL, out {rootName});",
            Kind.ProgressiveList => $"{property.Type.StaticMemberAccess}.MerkleizeProgressiveList({SpanExpression(property, expression)}, out {rootName});",
            _ => $"{property.Type.StaticMemberAccess}.Merkleize({expression}, out {rootName});",
        };

    private static string MerkleizeEmptyCollectionRootStatement(SszProperty property, string rootName) =>
        property.Kind switch
        {
            Kind.BitVector => $"Merkle.Merkleize(out {rootName}, new BitArray({property.Length}));",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true, IsSszBasicType: true } enumType => $"MerkleizeBasicVectorWithConverter<{enumType.TypeReferenceName}>(System.Runtime.InteropServices.MemoryMarshal.Cast<{property.Type.TypeReferenceName}, {enumType.TypeReferenceName}>(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty), {enumType.StaticLength}, {property.Length}, {enumType.CustomEncodeMethod}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec && property.Type.IsSszBasicType => $"MerkleizeBasicVectorWithConverter<{property.Type.TypeReferenceName}>(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Type.StaticLength}, {property.Length}, {property.Type.CustomEncodeMethod}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.IsSszBasicType => $"MerkleizeBasicVector(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Type.StaticLength}, {property.Length}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec => $"MerkleizeDefaultCompositeVectorWithConverter<{property.Type.TypeReferenceName}>({property.Type.StaticLength}, {property.Length}, {property.Type.CustomDecodeMethod}, {property.Type.CustomFeedMethod}, out {rootName});",
            Kind.Vector when property.Type.Kind == Kind.Basic => $"Merkle.Merkleize(out {rootName}, ReadOnlySpan<UInt256>.Empty, {property.Length});",
            Kind.Vector => $"{{ {property.Type.TypeReferenceName}[] __empty{property.Name} = new {property.Type.TypeReferenceName}[{property.Length}]; {property.Type.StaticMemberAccess}.MerkleizeVector(__empty{property.Name}, out {rootName}); }}",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true, IsSszBasicType: true } enumType => $"MerkleizeBasicListWithConverter<{enumType.TypeReferenceName}>(System.Runtime.InteropServices.MemoryMarshal.Cast<{property.Type.TypeReferenceName}, {enumType.TypeReferenceName}>(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty), {enumType.StaticLength}, {property.Limit}UL, {enumType.CustomEncodeMethod}, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true, IsSszBasicType: true } enumType => $"MerkleizeProgressiveBasicListWithConverter<{enumType.TypeReferenceName}>(System.Runtime.InteropServices.MemoryMarshal.Cast<{property.Type.TypeReferenceName}, {enumType.TypeReferenceName}>(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty), {enumType.StaticLength}, {enumType.CustomEncodeMethod}, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec && property.Type.IsSszBasicType => $"MerkleizeBasicListWithConverter<{property.Type.TypeReferenceName}>(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Type.StaticLength}, {property.Limit}UL, {property.Type.CustomEncodeMethod}, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec && property.Type.IsSszBasicType => $"MerkleizeProgressiveBasicListWithConverter<{property.Type.TypeReferenceName}>(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Type.StaticLength}, {property.Type.CustomEncodeMethod}, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.IsSszBasicType => $"MerkleizeBasicList(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Type.StaticLength}, {property.Limit}UL, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.IsSszBasicType => $"MerkleizeProgressiveBasicList(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, out {rootName});",
            Kind.List when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec => $"MerkleizeCompositeListWithConverter(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Limit}UL, {property.Type.CustomFeedMethod}, out {rootName});",
            Kind.ProgressiveList when property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec => $"MerkleizeCompositeProgressiveListWithConverter(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Type.CustomFeedMethod}, out {rootName});",
            Kind.List => $"{property.Type.StaticMemberAccess}.MerkleizeList(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, {property.Limit}UL, out {rootName});",
            Kind.ProgressiveList => $"{property.Type.StaticMemberAccess}.MerkleizeProgressiveList(ReadOnlySpan<{property.Type.TypeReferenceName}>.Empty, out {rootName});",
            _ => throw new InvalidOperationException($"Cannot merkleize an empty {property.Kind} collection."),
        };

    private static string MerkleizeDefaultStaticRootStatement(SszProperty property, string rootName)
    {
        string valueName = "__default" + property.Name;
        return $"{{ byte[] {valueName}Data = new byte[{property.StaticLength}]; {property.Type.StaticMemberAccess}.Decode({valueName}Data, out {property.Type.TypeReferenceName} {valueName}); {property.Type.StaticMemberAccess}.Merkleize({valueName}, out {rootName}); }}";
    }

    private static string MerkleizeRootAssignmentStatement(SszProperty property, string expression, string rootName)
    {
        string body = MerkleizeRootStatement(property, expression, rootName);
        if (!property.IsNullable || property.IsSpanLikeProperty || property.Kind is Kind.BitList or Kind.ProgressiveBitList)
        {
            return body;
        }

        if (property.Kind is (Kind.Vector or Kind.BitVector or Kind.List or Kind.ProgressiveList) && CanEncodeNullAsDefault(property))
        {
            return $"if ({expression} is null) {{ {MerkleizeEmptyCollectionRootStatement(property, rootName)} }} else {{ {body} }}";
        }

        if (property.Kind == Kind.Basic && property.Type.HasCustomInlineCodec)
        {
            return $"if ({expression} is null) {{ MerkleizeDefaultWithConverter<{property.Type.TypeReferenceName}>({property.Type.StaticLength}, {property.Type.CustomDecodeMethod}, {property.Type.CustomFeedMethod}, out {rootName}); }} else {{ {body} }}";
        }

        if (!property.IsVariable && property.Kind != Kind.Basic)
        {
            return $"if ({expression} is null) {{ {MerkleizeDefaultStaticRootStatement(property, rootName)} }} else {{ {body} }}";
        }

        return $"if ({expression} is null) {{ {rootName} = default; }} else {{ {body} }}";
    }

    private static string MerkleizeFeedStatement(SszProperty property, string expression)
    {
        if (property.Kind == Kind.Basic && property.Type.CustomFeedTemplate is not null && !property.IsNullable)
        {
            return ConverterFeedStatement(property, expression);
        }

        string rootName = VarName(property.Name) + "Root";
        return $"UInt256 {rootName}; {MerkleizeRootAssignmentStatement(property, expression, rootName)} merkleizer.Feed({rootName});";
    }

    private static string DynamicLength(SszType container, SszProperty m)
    {
        if ((m.Kind & (Kind.Collection | Kind.BitList | Kind.ProgressiveBitList)) != Kind.None && m.Type.Kind == Kind.Basic)
        {
            string length = m.Kind is Kind.BitList or Kind.ProgressiveBitList
                ? $"(container.{m.Name} is not null ? container.{m.Name}.Length / 8 + 1 : 1)"
                : $"({m.Type.StaticLength} * {SpanExpression(m, $"container.{m.Name}")}.Length)";
            return m.IsNullable && (m.Kind is Kind.List or Kind.ProgressiveList) && CanEncodeNullAsDefault(m)
                ? $"(container.{m.Name} is null ? 0 : {length})"
                : length;
        }

        string call = m.IsCollection
            ? $"{m.Type.StaticMemberAccess}.GetLength({SpanExpression(m, $"container.{m.Name}")})"
            : $"{m.Type.StaticMemberAccess}.GetLength(container.{m.Name})";

        // A null reference-typed property contributes zero bytes to the variable-length region —
        // matches the static-field encode's "skip on null" behaviour and keeps offsets consistent.
        return m.IsNullable ? $"(container.{m.Name} is null ? 0 : {call})" : call;
    }

    private static string ByteArrayLiteral(byte[] value) => $"[{string.Join(", ", value)}]";

    private static string ProgressiveContainerMerkleizeBody(SszType decl)
    {
        string activeFields = ByteArrayLiteral(decl.ActiveFieldsBytes ?? []);
        IEnumerable<string> memberRoots = decl.Members!.Select((m, index) =>
        {
            string validation = ValidationStatement(decl, m, $"container.{m.Name}");
            string merkleize = MerkleizeRootAssignmentStatement(m, $"container.{m.Name}", $"subRoots[{index}]");
            return string.IsNullOrEmpty(validation) ? merkleize : $"{validation} {merkleize}";
        });

        return string.Join("\n",
        [
            $"UInt256[] subRoots = new UInt256[{decl.Members!.Length}];",
            ..memberRoots,
            "Merkle.MerkleizeProgressive(out root, subRoots);",
            $"Merkle.MixInActiveFields(ref root, {activeFields});",
        ]);
    }

    private static string EncodeStatement(string target, SszProperty property, string expression)
    {
        if (property.Kind == Kind.Basic && property.Type.HasCustomInlineCodec)
        {
            return property.Type.CustomEncodeTemplate!
                .Replace("{0}", target)
                .Replace("{1}", EncodeValueExpression(property, expression));
        }

        if ((property.Kind is Kind.List or Kind.Vector or Kind.ProgressiveList) && property.Type.Kind == Kind.Basic && property.Type.HasCustomInlineCodec)
        {
            return $"{property.Type.CustomEncodeMethod}({target}, {SpanExpression(property, expression)});";
        }

        if ((property.Kind is Kind.List or Kind.Vector or Kind.ProgressiveList) && property.Type.Kind == Kind.Basic && property.Type.EnumType is { HasCustomInlineCodec: true } enumType)
        {
            return $"{enumType.CustomEncodeMethod}({target}, {EnumSpanExpression(property, expression)});";
        }

        string arguments = $"{target}, {EncodeValueExpression(property, expression)}";
        if (property.Kind == Kind.BitList)
        {
            // The Encode limit parameter is int-typed; bitlist limits beyond int.MaxValue are
            // rejected at parse time (a BitArray cannot exceed int.MaxValue bits), so this fits.
            arguments += $", {property.Limit!.Value}";
        }
        else if (property.Kind == Kind.ProgressiveBitList)
        {
            arguments += $", {UnboundedBitlistLimit}";
        }

        return $"{(property.HandledByStd ? "Nethermind.Serialization.Ssz.Ssz.Encode" : $"{property.Type.StaticMemberAccess}.Encode")}({arguments});";
    }

    private static bool RequiresNullGuard(SszProperty property)
    {
        if (property.IsSpanLikeProperty || property.IsMemoryLikeProperty || property.Kind is Kind.BitList or Kind.ProgressiveBitList)
        {
            return false;
        }

        return (property.IsNullable && CanEncodeNullAsDefault(property)) || !property.Type.IsStruct;
    }

    private static string UsingsBlock(SszType decl) =>
        string.Join("\n", ReferencedTypes(decl)
            .SelectMany(GeneratedNamespaces)
            .Concat(decl.TypeParameterConstraintNamespaces)
            .Append("Nethermind.Int256")
            .Append("System")
            .Distinct()
            .OrderBy(x => x)
            .Where(x => !string.IsNullOrEmpty(x) && x != decl.Namespace && x != "Nethermind.Serialization.Ssz")
            .Select(n => $"using {n};"));

    private static IEnumerable<SszType> ReferencedTypes(SszType type)
    {
        HashSet<SszType> visited = [];
        Stack<SszType> pending = new();
        pending.Push(type);

        while (pending.Count > 0)
        {
            SszType current = pending.Pop();
            if (!visited.Add(current))
            {
                continue;
            }

            yield return current;

            if (current.EnumType is not null)
            {
                pending.Push(current.EnumType);
            }

            if (current.Members is null)
            {
                continue;
            }

            for (int i = 0; i < current.Members.Length; i++)
            {
                pending.Push(current.Members[i].Type);
            }
        }
    }

    private static IEnumerable<string> GeneratedNamespaces(SszType type)
    {
        string? typeNamespace = type.Namespace;
        if (typeNamespace is { Length: > 0 })
        {
            yield return typeNamespace;
        }

        foreach (string namespaceName in type.AdditionalNamespaces)
        {
            yield return namespaceName;
        }
    }

    private static string? GenerateClassCode(SourceProductionContext context, SszType decl, Location? location)
    {
        try
        {
            List<SszProperty> variables = decl.Members.Where(m => m.IsVariable).ToList();
            IEnumerable<string> BuildStaticEncodeLines(SszType d)
            {
                int localStaticOffset = 0;
                int localOffsetIndex = 0;
                foreach (SszProperty m in d.Members!)
                {
                    string line;
                    if (m.IsVariable)
                    {
                        localOffsetIndex++;
                        line = $"EncodeSszOffset(data.Slice({localStaticOffset}, 4), offset{localOffsetIndex});";
                    }
                    else
                    {
                        line = StaticFieldEncodeStatement(m, localStaticOffset, "container");
                    }
                    localStaticOffset += m.StaticLength;
                    yield return line;
                }
            }

            IEnumerable<string> BuildStaticDecodeLines(SszType d)
            {
                int localOffset = 0;
                int localOffsetIndex = 0;
                foreach (SszProperty m in d.Members!)
                {
                    string line;
                    if (m.IsVariable)
                    {
                        localOffsetIndex++;
                        line = $"int offset{localOffsetIndex} = DecodeSszOffset(data.Slice({localOffset}, 4));";
                    }
                    else
                    {
                        line = DecodeAndAssign(d, m, $"data.Slice({localOffset}, {m.StaticLength})");
                    }
                    localOffset += m.StaticLength;
                    yield return line;
                }
            }

            string containerMerkleizeBody = decl.Kind == Kind.ProgressiveContainer
                ? ProgressiveContainerMerkleizeBody(decl)
                : string.Join("\n",
                [
                    $"Merkleizer merkleizer = new Merkleizer(Merkle.NextPowerOfTwoExponent({decl.Members!.Length}));",
                    ..decl.Members.Select(m => MerkleizeFeedStatement(m, $"container.{m.Name}")),
                    "merkleizer.CalculateRoot(out root);",
                ]);
            bool isByteListItself = decl.IsSszListItself && IsByteList(variables[0]);
            string DecodeCollectionItem(string sliceExpression, string destination) => isByteListItself
                ? $"{destination}.{variables[0].Name} = DecodeSszByteList({sliceExpression}, {variables[0].Limit}UL, nameof({decl.TypeReferenceName}), nameof({variables[0].Name}));"
                : $"Decode({sliceExpression}, out {destination});";
            string result = FixWhitespace(decl.IsSszListItself ?
$@"using Nethermind.Serialization.Ssz.Merkleization;
using Nethermind.Serialization.Ssz;
using static Nethermind.Serialization.SszCodecHelpers;
{UsingsBlock(decl)}
{Whitespace}
{NamespaceLine(decl)}
{Whitespace}
{PartialTypeDeclaration(decl)}
{{
    public static int GetLength({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return 0;
        }")}
{Whitespace}
        {ValidationStatement(decl, variables[0], $"container.{variables[0].Name}")}
        return {DynamicLength(decl, variables[0])};
    }}
{Whitespace}
    public static int GetLength(ReadOnlySpan<{decl.TypeReferenceName}> container)
    {{
        int length = container.Length * {SszType.PointerLength};
        foreach({decl.TypeReferenceName} item in container)
        {{
            length += GetLength(item);
        }}
{Whitespace}
        return length;
    }}
{Whitespace}
    public static byte[] Encode({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return [];
        }")}
        byte[] buf = global::System.GC.AllocateUninitializedArray<byte>(GetLength(container));
        Encode(buf, container);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, {decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return;
        }")}
{Whitespace}
        {ValidationStatement(decl, variables[0], $"container.{variables[0].Name}")}
        {(RequiresNullGuard(variables[0]) ? $"if (container.{variables[0].Name} is not null) " : string.Empty)}{EncodeStatement("data", variables[0], $"container.{variables[0].Name}")}
    }}
{Whitespace}
    public static byte[] Encode(ReadOnlySpan<{decl.TypeReferenceName}> items)
    {{
        byte[] buf = global::System.GC.AllocateUninitializedArray<byte>(GetLength(items));
        Encode(buf, items);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, ReadOnlySpan<{decl.TypeReferenceName}> items)
    {{
{Whitespace}
        int offset = items.Length * {(SszType.PointerLength)};
        int itemOffset = 0;
{Whitespace}
        foreach({decl.TypeReferenceName} item in items)
        {{
            EncodeSszOffset(data.Slice(itemOffset, {(SszType.PointerLength)}), offset);
            itemOffset += {(SszType.PointerLength)};
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.TypeReferenceName} container)
    {{
        container = new();
{Whitespace}
        {DecodeAndAssign(decl, variables[0], "data")}
    }}
{Whitespace}
    {SequenceDecodeMethod(decl.TypeReferenceName)}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.TypeReferenceName}[] container)
    {{
        if(data.Length is 0)
        {{
            container = [];
            return;
        }}
{Whitespace}
        {(decl.IsVariable ? $@"ValidateSszMinimumLength(data.Length, {SszType.PointerLength}, ""{decl.TypeReferenceName}[]"");
        int firstOffset = DecodeSszOffset(data.Slice(0, 4));
        int length = ValidateSszVariableItemCount(data, firstOffset, ""{decl.TypeReferenceName}[]"")" : $@"ValidateSszMultipleOf(data.Length, {decl.StaticLength}, ""{decl.TypeReferenceName}[]"");
        int length = data.Length / {decl.StaticLength}")};
        container = new {decl.TypeReferenceName}[length];
{Whitespace}
        {(decl.IsVariable ? @$"int index = 0;
        int offset = firstOffset;
        for(int nextOffsetIndex = {SszType.PointerLength}; index < length - 1; index++, nextOffsetIndex += {SszType.PointerLength})
        {{
            int nextOffset = DecodeSszOffset(data.Slice(nextOffsetIndex, {SszType.PointerLength}));
            ValidateSszNextOffset(data, offset, nextOffset, ""{decl.TypeReferenceName}[]"");
            {DecodeCollectionItem("data.Slice(offset, nextOffset - offset)", "container[index]")}
            offset = nextOffset;
        }}
{Whitespace}
        {DecodeCollectionItem("data.Slice(offset)", "container[index]")}" : @$"int offset = 0;
        for(int index = 0; index < length; index++)
        {{
            Decode(data.Slice(offset, {decl.StaticLength}), out container[index]);
            offset += {decl.StaticLength};
        }}")}
    }}
{Whitespace}
    public static void Merkleize({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container, out UInt256 root)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            root = 0;
            return;
        }")}
        {ValidationStatement(decl, variables[0], $"container.{variables[0].Name}")}
        {MerkleizeRootAssignmentStatement(variables[0], $"container.{variables[0].Name}", "root")}
    }}
{Whitespace}
    public static void MerkleizeVector(ReadOnlySpan<{decl.TypeReferenceName}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.Merkleize(out root, subRoots.AsSpan(0, count));
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
    }}
{Whitespace}
    public static void MerkleizeList(ReadOnlySpan<{decl.TypeReferenceName}> container, ulong limit, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.Merkleize(out root, subRoots.AsSpan(0, count), limit);
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
        Merkle.MixIn(ref root, count);
    }}
{Whitespace}
    public static void MerkleizeProgressiveList(ReadOnlySpan<{decl.TypeReferenceName}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.MerkleizeProgressive(out root, subRoots.AsSpan(0, count));
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
        Merkle.MixIn(ref root, count);
    }}
}}
" :
(decl.Kind == Kind.Container || decl.Kind == Kind.ProgressiveContainer) ?
$@"using Nethermind.Serialization.Ssz.Merkleization;
using Nethermind.Serialization.Ssz;
using static Nethermind.Serialization.SszCodecHelpers;
{UsingsBlock(decl)}
{Whitespace}
{NamespaceLine(decl)}
{Whitespace}
{PartialTypeDeclaration(decl)}
{{
    public static int GetLength({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return 0;
        }")}
{Whitespace}
{Shift(2, ValidationStatements(decl, decl.Members!, "container"))}
{Whitespace}
        return {decl.StaticLength}{(variables.Any() ? "" : ";")}
{Shift(4, variables.Select(m => $"+ {DynamicLength(decl, m)}"), ";")}
    }}
{Whitespace}
    public static int GetLength(ReadOnlySpan<{decl.TypeReferenceName}> container)
    {{
        {(decl.IsVariable ? @$"int length = container.Length * {SszType.PointerLength};
        foreach({decl.TypeReferenceName} item in container)
        {{
            length += GetLength(item);
        }}
{Whitespace}
        return length;" : $"return container.Length * {(decl.StaticLength)};")}
    }}
{Whitespace}
    public static byte[] Encode({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return [];
        }")}
        byte[] buf = global::System.GC.AllocateUninitializedArray<byte>(GetLength(container));
        Encode(buf, container);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, {decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return;
        }")}
{Whitespace}
{Shift(2, ValidationStatements(decl, decl.Members!, "container"))}
{Whitespace}
{Shift(2, variables.Select((_, i) => $"int offset{i + 1} = {(i == 0 ? decl.StaticLength : $"offset{i} + {DynamicLength(decl, variables[i - 1])}")};"))}
{Whitespace}
{Shift(2, BuildStaticEncodeLines(decl))}
{Whitespace}
{Shift(2, variables.Select((m, i) => (RequiresNullGuard(m) ? $"if (container.{m.Name} is not null) " : "") + EncodeStatement($"data.Slice(offset{i + 1}, {(i + 1 == variables.Count ? "data.Length" : $"offset{i + 2}")} - offset{i + 1})", m, $"container.{m.Name}")))}
    }}
{Whitespace}
    public static byte[] Encode(ReadOnlySpan<{decl.TypeReferenceName}> items)
    {{
        byte[] buf = global::System.GC.AllocateUninitializedArray<byte>(GetLength(items));
        Encode(buf, items);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, ReadOnlySpan<{decl.TypeReferenceName}> items)
    {{
{Whitespace}
        {(decl.IsVariable ? @$"int offset = items.Length * {(SszType.PointerLength)};
        int itemOffset = 0;
{Whitespace}
        foreach({decl.TypeReferenceName} item in items)
        {{
            EncodeSszOffset(data.Slice(itemOffset, {(SszType.PointerLength)}), offset);
            itemOffset += {(SszType.PointerLength)};
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}" : @$"int offset = 0;
        foreach({decl.TypeReferenceName} item in items)
        {{
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}")}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.TypeReferenceName} container)
    {{
        {(decl.IsVariable ? $"ValidateSszMinimumLength(data.Length, {decl.StaticLength}, nameof({decl.TypeReferenceName}));" : $"ValidateSszExactLength(data.Length, {decl.StaticLength}, nameof({decl.TypeReferenceName}));")}
        container = new();
{Whitespace}
{Shift(2, BuildStaticDecodeLines(decl))}
{Whitespace}
        {(variables.Any() ? $"ValidateSszDynamicOffsets(data, {decl.StaticLength}, nameof({decl.TypeReferenceName}), [{string.Join(", ", Enumerable.Range(1, variables.Count).Select(i => $"offset{i}"))}]);" : string.Empty)}
{Whitespace}
{Shift(2, variables.Select((m, i) => DecodeAndAssign(decl, m, $"data.Slice(offset{i + 1}, {(i + 1 == variables.Count ? "data.Length" : $"offset{i + 2}")} - offset{i + 1})")))}
    }}
{Whitespace}
    {SequenceDecodeMethod(decl.TypeReferenceName)}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.TypeReferenceName}[] container)
    {{
        if(data.Length is 0)
        {{
            container = [];
            return;
        }}
{Whitespace}
        {(decl.IsVariable ? $@"ValidateSszMinimumLength(data.Length, {SszType.PointerLength}, ""{decl.TypeReferenceName}[]"");
        int firstOffset = DecodeSszOffset(data.Slice(0, 4));
        int length = ValidateSszVariableItemCount(data, firstOffset, ""{decl.TypeReferenceName}[]"")" : $@"ValidateSszMultipleOf(data.Length, {decl.StaticLength}, ""{decl.TypeReferenceName}[]"");
        int length = data.Length / {decl.StaticLength}")};
        container = new {decl.TypeReferenceName}[length];
{Whitespace}
        {(decl.IsVariable ? @$"int index = 0;
        int offset = firstOffset;
        for(int nextOffsetIndex = {SszType.PointerLength}; index < length - 1; index++, nextOffsetIndex += {SszType.PointerLength})
        {{
            int nextOffset = DecodeSszOffset(data.Slice(nextOffsetIndex, {SszType.PointerLength}));
            ValidateSszNextOffset(data, offset, nextOffset, ""{decl.TypeReferenceName}[]"");
            Decode(data.Slice(offset, nextOffset - offset), out container[index]);
            offset = nextOffset;
        }}
{Whitespace}
        Decode(data.Slice(offset), out container[index]);" : @$"int offset = 0;
        for(int index = 0; index < length; index++)
        {{
            Decode(data.Slice(offset, {decl.StaticLength}), out container[index]);
            offset += {decl.StaticLength};
        }}")}
    }}
{Whitespace}
    public static void Merkleize({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container, out UInt256 root)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            root = 0;
            return;
        }")}
{Shift(2, ValidationStatements(decl, decl.Members!, "container"))}
{Whitespace}
{Shift(2, containerMerkleizeBody.Split('\n'))}
    }}
{Whitespace}
    public static void MerkleizeVector(ReadOnlySpan<{decl.TypeReferenceName}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.Merkleize(out root, subRoots.AsSpan(0, count));
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
    }}
{Whitespace}
    public static void MerkleizeList(ReadOnlySpan<{decl.TypeReferenceName}> container, ulong limit, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.Merkleize(out root, subRoots.AsSpan(0, count), limit);
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
        Merkle.MixIn(ref root, count);
    }}
{Whitespace}
    public static void MerkleizeProgressiveList(ReadOnlySpan<{decl.TypeReferenceName}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.MerkleizeProgressive(out root, subRoots.AsSpan(0, count));
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
        Merkle.MixIn(ref root, count);
    }}
}}
" :
// Compatible unions
$@"using Nethermind.Serialization.Ssz.Merkleization;
using Nethermind.Serialization.Ssz;
using static Nethermind.Serialization.SszCodecHelpers;
{UsingsBlock(decl)}
{Whitespace}
{NamespaceLine(decl)}
{Whitespace}
{PartialTypeDeclaration(decl)}
{{
    public static int GetLength({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return 0;
        }")}
        switch(container.Selector) {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m =>
{
    string validation = ValidationStatement(decl, m, $"container.{m.Name}");
    string length = m.IsVariable ? DynamicLength(decl, m) : m.StaticLength.ToString();
    return string.IsNullOrEmpty(validation)
        ? $"case {decl.Selector!.Type.StaticMemberAccess}.{m.Name}: return 1 + {length};"
        : $"case {decl.Selector!.Type.StaticMemberAccess}.{m.Name}: {validation} return 1 + {length};";
}))}
            default:
                return ThrowInvalidSszData<int>(nameof({decl.TypeReferenceName}), $""unsupported union selector {{(byte)container.Selector}}."");
        }}
    }}
{Whitespace}
    public static int GetLength(ReadOnlySpan<{decl.TypeReferenceName}> container)
    {{
        int length = container.Length * {SszType.PointerLength};
        foreach({decl.TypeReferenceName} item in container)
        {{
            length += GetLength(item);
        }}
{Whitespace}
        return length;
    }}
{Whitespace}
    public static byte[] Encode({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return [];
        }")}
        byte[] buf = global::System.GC.AllocateUninitializedArray<byte>(GetLength(container));
        Encode(buf, container);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, {decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            return;
        }")}
        ValidateSszExactLength(data.Length, GetLength(container), nameof({decl.TypeReferenceName}));
        data[0] = (byte)container.Selector;
{Whitespace}
        switch(container.Selector) {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m =>
{
    string expression = $"container.{m.Name}";
    string target = "data.Slice(1)";
    string encode = NullClearingEncodeStatement(target, m, expression, EncodeStatement(target, m, expression));
    return $"case {decl.Selector!.Type.StaticMemberAccess}.{m.Name}: {encode} break;";
}))}
            default:
                ThrowInvalidSszData(nameof({decl.TypeReferenceName}), $""unsupported union selector {{(byte)container.Selector}}."");
                break;
        }};
    }}
{Whitespace}
    public static byte[] Encode(ReadOnlySpan<{decl.TypeReferenceName}> items)
    {{
        byte[] buf = global::System.GC.AllocateUninitializedArray<byte>(GetLength(items));
        Encode(buf, items);
        return buf;
    }}
{Whitespace}
    public static void Encode(Span<byte> data, ReadOnlySpan<{decl.TypeReferenceName}> items)
    {{
        int offset = items.Length * {(SszType.PointerLength)};
        int itemOffset = 0;
        foreach({decl.TypeReferenceName} item in items)
        {{
            EncodeSszOffset(data.Slice(itemOffset, {(SszType.PointerLength)}), offset);
            itemOffset += {(SszType.PointerLength)};
            int length = GetLength(item);
            Encode(data.Slice(offset, length), item);
            offset += length;
        }}
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.TypeReferenceName}[] container)
    {{
        if(data.Length is 0)
        {{
            container = [];
            return;
        }}
{Whitespace}
        ValidateSszMinimumLength(data.Length, {SszType.PointerLength}, ""{decl.TypeReferenceName}[]"");
        int firstOffset = DecodeSszOffset(data.Slice(0, 4));
        int length = ValidateSszVariableItemCount(data, firstOffset, ""{decl.TypeReferenceName}[]"");
        container = new {decl.TypeReferenceName}[length];
{Whitespace}
        int index = 0;
        int offset = firstOffset;
        for(int nextOffsetIndex = {SszType.PointerLength}; index < length - 1; index++, nextOffsetIndex += {SszType.PointerLength})
        {{
            int nextOffset = DecodeSszOffset(data.Slice(nextOffsetIndex, {SszType.PointerLength}));
            ValidateSszNextOffset(data, offset, nextOffset, ""{decl.TypeReferenceName}[]"");
            Decode(data.Slice(offset, nextOffset - offset), out container[index]);
            offset = nextOffset;
        }}
{Whitespace}
        Decode(data.Slice(offset), out container[index]);
    }}
{Whitespace}
    public static void Decode(ReadOnlySpan<byte> data, out {decl.TypeReferenceName} container)
    {{
        container = new();
        ValidateSszMinimumLength(data.Length, 1, nameof({decl.TypeReferenceName}));
        container.Selector = ({decl.Selector!.Type.StaticMemberAccess})data[0];
        switch(container.Selector) {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m => $"case {decl.Selector!.Type.StaticMemberAccess}.{m.Name}: {DecodeAndAssign(decl, m, "data.Slice(1)")} break;"))}
            default:
                ThrowInvalidSszData(nameof({decl.TypeReferenceName}), $""unsupported union selector {{data[0]}}."");
                break;
        }};
        ValidateSszExactLength(data.Length, GetLength(container), nameof({decl.TypeReferenceName}));
    }}
{Whitespace}
    {SequenceDecodeMethod(decl.TypeReferenceName)}
{Whitespace}
    public static void Merkleize({decl.TypeReferenceName}{(decl.IsStruct ? "" : "?")} container, out UInt256 root)
    {{
        {(decl.IsStruct ? "" : @"if(container is null)
        {
            root = 0;
            return;
        }")}
        switch(container.Selector) {{
{Shift(3, decl.CompatibleUnionMembers!.Select(m =>
{
    string validation = ValidationStatement(decl, m, $"container.{m.Name}");
    string merkleize = MerkleizeRootAssignmentStatement(m, $"container.{m.Name}", "root");
    return string.IsNullOrEmpty(validation)
        ? $"case {decl.Selector!.Type.StaticMemberAccess}.{m.Name}: {merkleize} break;"
        : $"case {decl.Selector!.Type.StaticMemberAccess}.{m.Name}: {validation} {merkleize} break;";
}))}
            default:
                root = ThrowInvalidSszData<UInt256>(nameof({decl.TypeReferenceName}), $""unsupported union selector {{(byte)container.Selector}}."");
                break;
        }};
        Merkle.MixIn(ref root, (byte)container.Selector);
    }}
{Whitespace}
    public static void MerkleizeVector(ReadOnlySpan<{decl.TypeReferenceName}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.Merkleize(out root, subRoots.AsSpan(0, count));
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
    }}
{Whitespace}
    public static void MerkleizeList(ReadOnlySpan<{decl.TypeReferenceName}> container, ulong limit, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.Merkleize(out root, subRoots.AsSpan(0, count), limit);
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
        Merkle.MixIn(ref root, count);
    }}
{Whitespace}
    public static void MerkleizeProgressiveList(ReadOnlySpan<{decl.TypeReferenceName}> container, out UInt256 root)
    {{
        int count = container.Length;
        UInt256[] subRoots = System.Buffers.ArrayPool<UInt256>.Shared.Rent(count);
        try
        {{
            for(int i = 0; i < count; i++)
            {{
                Merkleize(container[i], out subRoots[i]);
            }}
{Whitespace}
            Merkle.MerkleizeProgressive(out root, subRoots.AsSpan(0, count));
        }}
        finally
        {{
            System.Buffers.ArrayPool<UInt256>.Shared.Return(subRoots);
        }}
        Merkle.MixIn(ref root, count);
    }}
}}
");
#if DEBUG
#pragma warning disable RS1035 // Allow console for debugging
            Console.WriteLine(WithLineNumbers(result, false));
#pragma warning restore RS1035
#endif
            return GeneratedSourceHeader + result;
        }
        catch (Exception e)
        {
            context.ReportDiagnostic(Diagnostic.Create(GenerationFailureRule, location ?? Location.None, decl.Name, e.Message));
            return null;
        }
    }

#if DEBUG
    static string WithLineNumbers(string input, bool bypass = false)
    {
        if (bypass) return input;

        string[] lines = input.Split('\n');
        int lineNumberWidth = lines.Length.ToString().Length;

        StringBuilder sb = new();
        for (int i = 0; i < lines.Length; i++)
        {
            string lineNumber = (i + 1).ToString().PadLeft(lineNumberWidth);
            sb.AppendLine($"{lineNumber}: {lines[i]}");
        }

        return sb.ToString();
    }
#endif
}
