<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../tests.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <CodeAnalysisGenerateSuccessFile>false</CodeAnalysisGenerateSuccessFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Serialization.Json\Nethermind.Serialization.Json.csproj" />
    <ProjectReference Include="..\Nethermind.Serialization.JsonGenerator\Nethermind.Serialization.JsonGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
