// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Text;

namespace Nethermind.Evm.Lean.FrameJournalExtractor;

internal static class FrameJournalLeanEmitter
{
    internal static byte[] Emit(IrDocument document, string irHash)
    {
        string operationNames = string.Join(", ", document.Operations.Select(operation => $"\"{operation.Name}\""));
        string dependencyTheorems = string.Join(", ", document.DependencyTheorems.Select(theorem => $"\"{theorem}\""));
        string source = $$"""
            -- SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
            -- SPDX-License-Identifier: LGPL-3.0-only

            -- Generated by FrameJournalExtractor; do not edit.
            -- Extractor: {{document.ExtractorVersion}}
            -- Semantic IR SHA-256: {{irHash}}

            import FrameJournalExtractor.Specification.FrameJournalState
            import WorldJournalExtractor.Generated.WorldJournalKernel

            namespace FrameJournalExtractor.Generated.FrameJournalKernel

            open FrameJournalExtractor
            open WorldJournalExtractor

            namespace WorldGenerated
            export WorldJournalExtractor.Generated.WorldJournalKernel (transition executeTrace)
            end WorldGenerated

            def admittedOperationNames : List String := [{{operationNames}}]

            def admittedDependencyTheorems : List String := [{{dependencyTheorems}}]

            def markCreated (world : WorldMachine) (address : Address) : WorldMachine :=
              { world with journal :=
                  { world.journal with
                    createdThisTx := FiniteSet.insert world.journal.createdThisTx address } }

            def enter (kind : FrameKind) (machine : Machine) : Option Machine :=
              let prepared := match kind with
                | .call => machine.world
                | .create address => markCreated machine.world address
              match WorldGenerated.transition .takeSnapshot prepared with
              | none => none
              | some world => some { machine with world, frames := kind :: machine.frames }

            def retainAndPop (machine : Machine) : Option Machine :=
              match machine.frames, machine.world.snapshots with
              | _ :: frames, _ :: snapshots =>
                  some { machine with world := { machine.world with snapshots }, frames }
              | _, _ => none

            def reapplyRipemdTouch (machine : Machine) : Option Machine :=
              if machine.ripemdTouchLatched then
                match WorldGenerated.transition (.readAccount ripemd160Address) machine.world with
                | none => none
                | some readWorld =>
                    match FiniteMap.lookup readWorld.journal.accounts.current ripemd160Address with
                    | none => some { machine with world := readWorld }
                    | some account =>
                        if isEmptyAccount account then
                          (WorldGenerated.transition (.updateAccount ripemd160Address account) readWorld).map fun world =>
                            { machine with world }
                        else
                          some { machine with world := readWorld }
              else
                some machine

            def restoreAndPop (machine : Machine) : Option Machine :=
              match machine.frames with
              | [] => none
              | _ :: frames =>
                  match WorldGenerated.transition .restoreSnapshot machine.world with
                  | none => none
                  | some world => reapplyRipemdTouch { machine with world, frames }

            def transition (operation : Operation) (machine : Machine) : Option Machine :=
              match operation with
              | .applyWorld worldOperation =>
                  if isBodyOperation worldOperation then
                    (WorldGenerated.transition worldOperation machine.world).map fun world =>
                      { machine with world }
                  else
                    none
              | .enterCall => enter .call machine
              | .enterCreate address => enter (.create address) machine
              | .preFrameCallFailure => some machine
              | .preFrameCreateFailure => some machine
              | .latchRipemdTouch => some { machine with ripemdTouchLatched := true }
              | .exitSuccess => retainAndPop machine
              | .exitRevert => restoreAndPop machine
              | .exitException => restoreAndPop machine

            def executeTrace : List Operation → Machine → Option Machine
              | [], machine => some machine
              | operation :: tail, machine =>
                  match transition operation machine with
                  | none => none
                  | some next => executeTrace tail next

            end FrameJournalExtractor.Generated.FrameJournalKernel
            """;
        return Encoding.UTF8.GetBytes(source.ReplaceLineEndings("\n") + "\n");
    }
}
