<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Nethermind.RpcTests.Generator</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SmartFormat" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
