name: Setup GH Runner
description: "Setup a self-hosted GitHub Actions runner"
inputs:
  gh-token:
    description: "The token of the GitHub App to use for authentication"
    required: true
  gh-username:
    description: "GitHub username that manages this runner"
    required: true
  runner-name:
    description: "Runner name to be used as base label for the Linode instance"
    required: true
  runner-type:
    description: "Runner Linode machine type (e.g., g6-standard-2)"
    required: true
  tags:
    description: "Comma separated tags for the runner machine"
    required: false
    default: ""
  allowed-ips:
    description: "Comma separated allowed IPs for the runner firewall"
    required: false
    default: ""
  ssh-keys:
    description: "Comma separated public SSH keys for the runner machine"
    required: false
    default: ""
  timeout:
    description: "Timeout for the runner machine auto removal in hours"
    required: false
    default: "24"
  setup-wait-time:
    description: "Time to wait (in seconds) for runner setup to complete before returning"
    required: false
    default: "60"

outputs:
  runner-name:
    description: "Name of the created runner (generated by external workflow)"
    value: ${{ steps.extract-details.outputs.runner_name }}
  machine-ip:
    description: "IP address of the created machine"
    value: ${{ steps.extract-details.outputs.machine_ip }}
  run-id:
    description: "Run ID of the machine creation workflow"
    value: ${{ steps.wait-workflow.outputs.run_id }}

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"

    - name: Install dependencies
      shell: bash
      run: |
        pip install jinja2

    - name: Build base tag and runner label
      env:
        USER_NAME: ${{ inputs.gh-username || github.actor }}
      shell: bash
      run: |
        # Generate BASE_TAG using the first letter of USER_NAME and a random 4-digit number
        BASE_TAG="${USER_NAME:0:1}$(shuf -i 1000-9999 -n 1)"
        echo "BASE_TAG=$BASE_TAG" >> $GITHUB_ENV
        echo "Generated BASE_TAG: $BASE_TAG"

        # Create unique runner label to avoid collisions
        RUNNER_LABEL="${{ inputs.runner-name }}-${USER_NAME}-${BASE_TAG}"
        echo "RUNNER_LABEL=$RUNNER_LABEL" >> $GITHUB_ENV
        echo "Generated RUNNER_LABEL: $RUNNER_LABEL"

    - name: Generate workflow inputs with setup script
      env:
        BASE_TAG: ${{ env.BASE_TAG }}
        GITHUB_USERNAME: ${{ inputs.gh-username }}
        RUNNER_NAME: ${{ inputs.runner-name }}
        RUNNER_TYPE: ${{ inputs.runner-type }}
        RUNNER_LABEL: ${{ env.RUNNER_LABEL }}
        TAGS: ${{ inputs.tags }}
        ALLOWED_IPS: ${{ inputs.allowed-ips }}
        SSH_KEYS: ${{ inputs.ssh-keys }}
        TIMEOUT: ${{ inputs.timeout }}
        GH_TOKEN: ${{ inputs.gh-token }}
        ORG_NAME: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        OUTPUT_FILE: workflow-inputs.json
      shell: bash
      run: |
        echo "Generating workflow inputs with runner setup script..."
        python3 ${{ github.action_path }}/generate_workflow_inputs.py

    - name: Trigger machine creation workflow
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      shell: bash
      run: |
        echo "Triggering machine creation workflow..."
        gh workflow run run-custom-node.yml \
          --repo NethermindEth/post-merge-smoke-tests \
          --ref main \
          --json < workflow-inputs.json

        echo "Workflow triggered successfully"

    - name: Wait for machine creation workflow
      id: wait-workflow
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
        WORKFLOW_ID: "run-custom-node.yml"
        MAX_WAIT_MINUTES: "5"
        INTERVAL: "5"
        TIMEOUT: "20"
        ORG_NAME: "NethermindEth"
        REPO_NAME: "post-merge-smoke-tests"
        NAME_FILTER: ${{ env.BASE_TAG }}
        REF: "main"
      shell: bash
      run: |
        chmod +x ${{ github.workspace }}/scripts/wait-for-workflow.sh
        ${{ github.workspace }}/scripts/wait-for-workflow.sh | tee script-output.txt
        run_id=$(grep -oP 'Run ID: \K\d+' script-output.txt)
        echo "Run ID extracted is: $run_id"
        echo "run_id=$run_id" >> $GITHUB_OUTPUT

    - name: Download machine specs artifact
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      shell: bash
      run: |
        echo "Downloading machine specs artifact..."
        mkdir -p ./downloaded-artifacts

        gh run download "${{ steps.wait-workflow.outputs.run_id }}" \
          --repo NethermindEth/post-merge-smoke-tests \
          --dir ./downloaded-artifacts

        echo "Artifacts downloaded successfully"

    - name: Extract machine details
      id: extract-details
      shell: bash
      run: |
        # Find the machine details file
        DETAILS_DIR="./downloaded-artifacts/machine-details"
        if [ ! -d "$DETAILS_DIR" ]; then
          echo "Error: machine-details directory not found"
          exit 1
        fi

        FILE=$(ls "$DETAILS_DIR" | head -n 1)
        if [ -z "$FILE" ]; then
          echo "Error: Could not find machine details file"
          exit 1
        fi

        DETAILS_FILE="$DETAILS_DIR/$FILE"
        echo "Machine details file: $DETAILS_FILE"

        # Display details in summary
        echo "<details>" >> $GITHUB_STEP_SUMMARY
        echo "<summary>Self-hosted runner machine details</summary>" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        cat "$DETAILS_FILE" >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY

        # Extract details from the artifact
        cat "$DETAILS_FILE" | tee machine-output.txt

        # Extract machine IP (format: "   IP: 123.456.789.012")
        MACHINE_IP=$(grep -oP '^\s+IP:\s+\K[0-9.]+' machine-output.txt | head -n 1 || echo "unknown")
        echo "Machine IP: $MACHINE_IP"
        echo "machine_ip=$MACHINE_IP" >> $GITHUB_OUTPUT

        # Use the runner label we generated (combines input label + username + random number)
        # This is the actual GitHub Actions runner label registered in the setup script
        echo "Runner Label: ${{ env.RUNNER_LABEL }}"
        echo "runner_name=${{ env.RUNNER_LABEL }}" >> $GITHUB_OUTPUT

    - name: Wait for runner setup to complete
      shell: bash
      run: |
        WAIT_TIME="${{ inputs.setup-wait-time }}"
        echo "Waiting ${WAIT_TIME} seconds for runner setup to complete..."
        sleep "${WAIT_TIME}"
        echo "Runner setup wait time completed"

    - name: Display runner information
      shell: bash
      run: |
        echo "### Self-Hosted Runner Created" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Runner Name**: ${{ steps.extract-details.outputs.runner_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Base Tag**: ${{ env.BASE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Machine IP**: ${{ steps.extract-details.outputs.machine_ip }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Timeout**: ${{ inputs.timeout }} hours" >> $GITHUB_STEP_SUMMARY
        echo "- **Run ID**: ${{ steps.wait-workflow.outputs.run_id }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The runner is now available for use in workflows." >> $GITHUB_STEP_SUMMARY
