// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nethermind.JsonRpc.SourceGenerator;

[Generator]
public sealed class RpcJsonTypeInfoGenerator : IIncrementalGenerator
{
    private const string GeneratedSourceHeader = "// <auto-generated/>\n#nullable enable\n";
    private const string JsonRpcNamespace = "Nethermind.JsonRpc";
    private const string JsonRpcModulesNamespace = "Nethermind.JsonRpc.Modules";
    private const string SystemThreadingTasksNamespace = "System.Threading.Tasks";

    private static readonly SymbolDisplayFormat TypeDisplayFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ImmutableArray<string>> methodTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (context, cancellationToken) => GetRpcJsonTypes(context, cancellationToken));

        IncrementalValueProvider<ImmutableArray<ImmutableArray<string>>> collectedTypes = methodTypes.Collect();
        context.RegisterSourceOutput(collectedTypes, static (context, types) => Generate(context, types));
    }

    private static ImmutableArray<string> GetRpcJsonTypes(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        MethodDeclarationSyntax methodDeclaration = (MethodDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(methodDeclaration, cancellationToken) is not IMethodSymbol method ||
            method.IsStatic ||
            method.MethodKind != MethodKind.Ordinary ||
            method.DeclaredAccessibility != Accessibility.Public ||
            !IsRpcModule(method.ContainingType))
        {
            return ImmutableArray<string>.Empty;
        }

        ImmutableArray<string>.Builder types = ImmutableArray.CreateBuilder<string>();
        AddReturnPayloadTypes(method.ReturnType, types);
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            AddJsonType(method.Parameters[i].Type, types);
        }

        return types.ToImmutable();
    }

    private static bool IsRpcModule(INamedTypeSymbol? type)
    {
        if (type is null)
        {
            return false;
        }

        for (int i = 0; i < type.AllInterfaces.Length; i++)
        {
            if (IsNamedType(type.AllInterfaces[i], JsonRpcModulesNamespace, "IRpcModule"))
            {
                return true;
            }
        }

        return IsNamedType(type, JsonRpcModulesNamespace, "IRpcModule");
    }

    private static void AddReturnPayloadTypes(ITypeSymbol returnType, ImmutableArray<string>.Builder types)
    {
        ITypeSymbol resultType = UnwrapTaskLike(returnType);
        if (resultType is not INamedTypeSymbol namedResult || !namedResult.IsGenericType)
        {
            return;
        }

        INamedTypeSymbol resultDefinition = namedResult.ConstructedFrom;
        if (IsNamedType(resultDefinition, JsonRpcNamespace, "ResultWrapper`1"))
        {
            AddJsonType(namedResult.TypeArguments[0], types);
            return;
        }

        if (IsNamedType(resultDefinition, JsonRpcNamespace, "ResultWrapper`2"))
        {
            AddJsonType(namedResult.TypeArguments[0], types);
            AddJsonType(namedResult.TypeArguments[1], types);
        }
    }

    private static ITypeSymbol UnwrapTaskLike(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType &&
            namedType.IsGenericType &&
            (IsNamedType(namedType.ConstructedFrom, SystemThreadingTasksNamespace, "Task`1") ||
             IsNamedType(namedType.ConstructedFrom, SystemThreadingTasksNamespace, "ValueTask`1")))
        {
            return namedType.TypeArguments[0];
        }

        return type;
    }

    private static void AddJsonType(ITypeSymbol type, ImmutableArray<string>.Builder types)
    {
        if (type.TypeKind == TypeKind.TypeParameter || type.SpecialType == SpecialType.System_Void)
        {
            return;
        }

        types.Add(type.ToDisplayString(TypeDisplayFormat));
    }

    private static bool IsNamedType(INamedTypeSymbol type, string namespaceName, string metadataName) =>
        type.ContainingNamespace.ToDisplayString() == namespaceName && type.MetadataName == metadataName;

    private static void Generate(SourceProductionContext context, ImmutableArray<ImmutableArray<string>> typeGroups)
    {
        HashSet<string> uniqueTypes = new(StringComparer.Ordinal);
        for (int i = 0; i < typeGroups.Length; i++)
        {
            ImmutableArray<string> group = typeGroups[i];
            for (int j = 0; j < group.Length; j++)
            {
                uniqueTypes.Add(group[j]);
            }
        }

        if (uniqueTypes.Count == 0)
        {
            return;
        }

        string[] sortedTypes = new string[uniqueTypes.Count];
        uniqueTypes.CopyTo(sortedTypes);
        Array.Sort(sortedTypes, StringComparer.Ordinal);

        StringBuilder builder = new();
        builder.AppendLine(GeneratedSourceHeader);
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Text.Json.Serialization.Metadata;");
        builder.AppendLine("using Nethermind.Serialization.Json;");
        builder.AppendLine();
        builder.AppendLine("namespace Nethermind.JsonRpc;");
        builder.AppendLine();
        builder.AppendLine("internal static partial class GeneratedRpcTypeInfo");
        builder.AppendLine("{");
        builder.AppendLine("    static partial void TryGetCore(Type type, ref JsonTypeInfo? typeInfo)");
        builder.AppendLine("    {");
        for (int i = 0; i < sortedTypes.Length; i++)
        {
            builder.Append("        if (type == typeof(");
            builder.Append(sortedTypes[i]);
            builder.AppendLine("))");
            builder.AppendLine("        {");
            builder.AppendLine("            EthereumJsonSerializer.JsonOptions.TryGetTypeInfo(type, out typeInfo);");
            builder.AppendLine("            return;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("GeneratedRpcJsonContext.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
