// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nethermind.JsonRpc.SourceGenerator;

[Generator]
public sealed class RpcJsonTypeInfoGenerator : IIncrementalGenerator
{
    private const string GeneratedSourceHeader = "// <auto-generated/>\n#nullable enable\n";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ImmutableArray<string>> rpcTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax or InvocationExpressionSyntax,
                transform: static (context, cancellationToken) => RpcJsonTypeDiscovery.GetJsonTypes(context, cancellationToken));

        IncrementalValueProvider<ImmutableArray<ImmutableArray<string>>> collectedTypes = rpcTypes.Collect();
        context.RegisterSourceOutput(collectedTypes, static (context, types) => Generate(context, types));
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<ImmutableArray<string>> typeGroups)
    {
        string[] sortedTypes = RpcJsonTypeDiscovery.GetSortedUniqueTypes(typeGroups);
        if (sortedTypes.Length == 0)
        {
            return;
        }

        StringBuilder builder = new();
        builder.AppendLine(GeneratedSourceHeader);
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using System.Text.Json.Serialization.Metadata;");
        builder.AppendLine("using Nethermind.Serialization.Json;");
        builder.AppendLine();
        builder.AppendLine("namespace Nethermind.JsonRpc;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedRpcJsonTypeInfoProvider");
        builder.AppendLine("{");
        builder.AppendLine("    [ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");
        builder.AppendLine("        RpcGeneratedTypeInfoRegistry.Register(RpcTypes, TryGet);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static readonly Type[] RpcTypes =");
        builder.AppendLine("    {");
        for (int i = 0; i < sortedTypes.Length; i++)
        {
            builder.Append("        typeof(");
            builder.Append(sortedTypes[i]);
            builder.AppendLine("),");
        }
        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    private static JsonTypeInfo? TryGet(Type type)");
        builder.AppendLine("    {");
        builder.AppendLine("        JsonTypeInfo? typeInfo;");
        builder.AppendLine("        EthereumJsonSerializer.JsonOptions.TryGetTypeInfo(type, out typeInfo);");
        builder.AppendLine("        return typeInfo;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("GeneratedRpcJsonTypeInfoProvider.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
