//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Nethermind, Microsoft")]
[assembly: AssemblyProduct("DotNetty")]
[assembly: AssemblyVersion("0.7.6")]
[assembly: AssemblyFileVersion("0.7.6")]
[assembly: AssemblyCopyright("Demerzel Solutions Limited, Microsoft Corporation")]

