name = "ControlFlowOpcodeExtractor"
version = "0.1.0"
defaultTargets = ["ControlFlowOpcodeExtractor.Refinement.ControlFlowOpcode"]

[[lean_lib]]
name = "Eip803x"
srcDir = ".."

[[lean_lib]]
name = "ControlFlowOpcodeExtractor"
srcDir = ".."
