<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../src/Nethermind/tests.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>Nethermind.DocGen.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DocGen/DocGen.csproj" />
  </ItemGroup>

</Project>
