<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\src\Nethermind\tests.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>Nethermind.Bootnode.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Bootnode\Nethermind.Bootnode.csproj" />
  </ItemGroup>

</Project>
