<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Nethermind.Evm.Lean.SystemTransactionRoutingExtractor</AssemblyName>
    <RootNamespace>Nethermind.Evm.Lean.SystemTransactionRoutingExtractor</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <Compile Remove="Test/**/*.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Nethermind.Evm.Lean.SystemTransactionRoutingExtractor.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
