<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../tests.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NUnit1032</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Core.Test\Nethermind.Core.Test.csproj" />
    <ProjectReference Include="..\Nethermind.Eez.Execution\Nethermind.Eez.Execution.csproj" />
    <ProjectReference Include="..\Nethermind.Eez\Nethermind.Eez.csproj" />
    <ProjectReference Include="..\Nethermind.Evm.Test\Nethermind.Evm.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
