<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Nethermind.Torrent</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" />
    <ProjectReference Include="..\..\..\..\src\Nethermind\Nethermind.Kademlia\Nethermind.Kademlia.csproj" />
  </ItemGroup>

</Project>
