<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../tests.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Consensus.Qbft\Nethermind.Consensus.Qbft.csproj" />
    <ProjectReference Include="..\Nethermind.Core.Test\Nethermind.Core.Test.csproj" />
    <ProjectReference Include="..\Nethermind.JsonRpc.Test\Nethermind.JsonRpc.Test.csproj" />
  </ItemGroup>

</Project>
