name = "CallCreateOpcodeExtractor"
version = "0.1.0"
defaultTargets = ["CallCreateOpcodeExtractor.Refinement.CallCreateOpcode"]

[[lean_lib]]
name = "Eip803x"
srcDir = ".."

[[lean_lib]]
name = "CallCreateOpcodeExtractor"
srcDir = ".."
