// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: src/Nethermind/Nethermind.Grpc/Nethermind.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nethermind.Grpc {
  public static partial class NethermindService
  {
    static readonly string __ServiceName = "Nethermind.Grpc.NethermindService";

    static readonly grpc::Marshaller<global::Nethermind.Grpc.QueryRequest> __Marshaller_Nethermind_Grpc_QueryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nethermind.Grpc.QueryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nethermind.Grpc.QueryResponse> __Marshaller_Nethermind_Grpc_QueryResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nethermind.Grpc.QueryResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nethermind.Grpc.SubscriptionRequest> __Marshaller_Nethermind_Grpc_SubscriptionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nethermind.Grpc.SubscriptionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nethermind.Grpc.SubscriptionResponse> __Marshaller_Nethermind_Grpc_SubscriptionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nethermind.Grpc.SubscriptionResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Nethermind.Grpc.QueryRequest, global::Nethermind.Grpc.QueryResponse> __Method_Query = new grpc::Method<global::Nethermind.Grpc.QueryRequest, global::Nethermind.Grpc.QueryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Query",
        __Marshaller_Nethermind_Grpc_QueryRequest,
        __Marshaller_Nethermind_Grpc_QueryResponse);

    static readonly grpc::Method<global::Nethermind.Grpc.SubscriptionRequest, global::Nethermind.Grpc.SubscriptionResponse> __Method_Subscribe = new grpc::Method<global::Nethermind.Grpc.SubscriptionRequest, global::Nethermind.Grpc.SubscriptionResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Subscribe",
        __Marshaller_Nethermind_Grpc_SubscriptionRequest,
        __Marshaller_Nethermind_Grpc_SubscriptionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nethermind.Grpc.NethermindReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NethermindService</summary>
    [grpc::BindServiceMethod(typeof(NethermindService), "BindService")]
    public abstract partial class NethermindServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Nethermind.Grpc.QueryResponse> Query(global::Nethermind.Grpc.QueryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Subscribe(global::Nethermind.Grpc.SubscriptionRequest request, grpc::IServerStreamWriter<global::Nethermind.Grpc.SubscriptionResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NethermindService</summary>
    public partial class NethermindServiceClient : grpc::ClientBase<NethermindServiceClient>
    {
      /// <summary>Creates a new client for NethermindService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NethermindServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NethermindService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NethermindServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NethermindServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NethermindServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Nethermind.Grpc.QueryResponse Query(global::Nethermind.Grpc.QueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Query(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nethermind.Grpc.QueryResponse Query(global::Nethermind.Grpc.QueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Query, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nethermind.Grpc.QueryResponse> QueryAsync(global::Nethermind.Grpc.QueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nethermind.Grpc.QueryResponse> QueryAsync(global::Nethermind.Grpc.QueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Query, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Nethermind.Grpc.SubscriptionResponse> Subscribe(global::Nethermind.Grpc.SubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Subscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Nethermind.Grpc.SubscriptionResponse> Subscribe(global::Nethermind.Grpc.SubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Subscribe, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NethermindServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NethermindServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NethermindServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Query, serviceImpl.Query)
          .AddMethod(__Method_Subscribe, serviceImpl.Subscribe).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NethermindServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Query, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nethermind.Grpc.QueryRequest, global::Nethermind.Grpc.QueryResponse>(serviceImpl.Query));
      serviceBinder.AddMethod(__Method_Subscribe, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Nethermind.Grpc.SubscriptionRequest, global::Nethermind.Grpc.SubscriptionResponse>(serviceImpl.Subscribe));
    }

  }
}
#endregion
