//  Copyright (c) 2021 Demerzel Solutions Limited
//  This file is part of the Nethermind library.
// 
//  The Nethermind library is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
// 
//  The Nethermind library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU Lesser General Public License for more details.
// 
//  You should have received a copy of the GNU Lesser General Public License
//  along with the Nethermind. If not, see <http://www.gnu.org/licenses/>.
// 

using System.ComponentModel;

namespace Nethermind.Consensus.AuRa
{
    public static class Metrics
    {
        [Description("Current AuRa step")]
        public static long AuRaStep { get; set; }

        [Description("Number of reported benign misbehaviour validators")]
        public static long ReportedBenignMisbehaviour { get; set; }
        
        [Description("Number of reported malicious misbehaviour validators")]
        public static long ReportedMaliciousMisbehaviour { get; set; }
        
        [Description("Number of current AuRa validators")]
        public static long ValidatorsCount { get; set; }

        [Description("Number of sealed transactions generated by engine")]
        public static long SealedTransactions { get; set; }

        [Description("RANDAO number of commit hash transactions")]
        public static long CommitHashTransaction { get; set; }

        [Description("RANDAO number of reveal number transactions")]
        public static long RevealNumber { get; set; }

        [Description("POSDAO number of emit init change transactions")]
        public static long EmitInitiateChange { get; set; }
    }
}
