# SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
# SPDX-License-Identifier: LGPL-3.0-only

FROM nethermindeth/bflat-riscv64:20c2f9bb74404b2fba102e179d010886e1a21113

RUN apt-get update && apt-get install -y --no-install-recommends strace gdb file
