# SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
# SPDX-License-Identifier: LGPL-3.0-only

FROM nethermindeth/bflat-riscv64:latest

RUN apt-get update && apt-get install -y --no-install-recommends strace gdb file
