// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nethermind.Analyzers;

/// <summary>Specializes fork algorithm templates into concrete Fulu and Gloas methods.</summary>
/// <remarks>Fork differences are compile-time branches; emitted methods retain concrete state types and calls.</remarks>
[Generator]
public sealed class ForkAlgorithmGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidTemplate = new("NMFORK001", "Invalid fork template",
        "{0}: {1}", "Generation", DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".forks.cs", StringComparison.Ordinal)), static (output, file) =>
        {
            SourceText? text = file.GetText(output.CancellationToken);
            if (text is null) return;
            string name = Path.GetFileName(file.Path).Replace(".forks.cs", "");
            foreach (bool gloas in new[] { false, true })
            {
                CSharpParseOptions options = new(LanguageVersion.Preview,
                    preprocessorSymbols: gloas ? new[] { "GLOAS" } : Array.Empty<string>());
                SyntaxNode root = CSharpSyntaxTree.ParseText(text, options, file.Path, output.CancellationToken).GetRoot(output.CancellationToken);
                bool invalid = false;
                foreach (Diagnostic diagnostic in root.GetDiagnostics())
                {
                    if (diagnostic.Severity != DiagnosticSeverity.Error) continue;
                    output.ReportDiagnostic(Diagnostic.Create(InvalidTemplate, Location.None, file.Path, diagnostic.ToString()));
                    invalid = true;
                }
                if (invalid) continue;
                SyntaxNode specialized = new Specializer(name, gloas).Visit(root)!;
                output.AddSource((gloas ? "Gloas" : "") + name + ".forks.g.cs",
                    SourceText.From("// <auto-generated/>\n#nullable enable\n" + specialized.ToFullString(), Encoding.UTF8));
            }
        });
    }

    private sealed class Specializer(string name, bool gloas) : CSharpSyntaxRewriter
    {
        public override SyntaxTrivia VisitTrivia(SyntaxTrivia trivia) =>
            trivia.IsDirective || trivia.IsKind(SyntaxKind.DisabledTextTrivia) ? default : base.VisitTrivia(trivia);

        public override SyntaxToken VisitToken(SyntaxToken token)
        {
            SyntaxToken visited = base.VisitToken(token);
            if (!token.IsKind(SyntaxKind.IdentifierToken)) return visited;
            string? replacement = token.ValueText switch
            {
                "ForkState" => gloas ? "BeaconStateGloas" : "BeaconStateFulu",
                "ForkBlock" => gloas ? "BeaconBlockGloas" : "BeaconBlock",
                "ForkAttestation" => gloas ? "AttestationGloas" : "Attestation",
                "ForkBody" => gloas ? "BeaconBlockBodyGloas" : "BeaconBlockBody",
                "ForkAttesterSlashing" => gloas ? "AttesterSlashingGloas" : "AttesterSlashing",
                "ForkIndexedAttestation" => gloas ? "IndexedAttestationGloas" : "IndexedAttestation",
                "ForkSignatureSets" => gloas ? "GloasSignatureSets" : "SignatureSets",
                "ForkEpochProcessing" => gloas ? "GloasEpochProcessing" : "EpochProcessing",
                _ when token.Parent is ClassDeclarationSyntax && token.ValueText == name => gloas ? "Gloas" + name : name,
                _ => null,
            };
            return replacement is null ? visited : SyntaxFactory.Identifier(visited.LeadingTrivia, replacement, visited.TrailingTrivia);
        }
    }
}
