# SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
# SPDX-License-Identifier: LGPL-3.0-only
[package]
name = "nethermind-lean"
version = "0.1.0"
edition = "2024"
rust-version = "1.99"
publish = false

[lib]
name = "nethermind_lean"
crate-type = ["cdylib", "rlib"]

[dependencies]
sphincs = { git = "https://github.com/leanEthereum/leanVM", rev = "f33f31bf7c1191667e29a68a3acae63b9164c1c6" }
rec_aggregation = { git = "https://github.com/leanEthereum/leanVM", rev = "f33f31bf7c1191667e29a68a3acae63b9164c1c6" }
lean_vm = { git = "https://github.com/leanEthereum/leanVM", rev = "f33f31bf7c1191667e29a68a3acae63b9164c1c6" }
lean_compiler = { git = "https://github.com/leanEthereum/leanVM", rev = "f33f31bf7c1191667e29a68a3acae63b9164c1c6" }
primitives = { git = "https://github.com/leanEthereum/leanVM", rev = "f33f31bf7c1191667e29a68a3acae63b9164c1c6" }
parallel = { git = "https://github.com/leanEthereum/leanVM", rev = "f33f31bf7c1191667e29a68a3acae63b9164c1c6" }
bincode = "1.3"
tiny-keccak = { version = "2.0", features = ["keccak"] }

[profile.release]
opt-level = 3

[[example]]
name = "lean_startup_stub"
crate-type = ["cdylib"]
test = false
