<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nethermind.Core.Test" />
    <InternalsVisibleTo Include="Nethermind.Trie" />
    <InternalsVisibleTo Include="Nethermind.Merge.Plugin" />
    <InternalsVisibleTo Include="Nethermind.Stateless.Executor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.Core\Nethermind.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ckzg.Bindings" />
    <PackageReference Include="Nethermind.DotNetty.Buffers" />
  </ItemGroup>

</Project>
