//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DslGrammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class DslGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOOLEAN_OPERATOR=1, ARITHMETIC_SYMBOL=2, SOURCE=3, WATCH=4, WHERE=5, PUBLISH=6, 
		AND=7, OR=8, CONTAINS=9, IS=10, NOT=11, PUBLISH_VALUE=12, WEBSOCKETS=13, 
		TELEGRAM=14, DISCORD=15, SLACK=16, WORD=17, DIGIT=18, BYTECODE=19, ADDRESS=20, 
		URL=21, WS=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"BOOLEAN_OPERATOR", "ARITHMETIC_SYMBOL", "SOURCE", "WATCH", "WHERE", "PUBLISH", 
		"AND", "OR", "CONTAINS", "IS", "NOT", "PUBLISH_VALUE", "WEBSOCKETS", "TELEGRAM", 
		"DISCORD", "SLACK", "WORD", "DIGIT", "BYTECODE", "ADDRESS", "URL", "WS"
	};


	public DslGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public DslGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "'SOURCE'", "'WATCH'", "'WHERE'", "'PUBLISH'", "'AND'", 
		"'OR'", "'CONTAINS'", "'IS'", "'NOT'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOOLEAN_OPERATOR", "ARITHMETIC_SYMBOL", "SOURCE", "WATCH", "WHERE", 
		"PUBLISH", "AND", "OR", "CONTAINS", "IS", "NOT", "PUBLISH_VALUE", "WEBSOCKETS", 
		"TELEGRAM", "DISCORD", "SLACK", "WORD", "DIGIT", "BYTECODE", "ADDRESS", 
		"URL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DslGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DslGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\xFA', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x5', '\x2', '\x32', '\n', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', 
		'?', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x5', '\r', 'w', '\n', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', 
		'\xA1', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', '\xB3', '\n', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', 
		'\xC3', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x5', '\x11', '\xCF', '\n', '\x11', '\x3', '\x12', 
		'\x6', '\x12', '\xD2', '\n', '\x12', '\r', '\x12', '\xE', '\x12', '\xD3', 
		'\x3', '\x13', '\x6', '\x13', '\xD7', '\n', '\x13', '\r', '\x13', '\xE', 
		'\x13', '\xD8', '\x3', '\x14', '\x6', '\x14', '\xDC', '\n', '\x14', '\r', 
		'\x14', '\xE', '\x14', '\xDD', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\a', '\x15', '\xE4', '\n', '\x15', '\f', '\x15', '\xE', 
		'\x15', '\xE7', '\v', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x6', '\x16', 
		'\xF0', '\n', '\x16', '\r', '\x16', '\xE', '\x16', '\xF1', '\x3', '\x17', 
		'\x6', '\x17', '\xF5', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xF6', 
		'\x3', '\x17', '\x3', '\x17', '\x2', '\x2', '\x18', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', 
		'%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '\x3', 
		'\x2', '\a', '\x4', '\x2', '>', '>', '@', '@', '\x4', '\x2', '\x43', '\\', 
		'\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x32', ';', '\x43', 
		'H', '\x63', 'h', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', '\x10F', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x3', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '>', '\x3', '\x2', '\x2', '\x2', '\a', '@', 
		'\x3', '\x2', '\x2', '\x2', '\t', 'G', '\x3', '\x2', '\x2', '\x2', '\v', 
		'M', '\x3', '\x2', '\x2', '\x2', '\r', 'S', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '[', '\x3', '\x2', '\x2', '\x2', '\x11', '_', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x62', '\x3', '\x2', '\x2', '\x2', '\x15', 'k', '\x3', 
		'\x2', '\x2', '\x2', '\x17', 'n', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'v', '\x3', '\x2', '\x2', '\x2', '\x1B', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\xB2', '\x3', '\x2', '\x2', '\x2', '\x1F', '\xC2', '\x3', 
		'\x2', '\x2', '\x2', '!', '\xCE', '\x3', '\x2', '\x2', '\x2', '#', '\xD1', 
		'\x3', '\x2', '\x2', '\x2', '%', '\xD6', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\xDB', '\x3', '\x2', '\x2', '\x2', ')', '\xDF', '\x3', '\x2', '\x2', 
		'\x2', '+', '\xE8', '\x3', '\x2', '\x2', '\x2', '-', '\xF4', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x32', '\x5', '\x5', '\x3', '\x2', '\x30', '\x32', 
		'\x5', '\x13', '\n', '\x2', '\x31', '/', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x32', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x34', '\a', '?', '\x2', '\x2', '\x34', '?', '\a', '?', 
		'\x2', '\x2', '\x35', '\x36', '\a', '#', '\x2', '\x2', '\x36', '?', '\a', 
		'?', '\x2', '\x2', '\x37', '?', '\t', '\x2', '\x2', '\x2', '\x38', '\x39', 
		'\a', '>', '\x2', '\x2', '\x39', '?', '\a', '?', '\x2', '\x2', ':', ';', 
		'\a', '@', '\x2', '\x2', ';', '?', '\a', '?', '\x2', '\x2', '<', '?', 
		'\x5', '\x15', '\v', '\x2', '=', '?', '\x5', '\x17', '\f', '\x2', '>', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '>', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '>', '\x37', '\x3', '\x2', '\x2', '\x2', '>', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '>', ':', '\x3', '\x2', '\x2', '\x2', '>', '<', '\x3', '\x2', 
		'\x2', '\x2', '>', '=', '\x3', '\x2', '\x2', '\x2', '?', '\x6', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x41', '\a', 'U', '\x2', '\x2', '\x41', '\x42', 
		'\a', 'Q', '\x2', '\x2', '\x42', '\x43', '\a', 'W', '\x2', '\x2', '\x43', 
		'\x44', '\a', 'T', '\x2', '\x2', '\x44', '\x45', '\a', '\x45', '\x2', 
		'\x2', '\x45', '\x46', '\a', 'G', '\x2', '\x2', '\x46', '\b', '\x3', '\x2', 
		'\x2', '\x2', 'G', 'H', '\a', 'Y', '\x2', '\x2', 'H', 'I', '\a', '\x43', 
		'\x2', '\x2', 'I', 'J', '\a', 'V', '\x2', '\x2', 'J', 'K', '\a', '\x45', 
		'\x2', '\x2', 'K', 'L', '\a', 'J', '\x2', '\x2', 'L', '\n', '\x3', '\x2', 
		'\x2', '\x2', 'M', 'N', '\a', 'Y', '\x2', '\x2', 'N', 'O', '\a', 'J', 
		'\x2', '\x2', 'O', 'P', '\a', 'G', '\x2', '\x2', 'P', 'Q', '\a', 'T', 
		'\x2', '\x2', 'Q', 'R', '\a', 'G', '\x2', '\x2', 'R', '\f', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'T', '\a', 'R', '\x2', '\x2', 'T', 'U', '\a', 'W', 
		'\x2', '\x2', 'U', 'V', '\a', '\x44', '\x2', '\x2', 'V', 'W', '\a', 'N', 
		'\x2', '\x2', 'W', 'X', '\a', 'K', '\x2', '\x2', 'X', 'Y', '\a', 'U', 
		'\x2', '\x2', 'Y', 'Z', '\a', 'J', '\x2', '\x2', 'Z', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '[', '\\', '\a', '\x43', '\x2', '\x2', '\\', ']', '\a', 
		'P', '\x2', '\x2', ']', '^', '\a', '\x46', '\x2', '\x2', '^', '\x10', 
		'\x3', '\x2', '\x2', '\x2', '_', '`', '\a', 'Q', '\x2', '\x2', '`', '\x61', 
		'\a', 'T', '\x2', '\x2', '\x61', '\x12', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\a', '\x45', '\x2', '\x2', '\x63', '\x64', '\a', 'Q', '\x2', 
		'\x2', '\x64', '\x65', '\a', 'P', '\x2', '\x2', '\x65', '\x66', '\a', 
		'V', '\x2', '\x2', '\x66', 'g', '\a', '\x43', '\x2', '\x2', 'g', 'h', 
		'\a', 'K', '\x2', '\x2', 'h', 'i', '\a', 'P', '\x2', '\x2', 'i', 'j', 
		'\a', 'U', '\x2', '\x2', 'j', '\x14', '\x3', '\x2', '\x2', '\x2', 'k', 
		'l', '\a', 'K', '\x2', '\x2', 'l', 'm', '\a', 'U', '\x2', '\x2', 'm', 
		'\x16', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\a', 'P', '\x2', '\x2', 
		'o', 'p', '\a', 'Q', '\x2', '\x2', 'p', 'q', '\a', 'V', '\x2', '\x2', 
		'q', '\x18', '\x3', '\x2', '\x2', '\x2', 'r', 'w', '\x5', '\x1B', '\xE', 
		'\x2', 's', 'w', '\x5', '\x1D', '\xF', '\x2', 't', 'w', '\x5', '\x1F', 
		'\x10', '\x2', 'u', 'w', '\x5', '!', '\x11', '\x2', 'v', 'r', '\x3', '\x2', 
		'\x2', '\x2', 'v', 's', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', 
		'\x2', '\x2', 'v', 'u', '\x3', '\x2', '\x2', '\x2', 'w', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'y', '\a', 'Y', '\x2', '\x2', 'y', 'z', '\a', 
		'g', '\x2', '\x2', 'z', '{', '\a', '\x64', '\x2', '\x2', '{', '|', '\a', 
		'U', '\x2', '\x2', '|', '}', '\a', 'q', '\x2', '\x2', '}', '~', '\a', 
		'\x65', '\x2', '\x2', '~', '\x7F', '\a', 'm', '\x2', '\x2', '\x7F', '\x80', 
		'\a', 'g', '\x2', '\x2', '\x80', '\x81', '\a', 'v', '\x2', '\x2', '\x81', 
		'\xA1', '\a', 'u', '\x2', '\x2', '\x82', '\x83', '\a', 'y', '\x2', '\x2', 
		'\x83', '\x84', '\a', 'g', '\x2', '\x2', '\x84', '\x85', '\a', '\x64', 
		'\x2', '\x2', '\x85', '\x86', '\a', 'U', '\x2', '\x2', '\x86', '\x87', 
		'\a', 'q', '\x2', '\x2', '\x87', '\x88', '\a', '\x65', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'm', '\x2', '\x2', '\x89', '\x8A', '\a', 'g', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', 'v', '\x2', '\x2', '\x8B', '\xA1', '\a', 'u', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', 'y', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'g', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x64', '\x2', '\x2', '\x8F', 
		'\x90', '\a', 'u', '\x2', '\x2', '\x90', '\x91', '\a', 'q', '\x2', '\x2', 
		'\x91', '\x92', '\a', '\x65', '\x2', '\x2', '\x92', '\x93', '\a', 'm', 
		'\x2', '\x2', '\x93', '\x94', '\a', 'g', '\x2', '\x2', '\x94', '\x95', 
		'\a', 'v', '\x2', '\x2', '\x95', '\xA1', '\a', 'u', '\x2', '\x2', '\x96', 
		'\x97', '\a', 'Y', '\x2', '\x2', '\x97', '\x98', '\a', 'g', '\x2', '\x2', 
		'\x98', '\x99', '\a', '\x64', '\x2', '\x2', '\x99', '\x9A', '\a', 'u', 
		'\x2', '\x2', '\x9A', '\x9B', '\a', 'q', '\x2', '\x2', '\x9B', '\x9C', 
		'\a', '\x65', '\x2', '\x2', '\x9C', '\x9D', '\a', 'm', '\x2', '\x2', '\x9D', 
		'\x9E', '\a', 'g', '\x2', '\x2', '\x9E', '\x9F', '\a', 'v', '\x2', '\x2', 
		'\x9F', '\xA1', '\a', 'u', '\x2', '\x2', '\xA0', 'x', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\x82', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\x96', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', 'V', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', 'g', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'n', '\x2', '\x2', '\xA5', '\xA6', '\a', 'g', '\x2', '\x2', '\xA6', '\xA7', 
		'\a', 'i', '\x2', '\x2', '\xA7', '\xA8', '\a', 't', '\x2', '\x2', '\xA8', 
		'\xA9', '\a', '\x63', '\x2', '\x2', '\xA9', '\xB3', '\a', 'o', '\x2', 
		'\x2', '\xAA', '\xAB', '\a', 'v', '\x2', '\x2', '\xAB', '\xAC', '\a', 
		'g', '\x2', '\x2', '\xAC', '\xAD', '\a', 'n', '\x2', '\x2', '\xAD', '\xAE', 
		'\a', 'g', '\x2', '\x2', '\xAE', '\xAF', '\a', 'i', '\x2', '\x2', '\xAF', 
		'\xB0', '\a', 't', '\x2', '\x2', '\xB0', '\xB1', '\a', '\x63', '\x2', 
		'\x2', '\xB1', '\xB3', '\a', 'o', '\x2', '\x2', '\xB2', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', '\x46', '\x2', 
		'\x2', '\xB5', '\xB6', '\a', 'k', '\x2', '\x2', '\xB6', '\xB7', '\a', 
		'u', '\x2', '\x2', '\xB7', '\xB8', '\a', '\x65', '\x2', '\x2', '\xB8', 
		'\xB9', '\a', 'q', '\x2', '\x2', '\xB9', '\xBA', '\a', 't', '\x2', '\x2', 
		'\xBA', '\xC3', '\a', '\x66', '\x2', '\x2', '\xBB', '\xBC', '\a', '\x66', 
		'\x2', '\x2', '\xBC', '\xBD', '\a', 'k', '\x2', '\x2', '\xBD', '\xBE', 
		'\a', 'u', '\x2', '\x2', '\xBE', '\xBF', '\a', '\x65', '\x2', '\x2', '\xBF', 
		'\xC0', '\a', 'q', '\x2', '\x2', '\xC0', '\xC1', '\a', 't', '\x2', '\x2', 
		'\xC1', '\xC3', '\a', '\x66', '\x2', '\x2', '\xC2', '\xB4', '\x3', '\x2', 
		'\x2', '\x2', '\xC2', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xC3', ' ', 
		'\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\a', 'U', '\x2', '\x2', '\xC5', 
		'\xC6', '\a', 'n', '\x2', '\x2', '\xC6', '\xC7', '\a', '\x63', '\x2', 
		'\x2', '\xC7', '\xC8', '\a', '\x65', '\x2', '\x2', '\xC8', '\xCF', '\a', 
		'm', '\x2', '\x2', '\xC9', '\xCA', '\a', 'u', '\x2', '\x2', '\xCA', '\xCB', 
		'\a', 'n', '\x2', '\x2', '\xCB', '\xCC', '\a', '\x63', '\x2', '\x2', '\xCC', 
		'\xCD', '\a', '\x65', '\x2', '\x2', '\xCD', '\xCF', '\a', 'm', '\x2', 
		'\x2', '\xCE', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xC9', '\x3', 
		'\x2', '\x2', '\x2', '\xCF', '\"', '\x3', '\x2', '\x2', '\x2', '\xD0', 
		'\xD2', '\t', '\x3', '\x2', '\x2', '\xD1', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		'$', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD7', '\t', '\x4', '\x2', '\x2', 
		'\xD6', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '\xD8', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', 
		'\x3', '\x2', '\x2', '\x2', '\xD9', '&', '\x3', '\x2', '\x2', '\x2', '\xDA', 
		'\xDC', '\t', '\x5', '\x2', '\x2', '\xDB', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDB', '\x3', 
		'\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE0', '\a', '\x32', '\x2', 
		'\x2', '\xE0', '\xE1', '\a', 'z', '\x2', '\x2', '\xE1', '\xE5', '\x3', 
		'\x2', '\x2', '\x2', '\xE2', '\xE4', '\t', '\x5', '\x2', '\x2', '\xE3', 
		'\xE2', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE7', '\x3', '\x2', '\x2', 
		'\x2', '\xE5', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE6', '\x3', 
		'\x2', '\x2', '\x2', '\xE6', '*', '\x3', '\x2', '\x2', '\x2', '\xE7', 
		'\xE5', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\a', 'j', '\x2', 
		'\x2', '\xE9', '\xEA', '\a', 'v', '\x2', '\x2', '\xEA', '\xEB', '\a', 
		'v', '\x2', '\x2', '\xEB', '\xEC', '\a', 'r', '\x2', '\x2', '\xEC', '\xED', 
		'\a', 'u', '\x2', '\x2', '\xED', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xEE', 
		'\xF0', '\v', '\x2', '\x2', '\x2', '\xEF', '\xEE', '\x3', '\x2', '\x2', 
		'\x2', '\xF0', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xEF', '\x3', 
		'\x2', '\x2', '\x2', '\xF1', '\xF2', '\x3', '\x2', '\x2', '\x2', '\xF2', 
		',', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF5', '\t', '\x6', '\x2', '\x2', 
		'\xF4', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF6', '\x3', '\x2', 
		'\x2', '\x2', '\xF6', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', 
		'\x3', '\x2', '\x2', '\x2', '\xF7', '\xF8', '\x3', '\x2', '\x2', '\x2', 
		'\xF8', '\xF9', '\b', '\x17', '\x2', '\x2', '\xF9', '.', '\x3', '\x2', 
		'\x2', '\x2', '\x10', '\x2', '\x31', '>', 'v', '\xA0', '\xB2', '\xC2', 
		'\xCE', '\xD3', '\xD8', '\xDD', '\xE5', '\xF1', '\xF6', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
