// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using NUnit.Framework;

namespace Nethermind.Evm.Lean.AuthorizationStateGasFoldExtractor.Test;

[TestFixture]
public sealed class ExtractorTests
{
    [Test]
    public void Production_sources_extract_deterministically()
    {
        string root = FindRepoRoot();
        using TemporaryDirectory first = new();
        using TemporaryDirectory second = new();
        ExtractionResult firstResult = Extractor.Extract(root, first.Path, Path.Combine(first.Path, "fold.lean"));
        ExtractionResult secondResult = Extractor.Extract(root, second.Path, Path.Combine(second.Path, "fold.lean"));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(firstResult.SourceCount, Is.EqualTo(4));
            Assert.That(File.ReadAllBytes(firstResult.IrPath), Is.EqualTo(File.ReadAllBytes(secondResult.IrPath)));
            Assert.That(File.ReadAllBytes(firstResult.ManifestPath), Is.EqualTo(File.ReadAllBytes(secondResult.ManifestPath)));
            Assert.That(File.ReadAllBytes(firstResult.LeanPath), Is.EqualTo(File.ReadAllBytes(secondResult.LeanPath)));
        }
    }

    [Test]
    public void Checked_artifacts_match_fresh_extraction()
    {
        string root = FindRepoRoot();
        using TemporaryDirectory output = new();
        ExtractionResult result = Extractor.Extract(root, output.Path, Path.Combine(output.Path, "fold.lean"));
        string checkedPath = Path.Combine(root, "tools/Evm/Lean/AuthorizationStateGasFoldExtractor/Generated");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(File.ReadAllBytes(result.IrPath), Is.EqualTo(File.ReadAllBytes(Path.Combine(checkedPath, "AuthorizationStateGasFold.ir.json"))));
            Assert.That(File.ReadAllBytes(result.ManifestPath), Is.EqualTo(File.ReadAllBytes(Path.Combine(checkedPath, "AuthorizationStateGasFold.source-manifest.json"))));
            Assert.That(File.ReadAllBytes(result.LeanPath), Is.EqualTo(File.ReadAllBytes(Path.Combine(checkedPath, "AuthorizationStateGasFold.lean"))));
        }
    }

    [Test]
    public void Generated_Lean_is_theorem_free_and_exposes_the_five_field_fold()
    {
        string root = FindRepoRoot();
        string generated = File.ReadAllText(Path.Combine(root, "tools/Evm/Lean/AuthorizationStateGasFoldExtractor/Generated/AuthorizationStateGasFold.lean"));
        string ir = File.ReadAllText(Path.Combine(root, "tools/Evm/Lean/AuthorizationStateGasFoldExtractor/Generated/AuthorizationStateGasFold.ir.json"));
        string extractorVersion = JsonNode.Parse(ir)!["extractorVersion"]!.GetValue<string>();

        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.StartWith($"-- Generated by AuthorizationStateGasFoldExtractor {extractorVersion}."));
            Assert.That(generated, Does.Not.Contain("theorem "));
            Assert.That(generated, Does.Not.Contain("eip8038"));
            Assert.That(generated, Does.Contain("def foldTopFrameStateGas"));
            Assert.That(generated, Does.Contain("def stateChargeSpill"));
            Assert.That(generated, Does.Contain(
                "if available.value < amount then none else some { available with value := available.value - amount }"));
            Assert.That(generated, Does.Contain("def callerVisible"));
            Assert.That(generated, Does.Contain("stateGasSpillRefunded"));
            Assert.That(generated, Does.Contain("logicalAccountExists : Bool"));
            Assert.That(generated, Does.Not.Contain("\n  accountExists : Bool"));
            Assert.That(ir, Does.Contain("externalObligations"));
            Assert.That(ir, Does.Contain("stateChargeAdapter"));
            Assert.That(ir, Does.Contain("ConsumeRaw(refgas,gasCost)"));
            Assert.That(ir, Does.Contain("complete production authorization loop"));
        }
    }

    [Test]
    public void Serialized_ir_rejects_unknown_root_property()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        candidate["unexpected"] = JsonValue.Create(true);
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_unknown_nested_property()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        candidate["fold"]!.AsObject()["unexpected"] = JsonValue.Create(true);
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_case_mutation()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        JsonNode value = candidate["kernel"]!.DeepClone();
        candidate.Remove("kernel");
        candidate["Kernel"] = value;
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_duplicate_property()
    {
        byte[] source = ReadCheckedIr();
        byte[] candidate = DuplicateSchemaVersion(source);
        AssertIrRejected(source, candidate);
    }

    [Test]
    public void Serialized_ir_rejects_null_nested_shape()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        candidate["delegations"] = null;
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_fold_field_mutation()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        JsonArray writes = candidate["fold"]!.AsObject()["writes"]!.AsArray();
        writes[0]!.AsObject()["field"] = "stateGasUsed";
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_gas_policy_field_set_mutation()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        JsonArray fields = candidate["fold"]!.AsObject()["gasPolicyFields"]!.AsArray();
        fields[0] = "StateReservoir";
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_charge_order_mutation()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        JsonArray charges = candidate["delegations"]!.AsObject()["charges"]!.AsArray();
        JsonNode first = charges[0]!.DeepClone();
        charges[0] = charges[1]!.DeepClone();
        charges[1] = first;
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_delta_polarity_mutation()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        candidate["delegations"]!.AsObject()["delta"]!.AsObject()["operator"] = "+";
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_ir_rejects_dependency_hash_mutation()
    {
        byte[] source = ReadCheckedIr();
        JsonObject candidate = ParseObject(source);
        candidate["dependencies"]!.AsArray()[0]!.AsObject()["leanSha256"] = new string('0', 64);
        AssertIrRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_manifest_rejects_unknown_property()
    {
        byte[] source = ReadCheckedManifest();
        JsonObject candidate = ParseObject(source);
        candidate["unexpected"] = JsonValue.Create(true);
        AssertManifestRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_manifest_rejects_source_hash_mutation()
    {
        byte[] source = ReadCheckedManifest();
        JsonObject candidate = ParseObject(source);
        candidate["sources"]!.AsArray()[0]!.AsObject()["sha256"] = new string('0', 64);
        AssertManifestRejected(source, Serialize(candidate));
    }

    [Test]
    public void Serialized_manifest_rejects_duplicate_property()
    {
        byte[] source = ReadCheckedManifest();
        byte[] candidate = DuplicateSchemaVersion(source);
        AssertManifestRejected(source, candidate);
    }

    [Test]
    public void Fold_field_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace("baseline.StateGasUsed += stateGasUsed;", "baseline.StateReservoir += stateGasUsed;", StringComparison.Ordinal));

    [Test]
    public void Fold_polarity_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace("if (stateGasUsed <= 0)", "if (stateGasUsed >= 0)", StringComparison.Ordinal));

    [Test]
    public void Fold_argument_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("ref gasAvailable, ref executionIntrinsicGasStandard", "ref executionIntrinsicGasStandard, ref executionIntrinsicGasStandard", StringComparison.Ordinal));

    [Test]
    public void Fold_baseline_initialization_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "TGasPolicy executionIntrinsicGasStandard = intrinsicGas.Standard;",
                "TGasPolicy executionIntrinsicGasStandard = gasAvailable;",
                StringComparison.Ordinal));

    [Test]
    public void Initial_intrinsic_authorization_cost_polarity_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.IntrinsicGasCalculatorPath,
            text => text.Replace(
                "return spec.IsEip8037Enabled",
                "return !spec.IsEip8037Enabled",
                StringComparison.Ordinal));

    [Test]
    public void Authorization_list_error_helper_shape_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.IntrinsicGasCalculatorPath,
            text => text.Replace(
                "static void ThrowAuthorizationListNotEnabled(IReleaseSpec releaseSpec) =>",
                "static int ThrowAuthorizationListNotEnabled(IReleaseSpec releaseSpec) =>",
                StringComparison.Ordinal));

    [Test]
    public void Initial_intrinsic_state_projection_polarity_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath, InvertInitialIntrinsicStateProjection);

    [Test]
    public void Initial_intrinsic_state_cost_overwrite_fails_closed(
        [Values("totalStateCost = 1;", "totalStateCost++;", "Mutate(ref totalStateCost);", "authStateCost = 1;")]
        string mutation) =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "long totalStateCost = authStateCost;",
                mutation.StartsWith("authStateCost", StringComparison.Ordinal)
                    ? $"{mutation} long totalStateCost = authStateCost;"
                    : $"long totalStateCost = authStateCost; {mutation}",
                StringComparison.Ordinal));

    [Test]
    public void Process_call_reordering_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath, MovePrePreparationAfterProcessCall);

    [Test]
    public void Process_call_argument_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "ProcessDelegations(tx, spec, accessTracker, ref gasAvailable, ref executionIntrinsicGasStandard, out delegationRefunds)",
                "ProcessDelegations(tx, spec, accessTracker, ref executionIntrinsicGasStandard, ref executionIntrinsicGasStandard, out delegationRefunds)",
                StringComparison.Ordinal));

    [Test]
    public void Execute_available_gas_call_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "CalculateAvailableGas(tx, spec, in intrinsicGas, out TGasPolicy gasAvailable)",
                "CalculateAvailableGas(tx, spec, in intrinsicGas, out TGasPolicy changedAvailable)",
                StringComparison.Ordinal));

    [Test]
    public void Calculate_available_gas_forwarding_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "TGasPolicy.TryCreateAvailableFromIntrinsic(tx.GasLimit, intrinsicGas.Standard, spec, out gasAvailable)",
                "TGasPolicy.TryCreateAvailableFromIntrinsic(tx.GasLimit, intrinsicGas.FloorGas, spec, out gasAvailable)",
                StringComparison.Ordinal));

    [Test]
    public void Available_gas_initializer_failure_outcome_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "available = default;\n            return false;",
                "available = default;\n            return true;",
                StringComparison.Ordinal)
                .Replace(
                    "available = default;\r\n            return false;",
                    "available = default;\r\n            return true;",
                    StringComparison.Ordinal));

    [Test]
    public void Available_gas_initializer_projection_order_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath, SwapAvailableGasSpillProjections);

    [Test]
    public void Standard_processor_available_gas_override_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath, AddStandardAvailableGasOverride);

    [Test]
    public void Process_guard_polarity_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("if (spec.IsEip7702Enabled && tx.HasAuthorizationList)", "if (!spec.IsEip7702Enabled && tx.HasAuthorizationList)", StringComparison.Ordinal));

    [Test]
    public void Caller_reset_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "if (topFrameOutOfGas && spec.IsEip8037Enabled)",
                "if (topFrameOutOfGas || spec.IsEip8037Enabled)",
                StringComparison.Ordinal));

    [Test]
    public void Caller_reset_extra_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "if (topFrameOutOfGas && spec.IsEip8037Enabled)",
                "if (false) if (topFrameOutOfGas && spec.IsEip8037Enabled)",
                StringComparison.Ordinal));

    [Test]
    public void Caller_restore_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("if (hasPreExecutionSnapshot)", "if (!hasPreExecutionSnapshot)", StringComparison.Ordinal));

    [Test]
    public void Caller_failure_detached_from_process_failure_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "if (!ProcessDelegations(tx, spec, accessTracker, ref gasAvailable, ref executionIntrinsicGasStandard, out delegationRefunds))",
                "bool processSucceeded = ProcessDelegations(tx, spec, accessTracker, ref gasAvailable, ref executionIntrinsicGasStandard, out delegationRefunds);\n                if (!processSucceeded)",
                StringComparison.Ordinal));

    [Test]
    public void Caller_failure_arm_swap_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath, SwapTopFrameFailureArms);

    [Test]
    public void Caller_resets_nested_under_restore_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath, MoveResetsInsideRestoreGuard);

    [Test]
    public void Caller_snapshot_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "if (spec.IsEip8037Enabled)\r\n                {\r\n                    preExecutionSnapshot = WorldState.TakeSnapshot();",
                "if (!spec.IsEip8037Enabled)\r\n                {\r\n                    preExecutionSnapshot = WorldState.TakeSnapshot();",
                StringComparison.Ordinal)
                .Replace(
                    "if (spec.IsEip8037Enabled)\n                {\n                    preExecutionSnapshot = WorldState.TakeSnapshot();",
                    "if (!spec.IsEip8037Enabled)\n                {\n                    preExecutionSnapshot = WorldState.TakeSnapshot();",
                    StringComparison.Ordinal));

    [Test]
    public void Caller_snapshot_extra_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath, NestSnapshotAssignmentsUnderExtraGuard);

    [Test]
    public void Mainnet_processor_registration_nested_under_conditional_fails_closed() =>
        AssertSourceMutationRejected(Extractor.MainnetDiPath, NestRegistrationUnderConditional);

    [Test]
    public void Mainnet_processor_registration_signature_mutation_fails_closed(
        [Values(
            ".AddScoped<ITransactionProcessor, ChangedTransactionProcessor>()",
            ".AddScoped<ITransactionProcessor, EthereumTransactionProcessor>(static _ => null!)")]
        string replacement) =>
        AssertSourceMutationRejected(Extractor.MainnetDiPath,
            text => text.Replace(
                ".AddScoped<ITransactionProcessor, EthereumTransactionProcessor>()",
                replacement,
                StringComparison.Ordinal));

    [Test]
    public void Mainnet_competing_processor_registration_fails_closed(
        [Values(
            ".AddScoped<ITransactionProcessor, ChangedTransactionProcessor>()",
            ".AddScoped<ITransactionProcessor>(static _ => null!)",
            ".AddSingleton<ITransactionProcessor>(static _ => null!)",
            ".Bind<ITransactionProcessor, ChangedTransactionProcessor>()",
            ".AddScoped<global::Nethermind.Evm.TransactionProcessing.ITransactionProcessor>(static _ => null!)",
            ".Register(static _ => (ITransactionProcessor)null!).As<ITransactionProcessor>()",
            ".Register(static _ => (ITransactionProcessor)null!).As(typeof(ITransactionProcessor))")]
        string competingRegistration) =>
        AssertSourceMutationRejected(Extractor.MainnetDiPath,
            text => text.Replace(
                ".AddScoped<ITransactionProcessor, EthereumTransactionProcessor>()",
                $".AddScoped<ITransactionProcessor, EthereumTransactionProcessor>(){competingRegistration}",
                StringComparison.Ordinal));

    [Test]
    public void Authorization_delta_polarity_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("GetStateGasUsed(in gasAvailable) - preAuthorizationStateGasUsed", "GetStateGasUsed(in gasAvailable) + preAuthorizationStateGasUsed", StringComparison.Ordinal));

    [Test]
    public void Authorization_delta_getter_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "public static long GetStateGasUsed(in EthereumGasPolicy gas) => gas.StateGasUsed;",
                "public static long GetStateGasUsed(in EthereumGasPolicy gas) => gas.StateReservoir;",
                StringComparison.Ordinal));

    [Test]
    public void Authorization_charge_cost_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("TGasPolicy.GetNewAccountStateCost())", "TGasPolicy.GetPerAuthBaseStateCost())", StringComparison.Ordinal));

    [Test]
    public void Authorization_new_account_charge_physical_existence_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("if (!logicalAccountExists && !TGasPolicy.TryConsumeStateGas", "if (!physicalAccountExists && !TGasPolicy.TryConsumeStateGas", StringComparison.Ordinal));

    [Test]
    public void Authorization_logical_existence_source_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("logicalAccountExists = !WorldState.IsDeadAccount(authority);", "logicalAccountExists = WorldState.AccountExists(authority);", StringComparison.Ordinal));

    [Test]
    public void Authorization_physical_mutation_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("if (!physicalAccountExists)", "if (!logicalAccountExists)", StringComparison.Ordinal));

    [Test]
    public void Authorization_charge_failure_side_effect_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace(
                "{\n                            return false;\n                        }",
                "{\n                            codeInsertRefunds++;\n                            return false;\n                        }",
                StringComparison.Ordinal)
                .Replace(
                    "{\r\n                            return false;\r\n                        }",
                    "{\r\n                            codeInsertRefunds++;\r\n                            return false;\r\n                        }",
                    StringComparison.Ordinal));

    [Test]
    public void Authorization_first_write_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("if (writtenAccounts!.Add(authority))", "if (!writtenAccounts!.Add(authority))", StringComparison.Ordinal));

    [Test]
    public void Authorization_non_clear_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.TransactionProcessorPath,
            text => text.Replace("if (!clearsDelegation)", "if (clearsDelegation)", StringComparison.Ordinal));

    [Test]
    public void Intrinsic_zero_state_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.IntrinsicGasCalculatorPath,
            text => text.Replace("(authCount * perAuthExecution, 0)", "(authCount * perAuthExecution, 1)", StringComparison.Ordinal));

    [Test]
    public void Initial_projection_field_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace("StateGasUsed = totalStateCost", "StateGasUsed = 0", StringComparison.Ordinal));

    [Test]
    public void UpdateGas_guard_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace("GetRemainingGas(in gas) < gasCost", "GetRemainingGas(in gas) >= gasCost", StringComparison.Ordinal));

    [Test]
    public void UpdateGas_failure_value_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace("gas.Value = 0;\n            return false;", "gas.Value = gasCost;\n            return false;", StringComparison.Ordinal));

    [Test]
    public void UpdateGas_success_call_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace("ConsumeRaw(ref gas, gasCost);\n        return true;", "ConsumeRaw(ref gas, 0);\n        return true;", StringComparison.Ordinal));

    [Test]
    public void UpdateGas_remaining_gas_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "public static ulong GetRemainingGas(in EthereumGasPolicy gas) => gas.Value;",
                "public static ulong GetRemainingGas(in EthereumGasPolicy gas) => 0;",
                StringComparison.Ordinal));

    [Test]
    public void UpdateGas_raw_subtraction_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "private static void ConsumeRaw(ref EthereumGasPolicy gas, ulong cost) => gas.Value -= cost;",
                "private static void ConsumeRaw(ref EthereumGasPolicy gas, ulong cost) => gas.Value += cost;",
                StringComparison.Ordinal));

    [Test]
    public void State_charge_kernel_argument_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "gas.StateGasSpillRefunded,\n            stateGasCost);",
                "gas.StateGasSpill,\n            stateGasCost);",
                StringComparison.Ordinal)
                .Replace(
                    "gas.StateGasSpillRefunded,\r\n            stateGasCost);",
                    "gas.StateGasSpill,\r\n            stateGasCost);",
                    StringComparison.Ordinal));

    [Test]
    public void State_charge_failure_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "if (result.Outcome is StateGasChargeOutcome.OutOfGas) return false;",
                "if (result.Outcome is StateGasChargeOutcome.Success) return false;",
                StringComparison.Ordinal));

    [Test]
    public void State_charge_projection_mutation_fails_closed() =>
        AssertSourceMutationRejected(Extractor.EthereumGasPolicyPath,
            text => text.Replace(
                "gas.StateGasSpillRefunded = result.StateGasSpillRefunded;",
                "gas.StateGasSpillRefunded = result.StateGasSpill;",
                StringComparison.Ordinal));

    [Test]
    public void Dependency_manifest_root_signature_mutation_fails_closed()
    {
        string root = FindRepoRoot();
        AssertFixtureMutationRejected(root, Extractor.StateGasChargeManifestPath,
            text => text.Replace("StateGasChargeResult", "StateGasChargeResultMutated", StringComparison.Ordinal));
    }

    [Test]
    public void Dependency_manifest_identity_mutation_fails_closed()
    {
        string root = FindRepoRoot();
        AssertFixtureMutationRejected(root, Extractor.StateGasChargeManifestPath,
            text => text.Replace("\"schemaVersion\": 3,", "\"schemaVersion\": 3,\n  ", StringComparison.Ordinal));
    }

    [Test]
    public void Dependency_refinement_identity_mutation_fails_closed()
    {
        string root = FindRepoRoot();
        AssertFixtureMutationRejected(root, Extractor.StateGasChargeRefinementPath,
            text => text.Replace(
                "theorem generatedTryCharge_refines_chargeState",
                "theorem generatedTryCharge_refines_chargeState ",
                StringComparison.Ordinal));
    }

    [Test]
    public void Dependency_lean_artifact_identity_mutation_fails_closed()
    {
        string root = FindRepoRoot();
        AssertFixtureMutationRejected(root, "tools/Evm/Lean/Eip803x/Generated/StateGasChargeKernel.lean",
            text => text + "\n");
    }

    [Test]
    public void Dependency_source_identity_mutation_fails_closed()
    {
        string root = FindRepoRoot();
        AssertFixtureMutationRejected(root, Extractor.StateGasChargeSourcePath,
            text => text + "\n");
    }

    private static void AssertSourceMutationRejected(string relativePath, Func<string, string> mutation)
    {
        string root = FindRepoRoot();
        using TemporaryDirectory fixture = new();
        CopyFixture(root, fixture.Path);
        string path = Path.Combine(fixture.Path, relativePath.Replace('/', Path.DirectorySeparatorChar));
        string original = File.ReadAllText(path);
        string changed = mutation(original);
        Assert.That(changed, Is.Not.EqualTo(original), "Mutation did not change its fixture source.");
        File.WriteAllText(path, changed, new UTF8Encoding(false));
        using TemporaryDirectory output = new();
        Assert.Throws<ExtractionException>(() => Extractor.Extract(fixture.Path, output.Path, Path.Combine(output.Path, "fold.lean")));
    }

    private static void AssertFixtureMutationRejected(string root, string relativePath, Func<string, string> mutation)
    {
        using TemporaryDirectory fixture = new();
        CopyFixture(root, fixture.Path);
        string path = Path.Combine(fixture.Path, relativePath.Replace('/', Path.DirectorySeparatorChar));
        string original = File.ReadAllText(path);
        string changed = mutation(original);
        Assert.That(changed, Is.Not.EqualTo(original), "Mutation did not change its fixture artifact.");
        File.WriteAllText(path, changed, new UTF8Encoding(false));
        using TemporaryDirectory output = new();
        Assert.Throws<ExtractionException>(() => Extractor.Extract(fixture.Path, output.Path, Path.Combine(output.Path, "fold.lean")));
    }

    private static string SwapAvailableGasSpillProjections(string text)
    {
        const string lf =
            "            StateGasSpill = result.StateGasSpill,\n" +
            "            StateGasSpillRefunded = result.StateGasSpillRefunded,";
        const string lfReplacement =
            "            StateGasSpillRefunded = result.StateGasSpillRefunded,\n" +
            "            StateGasSpill = result.StateGasSpill,";
        string changed = text.Replace(lf, lfReplacement, StringComparison.Ordinal);
        if (changed != text) return changed;

        const string crlf =
            "            StateGasSpill = result.StateGasSpill,\r\n" +
            "            StateGasSpillRefunded = result.StateGasSpillRefunded,";
        const string crlfReplacement =
            "            StateGasSpillRefunded = result.StateGasSpillRefunded,\r\n" +
            "            StateGasSpill = result.StateGasSpill,";
        return text.Replace(crlf, crlfReplacement, StringComparison.Ordinal);
    }

    private static string InvertInitialIntrinsicStateProjection(string text)
    {
        const string lf = "return spec.IsEip8037Enabled\n            ? new IntrinsicGas";
        const string crlf = "return spec.IsEip8037Enabled\r\n            ? new IntrinsicGas";
        string changed = text.Replace(lf, "return !spec.IsEip8037Enabled\n            ? new IntrinsicGas", StringComparison.Ordinal);
        return changed == text
            ? text.Replace(crlf, "return !spec.IsEip8037Enabled\r\n            ? new IntrinsicGas", StringComparison.Ordinal)
            : changed;
    }

    private static string SwapTopFrameFailureArms(string text)
    {
        const string lf =
            "                    if (spec.IsEip8037Enabled)\n" +
            "                    {\n" +
            "                        topFrameOutOfGas = true;\n" +
            "                    }\n" +
            "                    else\n" +
            "                    {\n" +
            "                        return TransactionResult.GasLimitBelowIntrinsicGas;\n" +
            "                    }";
        const string lfReplacement =
            "                    if (spec.IsEip8037Enabled)\n" +
            "                    {\n" +
            "                        return TransactionResult.GasLimitBelowIntrinsicGas;\n" +
            "                    }\n" +
            "                    else\n" +
            "                    {\n" +
            "                        topFrameOutOfGas = true;\n" +
            "                    }";
        string changed = text.Replace(lf, lfReplacement, StringComparison.Ordinal);
        if (changed != text) return changed;

        const string crlf =
            "                    if (spec.IsEip8037Enabled)\r\n" +
            "                    {\r\n" +
            "                        topFrameOutOfGas = true;\r\n" +
            "                    }\r\n" +
            "                    else\r\n" +
            "                    {\r\n" +
            "                        return TransactionResult.GasLimitBelowIntrinsicGas;\r\n" +
            "                    }";
        const string crlfReplacement =
            "                    if (spec.IsEip8037Enabled)\r\n" +
            "                    {\r\n" +
            "                        return TransactionResult.GasLimitBelowIntrinsicGas;\r\n" +
            "                    }\r\n" +
            "                    else\r\n" +
            "                    {\r\n" +
            "                        topFrameOutOfGas = true;\r\n" +
            "                    }";
        return text.Replace(crlf, crlfReplacement, StringComparison.Ordinal);
    }

    private static string NestRegistrationUnderConditional(string text)
    {
        const string prefix = "    {\n        builder\n";
        const string prefixReplacement = "    {\n        if (true)\n        {\n            builder\n";
        const string suffix = "            ;\n\n        builder.AddSingleton<IMainStateBlockProducerEnvFactory";
        const string suffixReplacement = "            ;\n        }\n\n        builder.AddSingleton<IMainStateBlockProducerEnvFactory";
        string changed = text.Replace(prefix, prefixReplacement, StringComparison.Ordinal);
        return changed.Replace(suffix, suffixReplacement, StringComparison.Ordinal);
    }

    private static string AddStandardAvailableGasOverride(string text)
    {
        const string lf =
            "        : EthereumTransactionProcessorBase(blobBaseFeeCalculator, specProvider, worldState, virtualMachine, codeInfoRepository, logManager, parallel);\n\n" +
            "    public class BlobBaseFeeCalculator";
        const string lfReplacement =
            "        : EthereumTransactionProcessorBase(blobBaseFeeCalculator, specProvider, worldState, virtualMachine, codeInfoRepository, logManager, parallel)\n" +
            "    {\n" +
            "        protected override TransactionResult CalculateAvailableGas(\n" +
            "            Transaction tx, IReleaseSpec spec, in IntrinsicGas<EthereumGasPolicy> intrinsicGas, out EthereumGasPolicy gasAvailable) =>\n" +
            "            base.CalculateAvailableGas(tx, spec, in intrinsicGas, out gasAvailable);\n" +
            "    }\n\n" +
            "    public class BlobBaseFeeCalculator";
        string changed = text.Replace(lf, lfReplacement, StringComparison.Ordinal);
        if (changed != text) return changed;

        const string crlf =
            "        : EthereumTransactionProcessorBase(blobBaseFeeCalculator, specProvider, worldState, virtualMachine, codeInfoRepository, logManager, parallel);\r\n\r\n" +
            "    public class BlobBaseFeeCalculator";
        const string crlfReplacement =
            "        : EthereumTransactionProcessorBase(blobBaseFeeCalculator, specProvider, worldState, virtualMachine, codeInfoRepository, logManager, parallel)\r\n" +
            "    {\r\n" +
            "        protected override TransactionResult CalculateAvailableGas(\r\n" +
            "            Transaction tx, IReleaseSpec spec, in IntrinsicGas<EthereumGasPolicy> intrinsicGas, out EthereumGasPolicy gasAvailable) =>\r\n" +
            "            base.CalculateAvailableGas(tx, spec, in intrinsicGas, out gasAvailable);\r\n" +
            "    }\r\n\r\n" +
            "    public class BlobBaseFeeCalculator";
        return text.Replace(crlf, crlfReplacement, StringComparison.Ordinal);
    }

    private static string MovePrePreparationAfterProcessCall(string text)
    {
        const string declaration = "            TGasPolicy prePreparationGas = gasAvailable;\r\n";
        int declarationIndex = text.IndexOf(declaration, StringComparison.Ordinal);
        if (declarationIndex < 0)
        {
            const string lfDeclaration = "            TGasPolicy prePreparationGas = gasAvailable;\n";
            declarationIndex = text.IndexOf(lfDeclaration, StringComparison.Ordinal);
            if (declarationIndex < 0) return text;
            text = text.Remove(declarationIndex, lfDeclaration.Length);
            int insertion = text.IndexOf("            bool loadRecipient = !topFrameOutOfGas;", StringComparison.Ordinal);
            return insertion <= 0 ? text : text.Insert(insertion, lfDeclaration);
        }
        text = text.Remove(declarationIndex, declaration.Length);
        int callInsertion = text.IndexOf("            bool loadRecipient = !topFrameOutOfGas;", StringComparison.Ordinal);
        return callInsertion <= 0 ? text : text.Insert(callInsertion, declaration);
    }

    private static string MoveResetsInsideRestoreGuard(string text)
    {
        const string crlf =
            "                    WorldState.Restore(preExecutionSnapshot);\r\n" +
            "                }\r\n\r\n" +
            "                gasAvailable = prePreparationGas;\r\n" +
            "                executionIntrinsicGasStandard = intrinsicGas.Standard;";
        const string crlfReplacement =
            "                    WorldState.Restore(preExecutionSnapshot);\r\n" +
            "                    gasAvailable = prePreparationGas;\r\n" +
            "                    executionIntrinsicGasStandard = intrinsicGas.Standard;\r\n" +
            "                }";
        string changed = text.Replace(crlf, crlfReplacement, StringComparison.Ordinal);
        if (changed != text) return changed;

        const string lf =
            "                    WorldState.Restore(preExecutionSnapshot);\n" +
            "                }\n\n" +
            "                gasAvailable = prePreparationGas;\n" +
            "                executionIntrinsicGasStandard = intrinsicGas.Standard;";
        const string lfReplacement =
            "                    WorldState.Restore(preExecutionSnapshot);\n" +
            "                    gasAvailable = prePreparationGas;\n" +
            "                    executionIntrinsicGasStandard = intrinsicGas.Standard;\n" +
            "                }";
        return text.Replace(lf, lfReplacement, StringComparison.Ordinal);
    }

    private static string NestSnapshotAssignmentsUnderExtraGuard(string text)
    {
        const string crlf =
            "                    preExecutionSnapshot = WorldState.TakeSnapshot();\r\n" +
            "                    hasPreExecutionSnapshot = true;";
        const string crlfReplacement =
            "                    if (spec.IsEip7702Enabled)\r\n" +
            "                    {\r\n" +
            "                        preExecutionSnapshot = WorldState.TakeSnapshot();\r\n" +
            "                        hasPreExecutionSnapshot = true;\r\n" +
            "                    }";
        string changed = text.Replace(crlf, crlfReplacement, StringComparison.Ordinal);
        if (changed != text) return changed;

        const string lf =
            "                    preExecutionSnapshot = WorldState.TakeSnapshot();\n" +
            "                    hasPreExecutionSnapshot = true;";
        const string lfReplacement =
            "                    if (spec.IsEip7702Enabled)\n" +
            "                    {\n" +
            "                        preExecutionSnapshot = WorldState.TakeSnapshot();\n" +
            "                        hasPreExecutionSnapshot = true;\n" +
            "                    }";
        return text.Replace(lf, lfReplacement, StringComparison.Ordinal);
    }

    private static byte[] ReadCheckedIr() => File.ReadAllBytes(Path.Combine(
        FindRepoRoot(), "tools/Evm/Lean/AuthorizationStateGasFoldExtractor/Generated/AuthorizationStateGasFold.ir.json"));

    private static byte[] ReadCheckedManifest() => File.ReadAllBytes(Path.Combine(
        FindRepoRoot(), "tools/Evm/Lean/AuthorizationStateGasFoldExtractor/Generated/AuthorizationStateGasFold.source-manifest.json"));

    private static JsonObject ParseObject(byte[] bytes) =>
        JsonNode.Parse(bytes)?.AsObject() ?? throw new AssertionException("Checked artifact was not a JSON object.");

    private static byte[] Serialize(JsonObject value) =>
        Encoding.UTF8.GetBytes(value.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n");

    private static byte[] DuplicateSchemaVersion(byte[] source)
    {
        string text = Encoding.UTF8.GetString(source);
        int objectStart = text.IndexOf('{');
        if (objectStart < 0) throw new AssertionException("Checked artifact was not a JSON object.");
        return Encoding.UTF8.GetBytes(text.Insert(objectStart + 1, "\n  \"schemaVersion\": 2,"));
    }

    private static void AssertIrRejected(byte[] source, byte[] candidate) =>
        Assert.Throws<ExtractionException>(() => Extractor.ValidateSerializedIr(source, candidate));

    private static void AssertManifestRejected(byte[] source, byte[] candidate) =>
        Assert.Throws<ExtractionException>(() => Extractor.ValidateSerializedManifest(source, candidate));

    private static void CopyFixture(string sourceRoot, string targetRoot)
    {
        string[] paths =
        [
            Extractor.EthereumGasPolicyPath,
            Extractor.TransactionProcessorPath,
            Extractor.IntrinsicGasCalculatorPath,
            Extractor.MainnetDiPath,
            Extractor.TransactionGasInitializationManifestPath,
            Extractor.StateGasChargeManifestPath,
            Extractor.StateGasTransitionManifestPath,
            Extractor.TransactionGasInitializationSourcePath,
            Extractor.StateGasChargeSourcePath,
            Extractor.StateGasTransitionSourcePath,
            Extractor.TransactionGasInitializationRefinementPath,
            Extractor.StateGasChargeRefinementPath,
            Extractor.StateGasTransitionRefinementPath,
            "tools/Evm/Lean/Eip803x/Generated/TransactionGasInitializationKernel.lean",
            "tools/Evm/Lean/Eip803x/Generated/StateGasChargeKernel.lean",
            "tools/Evm/Lean/Eip803x/Generated/StateGasTransitionKernel.lean",
        ];
        foreach (string relative in paths)
        {
            string source = Path.Combine(sourceRoot, relative.Replace('/', Path.DirectorySeparatorChar));
            string target = Path.Combine(targetRoot, relative.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(target)!);
            File.Copy(source, target);
        }
    }

    private static string FindRepoRoot()
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "global.json")))
            directory = directory.Parent;
        return directory?.FullName ?? throw new AssertionException("Could not find repository root.");
    }

    private sealed class TemporaryDirectory : IDisposable
    {
        public TemporaryDirectory()
        {
            Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "authorization-state-gas-fold-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(Path);
        }

        public string Path { get; }

        public void Dispose()
        {
            if (Directory.Exists(Path))
                Directory.Delete(Path, recursive: true);
        }
    }
}
