// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Nethermind.JsonRpc.SourceGenerator.Build;

/// <summary>
/// Build-time entry point that emits the JSON serializer context used by JSON-RPC assemblies.
/// </summary>
/// <remarks>
/// The incremental RPC source generator can discover RPC payload types, but System.Text.Json source
/// generation cannot use <see cref="JsonSerializableAttribute"/> roots that are emitted by another
/// generator into the same target assembly during that compiler pass. The MSBuild target therefore
/// runs this executable before <c>CoreCompile</c>, passing the target project's source and reference
/// lists. This program builds a Roslyn compilation that matches the target project, discovers JSON-RPC
/// parameter/result types, filters out roots that the generated context cannot safely represent, and
/// writes a real <c>GeneratedRpcJsonContext.g.cs</c> file into <c>obj</c> so the System.Text.Json
/// generator can process it when the target project compiles.
/// </remarks>
internal static class Program
{
    private const string GeneratedSourceHeader = "// <auto-generated/>\n#nullable enable\n";

    private static int Main(string[] args)
    {
        try
        {
            Arguments arguments = Arguments.Parse(args);
            Generate(arguments);
            return 0;
        }
        catch (Exception exception)
        {
            Console.Error.WriteLine(exception);
            return 1;
        }
    }

    /// <summary>
    /// Creates the target-project compilation and writes the generated context source when any RPC
    /// payload types are eligible for System.Text.Json metadata generation.
    /// </summary>
    private static void Generate(Arguments arguments)
    {
        string[] sourcePaths = ReadExistingLines(arguments.SourcesFile);
        string[] referencePaths = ReadExistingLines(arguments.ReferencesFile);
        CSharpParseOptions parseOptions = CSharpParseOptions.Default
            .WithLanguageVersion(LanguageVersion.Preview)
            .WithPreprocessorSymbols(GetPreprocessorSymbols(arguments.DefineConstants));

        SyntaxTree[] syntaxTrees = Array.ConvertAll(sourcePaths, sourcePath =>
            CSharpSyntaxTree.ParseText(
                File.ReadAllText(sourcePath),
                parseOptions,
                sourcePath));
        MetadataReference[] references = Array.ConvertAll<string, MetadataReference>(referencePaths, static referencePath => MetadataReference.CreateFromFile(referencePath));

        CSharpCompilation compilation = CSharpCompilation.Create(
            arguments.AssemblyName,
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        List<ITypeSymbol> typeSymbols = CollectTypeSymbols(compilation, syntaxTrees);
        JsonRoot[] sortedTypes = GetSourceGeneratedTypes(typeSymbols, compilation.Assembly);
        if (sortedTypes.Length == 0)
        {
            File.Delete(arguments.OutputPath);
            return;
        }

        string output = GenerateContextSource(sortedTypes);
        Directory.CreateDirectory(Path.GetDirectoryName(arguments.OutputPath)!);
        WriteIfChanged(arguments.OutputPath, output);
    }

    /// <summary>
    /// Reuses the analyzer/source-generator discovery rules to find RPC method payload and subscription
    /// message types in the target assembly.
    /// </summary>
    private static List<ITypeSymbol> CollectTypeSymbols(CSharpCompilation compilation, SyntaxTree[] syntaxTrees)
    {
        List<ITypeSymbol> types = [];
        for (int i = 0; i < syntaxTrees.Length; i++)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(syntaxTrees[i]);
            foreach (SyntaxNode node in syntaxTrees[i].GetRoot().DescendantNodes())
            {
                ImmutableArray<ITypeSymbol> jsonTypes = RpcJsonTypeDiscovery.GetJsonTypeSymbols(semanticModel, node, CancellationToken.None);
                if (!jsonTypes.IsDefaultOrEmpty)
                {
                    types.AddRange(jsonTypes);
                }
            }
        }

        return types;
    }

    /// <summary>
    /// Builds the source file that declares all eligible <see cref="JsonSerializableAttribute"/> roots
    /// and registers the generated resolver at module initialization time.
    /// </summary>
    private static string GenerateContextSource(JsonRoot[] sortedTypes)
    {
        StringBuilder builder = new();
        builder.AppendLine(GeneratedSourceHeader).AppendLine(
            """
            using System.Runtime.CompilerServices;
            using System.Text.Json.Serialization;
            using Nethermind.Serialization.Json;

            namespace Nethermind.JsonRpc;

            [JsonSourceGenerationOptions(
                GenerationMode = JsonSourceGenerationMode.Metadata,
                PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
                PropertyNameCaseInsensitive = true,
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                IncludeFields = true)]
            """);
        for (int i = 0; i < sortedTypes.Length; i++)
        {
            JsonRoot root = sortedTypes[i];
            builder.AppendLine(root.TypeInfoPropertyName is null
                ? $"[JsonSerializable(typeof({root.DisplayName}))]"
                : $"[JsonSerializable(typeof({root.DisplayName}), TypeInfoPropertyName = \"{root.TypeInfoPropertyName}\")]");
        }

        builder.AppendLine(
            """
            internal partial class GeneratedRpcJsonContext : JsonSerializerContext
            {
                [ModuleInitializer]
                internal static void Register()
                {
                    EthereumJsonSerializer.AddTypeInfoResolver(Default, JsonTypeInfoResolverPriority.GeneratedRpc);
                }
            }
            """);
        return builder.ToString();
    }

    /// <summary>
    /// Deduplicates discovered types, removes roots the generated System.Text.Json metadata context cannot
    /// represent, and names types whose generated metadata members would otherwise collide.
    /// </summary>
    private static JsonRoot[] GetSourceGeneratedTypes(List<ITypeSymbol> typeSymbols, IAssemblySymbol currentAssembly)
    {
        JsonContextEligibility eligibility = new(currentAssembly);
        Dictionary<string, JsonTypeCandidate> candidatesByDisplayName = new(StringComparer.Ordinal);

        for (int i = 0; i < typeSymbols.Count; i++)
        {
            ITypeSymbol type = typeSymbols[i];
            string displayName = RpcJsonTypeDiscovery.GetTypeDisplayString(type);
            if (!candidatesByDisplayName.ContainsKey(displayName) &&
                eligibility.CreateCandidate(type, displayName) is { } candidate)
            {
                candidatesByDisplayName.Add(displayName, candidate);
            }
        }

        Dictionary<string, HashSet<string>> displayNamesByGeneratedName = GetDisplayNamesByGeneratedName(candidatesByDisplayName.Values);
        HashSet<string> unnameableCollisions = new(StringComparer.Ordinal);
        Dictionary<string, string?> propertyNameByDisplayName = new(StringComparer.Ordinal);
        foreach (KeyValuePair<string, HashSet<string>> group in displayNamesByGeneratedName)
        {
            if (group.Value.Count < 2)
            {
                continue;
            }

            // A colliding type the context cannot name in typeof() keeps the collision, so its roots are dropped.
            if (!group.Value.All(eligibility.IsAccessible))
            {
                unnameableCollisions.Add(group.Key);
                continue;
            }

            foreach (string displayName in group.Value)
            {
                propertyNameByDisplayName[displayName] = GetUniquePropertyName(displayName);
            }
        }

        foreach (JsonTypeCandidate candidate in candidatesByDisplayName.Values)
        {
            if (!unnameableCollisions.Overlaps(candidate.GeneratedTypeNames.Keys))
            {
                propertyNameByDisplayName.TryAdd(candidate.DisplayName, null);
            }
        }

        JsonRoot[] roots = [.. propertyNameByDisplayName.Select(static p => new JsonRoot(p.Key, p.Value))];
        Array.Sort(roots, static (left, right) => StringComparer.Ordinal.Compare(left.DisplayName, right.DisplayName));
        return roots;
    }

    private static Dictionary<string, HashSet<string>> GetDisplayNamesByGeneratedName(IEnumerable<JsonTypeCandidate> candidates)
    {
        Dictionary<string, HashSet<string>> displayNamesByGeneratedName = new(StringComparer.Ordinal);
        foreach (JsonTypeCandidate candidate in candidates)
        {
            foreach (KeyValuePair<string, string> generatedTypeName in candidate.GeneratedTypeNames)
            {
                if (!displayNamesByGeneratedName.TryGetValue(generatedTypeName.Key, out HashSet<string>? displayNames))
                {
                    displayNamesByGeneratedName[generatedTypeName.Key] = displayNames = new(StringComparer.Ordinal);
                }

                displayNames.Add(generatedTypeName.Value);
            }
        }

        return displayNamesByGeneratedName;
    }

    /// <summary>Derives a metadata property name from the namespace-qualified type name, which is unique per type.</summary>
    private static string GetUniquePropertyName(string displayName)
    {
        StringBuilder builder = new(displayName.Length);
        foreach (char c in displayName.Replace("global::", string.Empty, StringComparison.Ordinal).Replace("[]", "Array", StringComparison.Ordinal))
        {
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return builder.ToString();
    }

    private sealed record JsonTypeCandidate(string DisplayName, Dictionary<string, string> GeneratedTypeNames);

    private sealed record JsonRoot(string DisplayName, string? TypeInfoPropertyName);

    /// <summary>
    /// Mirrors the constraints that matter for a generated <see cref="JsonSerializerContext"/> emitted
    /// into the target assembly.
    /// </summary>
    /// <remarks>
    /// A root is accepted when the target assembly can name it. The traversal rejects metadata graphs that
    /// require inaccessible custom converters; those types stay with the context of the assembly that owns
    /// the converter, or with the reflection resolver.
    /// </remarks>
    private sealed class JsonContextEligibility(IAssemblySymbol currentAssembly)
    {
        private const string JsonSerializationNamespace = "System.Text.Json.Serialization";
        private const string SystemNamespace = "System";

        private readonly IAssemblySymbol _currentAssembly = currentAssembly;
        private readonly Dictionary<string, bool> _accessibleByDisplayName = new(StringComparer.Ordinal);

        /// <summary>Whether generated code in the target assembly can name a type the traversal visited.</summary>
        public bool IsAccessible(string displayName) => _accessibleByDisplayName.TryGetValue(displayName, out bool accessible) && accessible;

        // The context is emitted into the target assembly, so roots that require inaccessible
        // converters or colliding generated metadata names must stay on the existing resolver path.
        public JsonTypeCandidate? CreateCandidate(ITypeSymbol type, string displayName)
        {
            if (!IsAccessibleType(type))
            {
                return null;
            }

            Dictionary<string, string> generatedTypeNames = new(StringComparer.Ordinal);
            HashSet<string> visitedTypes = new(StringComparer.Ordinal);
            return CanGenerateMetadata(type, generatedTypeNames, visitedTypes)
                ? new JsonTypeCandidate(displayName, generatedTypeNames)
                : null;
        }

        private bool IsAccessibleType(ITypeSymbol type)
        {
            switch (type)
            {
                case IArrayTypeSymbol arrayType:
                    return IsAccessibleType(arrayType.ElementType);
                case INamedTypeSymbol namedType:
                    if (!IsAccessibleFromGeneratedContext(namedType))
                    {
                        return false;
                    }

                    for (int i = 0; i < namedType.TypeArguments.Length; i++)
                    {
                        if (!IsAccessibleType(namedType.TypeArguments[i]))
                        {
                            return false;
                        }
                    }

                    return true;
                default:
                    return false;
            }
        }

        private bool CanGenerateMetadata(
            ITypeSymbol type,
            Dictionary<string, string> generatedTypeNames,
            HashSet<string> visitedTypes)
        {
            if (type.TypeKind is TypeKind.Error or TypeKind.TypeParameter or TypeKind.Pointer or TypeKind.FunctionPointer ||
                type.SpecialType == SpecialType.System_Void)
            {
                return false;
            }

            string displayName = RpcJsonTypeDiscovery.GetTypeDisplayString(type);
            if (!visitedTypes.Add(displayName))
            {
                return true;
            }

            _accessibleByDisplayName[displayName] = IsAccessibleType(type);
            if (!AddGeneratedTypeName(type, generatedTypeNames) ||
                !HasOnlyAccessibleJsonConverterAttributes(type))
            {
                return false;
            }

            if (type is IArrayTypeSymbol arrayType)
            {
                return CanGenerateMetadata(arrayType.ElementType, generatedTypeNames, visitedTypes);
            }

            if (type is not INamedTypeSymbol namedType)
            {
                return true;
            }

            for (int i = 0; i < namedType.TypeArguments.Length; i++)
            {
                if (!CanGenerateMetadata(namedType.TypeArguments[i], generatedTypeNames, visitedTypes))
                {
                    return false;
                }
            }

            if (!AddJsonDerivedTypes(namedType, generatedTypeNames, visitedTypes) ||
                !ShouldInspectMembers(namedType))
            {
                return true;
            }

            ImmutableArray<ISymbol> members = namedType.GetMembers();
            for (int i = 0; i < members.Length; i++)
            {
                if (!CanGenerateMemberMetadata(members[i], generatedTypeNames, visitedTypes))
                {
                    return false;
                }
            }

            return true;
        }

        private bool AddJsonDerivedTypes(
            INamedTypeSymbol type,
            Dictionary<string, string> generatedTypeNames,
            HashSet<string> visitedTypes)
        {
            ImmutableArray<AttributeData> attributes = type.GetAttributes();
            for (int i = 0; i < attributes.Length; i++)
            {
                AttributeData attribute = attributes[i];
                if (!IsAttribute(attribute.AttributeClass, JsonSerializationNamespace, "JsonDerivedTypeAttribute") ||
                    attribute.ConstructorArguments.Length == 0 ||
                    attribute.ConstructorArguments[0].Value is not ITypeSymbol derivedType)
                {
                    continue;
                }

                if (!CanGenerateMetadata(derivedType, generatedTypeNames, visitedTypes))
                {
                    return false;
                }
            }

            return true;
        }

        private bool CanGenerateMemberMetadata(ISymbol member, Dictionary<string, string> generatedTypeNames, HashSet<string> visitedTypes) =>
            HasOnlyAccessibleJsonConverterAttributes(member) &&
            (member switch
            {
                IPropertySymbol { IsStatic: false, Parameters.Length: 0 } property when IsJsonVisible(property) =>
                    CanGenerateMetadata(property.Type, generatedTypeNames, visitedTypes),
                IFieldSymbol { IsStatic: false, IsConst: false } field when IsJsonVisible(field) =>
                    CanGenerateMetadata(field.Type, generatedTypeNames, visitedTypes),
                _ => true
            });

        private static bool IsJsonVisible(IPropertySymbol property) =>
            property.DeclaredAccessibility == Accessibility.Public ||
            property.GetMethod?.DeclaredAccessibility == Accessibility.Public ||
            property.SetMethod?.DeclaredAccessibility == Accessibility.Public ||
            HasAttribute(property, JsonSerializationNamespace, "JsonIncludeAttribute");

        private static bool IsJsonVisible(IFieldSymbol field) =>
            field.DeclaredAccessibility == Accessibility.Public ||
            HasAttribute(field, JsonSerializationNamespace, "JsonIncludeAttribute");

        private static bool ShouldInspectMembers(INamedTypeSymbol type) =>
            type.SpecialType == SpecialType.None &&
            !IsSystemType(type) &&
            type.TypeKind is TypeKind.Class or TypeKind.Struct or TypeKind.Interface;

        private bool HasOnlyAccessibleJsonConverterAttributes(ISymbol symbol)
        {
            ImmutableArray<AttributeData> attributes = symbol.GetAttributes();
            for (int i = 0; i < attributes.Length; i++)
            {
                AttributeData attribute = attributes[i];
                if (IsAttribute(attribute.AttributeClass, JsonSerializationNamespace, "JsonConverterAttribute") &&
                    attribute.ConstructorArguments.Length != 0 &&
                    attribute.ConstructorArguments[0].Value is INamedTypeSymbol converterType &&
                    !IsAccessibleFromGeneratedContext(converterType))
                {
                    return false;
                }
            }

            return true;
        }

        private bool IsAccessibleFromGeneratedContext(INamedTypeSymbol type)
        {
            INamedTypeSymbol? current = type;
            while (current is not null)
            {
                bool sameAssembly = SymbolEqualityComparer.Default.Equals(current.ContainingAssembly, _currentAssembly);
                if (current.DeclaredAccessibility == Accessibility.Public ||
                    sameAssembly && current.DeclaredAccessibility is Accessibility.Internal or Accessibility.ProtectedOrInternal)
                {
                    current = current.ContainingType;
                    continue;
                }

                return false;
            }

            return true;
        }

        private static bool AddGeneratedTypeName(ITypeSymbol type, Dictionary<string, string> generatedTypeNames)
        {
            string generatedTypeName = GetGeneratedTypeName(type);
            string displayName = RpcJsonTypeDiscovery.GetTypeDisplayString(type);
            return generatedTypeNames.TryAdd(generatedTypeName, displayName) ||
                generatedTypeNames[generatedTypeName] == displayName;
        }

        private static string GetGeneratedTypeName(ITypeSymbol type) =>
            type switch
            {
                IArrayTypeSymbol arrayType => GetGeneratedTypeName(arrayType.ElementType) + "Array",
                INamedTypeSymbol namedType => GetNamedGeneratedTypeName(namedType),
                _ => type.MetadataName
            };

        private static string GetNamedGeneratedTypeName(INamedTypeSymbol type)
        {
            StringBuilder builder = new();
            if (type.ContainingType is not null)
            {
                builder.Append(GetNamedGeneratedTypeName(type.ContainingType));
            }

            string metadataName = type.MetadataName;
            int genericTickIndex = metadataName.IndexOf('`', StringComparison.Ordinal);
            builder.Append(genericTickIndex >= 0 ? metadataName[..genericTickIndex] : metadataName);

            if (type.IsGenericType)
            {
                for (int i = 0; i < type.TypeArguments.Length; i++)
                {
                    builder.Append(GetGeneratedTypeName(type.TypeArguments[i]));
                }
            }

            return builder.ToString();
        }

        private static bool IsSystemType(INamedTypeSymbol type)
        {
            string fullName = type.ContainingNamespace.ToDisplayString();
            return fullName == SystemNamespace || fullName.StartsWith(SystemNamespace + ".", StringComparison.Ordinal);
        }

        private static bool HasAttribute(ISymbol symbol, string namespaceName, string metadataName)
        {
            ImmutableArray<AttributeData> attributes = symbol.GetAttributes();
            for (int i = 0; i < attributes.Length; i++)
            {
                if (IsAttribute(attributes[i].AttributeClass, namespaceName, metadataName))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsAttribute(INamedTypeSymbol? attributeClass, string namespaceName, string metadataName) =>
            attributeClass is not null &&
            attributeClass.ContainingNamespace.ToDisplayString() == namespaceName &&
            attributeClass.MetadataName == metadataName;
    }

    private static string[] GetPreprocessorSymbols(string defineConstants)
    {
        if (string.IsNullOrWhiteSpace(defineConstants))
        {
            return [];
        }

        string[] symbols = defineConstants.Split([';', ','], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        for (int i = 0; i < symbols.Length; i++)
        {
            int equalsIndex = symbols[i].IndexOf('=');
            if (equalsIndex >= 0) symbols[i] = symbols[i][..equalsIndex];
        }

        return symbols;
    }

    private static string[] ReadExistingLines(string path)
    {
        if (!File.Exists(path))
        {
            return [];
        }

        string[] lines = File.ReadAllLines(path);
        List<string> existing = new(lines.Length);
        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i];
            if (File.Exists(line)) existing.Add(line);
        }

        return [.. existing];
    }

    private static void WriteIfChanged(string path, string content)
    {
        if (File.Exists(path) && File.ReadAllText(path) == content)
        {
            return;
        }

        File.WriteAllText(path, content, Encoding.UTF8);
    }

    private sealed record Arguments(string OutputPath, string SourcesFile, string ReferencesFile, string AssemblyName, string DefineConstants)
    {
        public static Arguments Parse(string[] args)
        {
            Dictionary<string, string> values = new(StringComparer.Ordinal);
            for (int i = 0; i < args.Length; i += 2)
            {
                if (i + 1 >= args.Length || !args[i].StartsWith("--", StringComparison.Ordinal))
                {
                    throw new ArgumentException($"Invalid argument at index {i}.");
                }

                values[args[i]] = args[i + 1];
            }

            return new Arguments(
                GetRequired(values, "--output"),
                GetRequired(values, "--sources"),
                GetRequired(values, "--references"),
                GetRequired(values, "--assembly-name"),
                values.GetValueOrDefault("--define-constants", string.Empty));
        }

        private static string GetRequired(Dictionary<string, string> values, string name) =>
            values.TryGetValue(name, out string? value) && !string.IsNullOrWhiteSpace(value)
                ? value
                : throw new ArgumentException($"Missing required argument {name}.");
    }
}
