// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Text;

namespace Nethermind.Evm.Lean.PersistentStorageOpcodeExtractor;

internal static class LeanEmitter
{
    private static readonly UTF8Encoding Utf8WithoutBom = new(false);
    private static readonly string[] ExpectedOpenExtractionObligations =
    [
        "The theorem covers the immediate standard-mainnet Amsterdam SLOAD/SSTORE handler abstraction selected by the eight admitted dispatch roots; C#, Roslyn, CLR/JIT, unsafe function-pointer execution, and hardware remain trusted.",
        "UInt256, Address, EvmStack, byte-array normalization, zero canonicalization, span lifetime, and provider-value representation remain adapter premises.",
        "IWorldState Get/GetOriginal/Set correctness, database persistence, storage journaling, snapshots, frame rollback/merge, and decorators remain separate obligations.",
        "StackAccessTracker collection implementation and BAL behavior are abstracted as an extensional warm-cell set; its admitted charge-before-warm path is covered for VM.IsTracingAccess=false, while access-list tracing, provider allocation, and concurrency remain open.",
        "Tracing callbacks, callback failures, metrics, cancellation, opcode counter overflow, transaction refund cap, receipt accounting, and block accounting are outside this handler theorem.",
        "Fixed-width ulong/long overflow is excluded by the refinement's explicit Amsterdam schedule and well-formed production-gas representation premises.",
    ];

    internal static byte[] Emit(IrDocument document, string irHash)
    {
        Validate(document);
        OpcodeDescriptor sload = document.Opcodes.Single(static opcode => opcode.Name == "sload");
        OpcodeDescriptor sstore = document.Opcodes.Single(static opcode => opcode.Name == "sstore");
        GasScheduleDescriptor schedule = document.Schedule;
        string specializationEntries = string.Join(",\n  ", document.Specializations.Select(static specialization =>
            $"{{ opcode := .{specialization.Opcode}, table := {LeanString(specialization.Table)}, " +
            $"tracingFlag := {LeanString(specialization.TracingFlag)}, cancellationFlag := {LeanString(specialization.CancellationFlag)}, " +
            $"closedRoot := {LeanString(specialization.ClosedRoot)} }}"));
        string obligationEntries = string.Join(",\n  ",
            document.OpenExtractionObligations.Select(static obligation => LeanString(obligation)));

        string source = $$"""
            -- SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
            -- SPDX-License-Identifier: LGPL-3.0-only

            -- Generated by PersistentStorageOpcodeExtractor; do not edit.
            -- Extractor: {{document.ExtractorVersion}}
            -- Semantic IR SHA-256: {{irHash}}

            import Eip803x.Gas
            import Eip803x.Evm.MemoryStackControl
            import Eip803x.Evm.Word

            namespace Eip803x.Generated.PersistentStorageOpcodeKernel

            open Eip803x
            open Eip803x.GasMachine
            open Eip803x.Evm
            open Eip803x.Evm.MemoryStackControl
            open Eip803x.Evm.Word

            structure Schedule where
              sloadBase : Nat
              coldStorageAccess : Nat
              warmAccess : Nat
              storageWrite : Nat
              storageClearRefund : Int
              storageSetStateGas : Nat
              sstoreStipend : Nat
              deriving DecidableEq, Repr

            def amsterdamSchedule : Schedule :=
              { sloadBase := {{schedule.SloadBase}}
                coldStorageAccess := {{schedule.ColdStorageAccess}}
                warmAccess := {{schedule.WarmAccess}}
                storageWrite := {{schedule.StorageWrite}}
                storageClearRefund := {{schedule.StorageClearRefund}}
                storageSetStateGas := {{schedule.StorageSetStateGas}}
                sstoreStipend := {{schedule.SstoreStipend}} }

            def consensusIsTracingAccess : Bool :=
              {{document.ExecutionMode.IsTracingAccess.ToString().ToLowerInvariant()}}

            def executionModeApplicability : String :=
              {{LeanString(document.ExecutionMode.Applicability)}}

            def openExtractionObligations : List String :=
              [{{obligationEntries}}]

            inductive Opcode where
              | sload
              | sstore
              deriving DecidableEq, Repr

            def allOpcodes : List Opcode := [.sload, .sstore]

            def opcodeByte : Opcode → Nat
              | .sload => {{sload.OpcodeByte}}
              | .sstore => {{sstore.OpcodeByte}}

            structure DispatchSpecialization where
              opcode : Opcode
              table : String
              tracingFlag : String
              cancellationFlag : String
              closedRoot : String
              deriving DecidableEq, Repr

            def dispatchSpecializations : List DispatchSpecialization :=
              [{{specializationEntries}}]

            inductive AccessStatus where
              | cold
              | warm
              deriving DecidableEq, Repr

            structure StorageSituation where
              original : UInt256
              current : UInt256
              newValue : UInt256
              access : AccessStatus
              deriving DecidableEq, Repr

            structure StorageGasEffect where
              executionCharge : Nat
              executionRefund : Int
              stateCharge : Nat
              stateRefill : Nat
              deriving DecidableEq, Repr

            def accessCost (schedule : Schedule) : AccessStatus → Nat
              | .cold => schedule.coldStorageAccess
              | .warm => schedule.warmAccess

            abbrev isFirstChange (input : StorageSituation) : Prop :=
              input.newValue ≠ input.current ∧ input.current = input.original

            abbrev clearsOriginal (input : StorageSituation) : Prop :=
              input.original ≠ 0 ∧ input.current ≠ 0 ∧ input.newValue = 0

            abbrev reversesClear (input : StorageSituation) : Prop :=
              input.original ≠ 0 ∧ input.current = 0 ∧ input.newValue ≠ 0

            abbrev restoresOriginal (input : StorageSituation) : Prop :=
              input.newValue = input.original ∧ input.newValue ≠ input.current

            abbrev createsSlot (input : StorageSituation) : Prop :=
              input.original = 0 ∧ input.current = 0 ∧ input.newValue ≠ 0

            abbrev removesCreatedSlot (input : StorageSituation) : Prop :=
              input.original = 0 ∧ input.current ≠ 0 ∧ input.newValue = 0

            def price (schedule : Schedule) (input : StorageSituation) : StorageGasEffect :=
              { executionCharge := accessCost schedule input.access +
                  if isFirstChange input then schedule.storageWrite else 0
                executionRefund :=
                  (if clearsOriginal input then schedule.storageClearRefund else 0) -
                  (if reversesClear input then schedule.storageClearRefund else 0) +
                  (if restoresOriginal input then (schedule.storageWrite : Int) else 0)
                stateCharge := if createsSlot input then schedule.storageSetStateGas else 0
                stateRefill := if removesCreatedSlot input then schedule.storageSetStateGas else 0 }

            structure Cell where
              address : UInt256
              key : UInt256
              deriving DecidableEq, Repr

            structure Slot where
              original : UInt256
              current : UInt256
              deriving DecidableEq, Repr

            abbrev Store := List (Cell × Slot)

            def zeroSlot : Slot := { original := Word.zero, current := Word.zero }

            def readSlot : Store → Cell → Slot
              | [], _ => zeroSlot
              | (candidate, value) :: tail, cell =>
                  if candidate = cell then value else readSlot tail cell

            def readOriginal (store : Store) (cell : Cell) : UInt256 :=
              (readSlot store cell).original

            def readCurrent (store : Store) (cell : Cell) : UInt256 :=
              (readSlot store cell).current

            def writeCurrent : Store → Cell → UInt256 → Store
              | [], cell, value => [(cell, { original := Word.zero, current := value })]
              | (candidate, slot) :: tail, cell, value =>
                  if candidate = cell then
                    (candidate, { slot with current := value }) :: tail
                  else
                    (candidate, slot) :: writeCurrent tail cell value

            def accessStatus (warmCells : List Cell) (cell : Cell) : AccessStatus :=
              if cell ∈ warmCells then .warm else .cold

            def warmCell (warmCells : List Cell) (cell : Cell) : List Cell :=
              if cell ∈ warmCells then warmCells else cell :: warmCells

            inductive Event where
              | sloadBaseCharged (amount : Nat)
              | keyPopped (key : UInt256)
              | valuePopped (value : UInt256)
              | accessCharged (cell : Cell) (status : AccessStatus) (amount : Nat)
              | currentRead (cell : Cell) (value : UInt256)
              | originalRead (cell : Cell) (value : UInt256)
              | netMeteredNoOp
              | executionWriteCharged (amount : Nat)
              | stateCharged (amount : Nat)
              | refundAdjusted (amount : Int)
              | stateRefundCredited (amount advanced : Nat)
              | storageWritten (cell : Cell) (value : UInt256)
              | valuePushed (value : UInt256)
              deriving DecidableEq, Repr

            structure MachineState where
              gas : GasState
              stateGasFloor : Nat
              stateGasRefundAdvanced : Nat
              stack : Stack
              storage : Store
              warmCells : List Cell
              executingAccount : UInt256
              events : List Event
              pc : Nat
              deriving Repr

            inductive Status where
              | ok
              | outOfGas
              | stackUnderflow
              | stackOverflow
              | staticCallViolation
              | badInstruction
              deriving DecidableEq, Repr

            structure Outcome where
              status : Status
              state : MachineState
              deriving Repr

            def record (state : MachineState) (event : Event) : MachineState :=
              { state with events := state.events ++ [event] }

            def exhaustExecutionGas (state : MachineState) : MachineState :=
              { state with gas := { state.gas with gasLeft := 0 } }

            def advancePc (state : MachineState) : MachineState :=
              { state with pc := state.pc + 1 }

            def addAdvancedStateRefund (amount : Nat) (gas : GasState) : GasState :=
              let toGasLeft := min amount gas.stateFromGasLeft
              { gas with
                gasLeft := gas.gasLeft + toGasLeft
                stateReservoir := gas.stateReservoir + (amount - toGasLeft)
                stateFromGasLeft := gas.stateFromGasLeft - toGasLeft }

            structure StateGasCredit where
              gas : GasState
              advanced : Nat
              deriving DecidableEq, Repr

            def creditStateGasRefund (amount stateGasFloor : Nat) (gas : GasState) : StateGasCredit :=
              let refundableHere := gas.stateUsed - stateGasFloor
              let appliedHere := min amount refundableHere
              let afterLocal := refillState appliedHere gas
              let advanced := amount - appliedHere
              { gas := addAdvancedStateRefund advanced afterLocal, advanced }

            def creditMachineStateRefund (amount : Nat) (state : MachineState) : MachineState :=
              if amount = 0 then state else
                let credit := creditStateGasRefund amount state.stateGasFloor state.gas
                record
                  { state with
                    gas := credit.gas
                    stateGasRefundAdvanced := state.stateGasRefundAdvanced + credit.advanced }
                  (.stateRefundCredited amount credit.advanced)

            def adjustRefund (amount : Int) (state : MachineState) : MachineState :=
              if amount = 0 then state else
                record
                  { state with gas := { state.gas with refundCounter := state.gas.refundCounter + amount } }
                  (.refundAdjusted amount)

            def clearRefundAdjustment (schedule : Schedule) (input : StorageSituation) : Int :=
              if clearsOriginal input then schedule.storageClearRefund else 0

            def clearRefundReversal (schedule : Schedule) (input : StorageSituation) : Int :=
              if reversesClear input then -schedule.storageClearRefund else 0

            def restoreOriginalRefund (schedule : Schedule) (input : StorageSituation) : Int :=
              if restoresOriginal input then schedule.storageWrite else 0

            def postAccessExecutionCharge (schedule : Schedule) (input : StorageSituation) : Nat :=
              (price schedule input).executionCharge - accessCost schedule input.access

            def commitSStore (schedule : Schedule) (input : StorageSituation) (cell : Cell)
                (newValue : UInt256) (state : MachineState) : MachineState :=
              let effect := price schedule input
              let afterClear := adjustRefund (clearRefundAdjustment schedule input) state
              let afterReversal := adjustRefund (clearRefundReversal schedule input) afterClear
              let afterStateRefund := creditMachineStateRefund effect.stateRefill afterReversal
              let afterRestore := adjustRefund (restoreOriginalRefund schedule input) afterStateRefund
              let afterWrite := { afterRestore with storage := writeCurrent afterRestore.storage cell newValue }
              record afterWrite (.storageWritten cell newValue)

            def executeSLoad (schedule : Schedule) (state : MachineState) : Outcome :=
              let entered := advancePc state
              match chargeExecution schedule.sloadBase entered.gas with
              | .error _ => { status := .outOfGas, state := exhaustExecutionGas entered }
              | .ok gasAfterBase =>
                let afterBase := record { entered with gas := gasAfterBase }
                  (.sloadBaseCharged schedule.sloadBase)
                match afterBase.stack.pop with
                | none => { status := .stackUnderflow, state := afterBase }
                | some (key, tail) =>
                  let cell := { address := entered.executingAccount, key }
                  let afterPop := record { afterBase with stack := tail } (.keyPopped key)
                  let access := accessStatus afterPop.warmCells cell
                  let cost := accessCost schedule access
                  match chargeExecution cost afterPop.gas with
                  | .error _ => { status := .outOfGas, state := exhaustExecutionGas afterPop }
                  | .ok gasAfterAccess =>
                    let afterAccess := record
                      { afterPop with gas := gasAfterAccess
                                      warmCells := warmCell afterPop.warmCells cell }
                      (.accessCharged cell access cost)
                    let value := readCurrent afterAccess.storage cell
                    let afterRead := record afterAccess (.currentRead cell value)
                    match afterRead.stack.push value with
                    | none => { status := .stackOverflow, state := afterRead }
                    | some stackAfter =>
                      { status := .ok
                        state := record { afterRead with stack := stackAfter } (.valuePushed value) }

            def executeSStore (schedule : Schedule) (isStatic : Bool) (state : MachineState) : Outcome :=
              let entered := advancePc state
              if isStatic then
                { status := .staticCallViolation, state := entered }
              else if entered.gas.gasLeft ≤ schedule.sstoreStipend then
                { status := .outOfGas, state := entered }
              else
                match entered.stack.pop with
                | none => { status := .stackUnderflow, state := entered }
                | some (key, afterKeyStack) =>
                  let afterKey := record { entered with stack := afterKeyStack } (.keyPopped key)
                  match afterKey.stack.pop with
                  | none => { status := .stackUnderflow, state := afterKey }
                  | some (newValue, afterValueStack) =>
                    let afterValue := record { afterKey with stack := afterValueStack } (.valuePopped newValue)
                    let cell := { address := entered.executingAccount, key }
                    let access := accessStatus afterValue.warmCells cell
                    let cost := accessCost schedule access
                    match chargeExecution cost afterValue.gas with
                    | .error _ => { status := .outOfGas, state := exhaustExecutionGas afterValue }
                    | .ok gasAfterAccess =>
                      let afterAccess := record
                        { afterValue with gas := gasAfterAccess
                                          warmCells := warmCell afterValue.warmCells cell }
                        (.accessCharged cell access cost)
                      let current := readCurrent afterAccess.storage cell
                      let afterCurrent := record afterAccess (.currentRead cell current)
                      if newValue = current then
                        { status := .ok, state := record afterCurrent .netMeteredNoOp }
                      else
                        let original := readOriginal afterCurrent.storage cell
                        let afterOriginal := record afterCurrent (.originalRead cell original)
                        let input : StorageSituation := { original, current, newValue, access }
                        let effect := price schedule input
                        let executionWrite := postAccessExecutionCharge schedule input
                        match chargeExecution executionWrite afterOriginal.gas with
                        | .error _ => { status := .outOfGas, state := exhaustExecutionGas afterOriginal }
                        | .ok gasAfterExecution =>
                          let afterExecution := record { afterOriginal with gas := gasAfterExecution }
                            (.executionWriteCharged executionWrite)
                          match chargeState effect.stateCharge afterExecution.gas with
                          | .error _ => { status := .outOfGas, state := afterExecution }
                          | .ok gasAfterState =>
                            let afterState := record { afterExecution with gas := gasAfterState }
                              (.stateCharged effect.stateCharge)
                            { status := .ok, state := commitSStore schedule input cell newValue afterState }

            def execute (schedule : Schedule) (isStatic : Bool) (opcode : Nat)
                (state : MachineState) : Outcome :=
              if opcode = opcodeByte .sload then executeSLoad schedule state
              else if opcode = opcodeByte .sstore then executeSStore schedule isStatic state
              else { status := .badInstruction, state := advancePc state }

            end Eip803x.Generated.PersistentStorageOpcodeKernel
            """;

        return Utf8WithoutBom.GetBytes(source.Replace("\r\n", "\n", StringComparison.Ordinal));
    }

    internal static void Validate(IrDocument document)
    {
        if (document is null || document.Reachability is null || document.ExecutionMode is null ||
            document.Schedule is null || document.Opcodes is null || document.Specializations is null ||
            document.ComposedGeneratedDependencies is null || document.OpenExtractionObligations is null ||
            document.Opcodes.Any(static opcode => opcode is null || opcode.OrderedEffects is null ||
                opcode.OrderedEffects.Any(static effect => effect is null)) ||
            document.Specializations.Any(static specialization => specialization is null ||
                specialization.Opcode is null || specialization.Table is null ||
                specialization.TracingFlag is null || specialization.CancellationFlag is null ||
                specialization.ClosedRoot is null) ||
            document.ComposedGeneratedDependencies.Any(static dependency => dependency is null) ||
            document.OpenExtractionObligations.Any(static obligation => obligation is null))
            throw new ExtractionException("The round-tripped persistent-storage IR contains null collections, entries, or fields.");

        if (document.SchemaVersion != 1 || document.ExtractorVersion != "1.0.0" ||
            document.Kernel != "Nethermind standard-mainnet Amsterdam SLOAD/SSTORE immediate-handler slice" ||
            document.Opcodes.Length != 2 || document.Specializations.Length != 8)
            throw new ExtractionException("The round-tripped persistent-storage IR has an unsupported shape.");

        ReachabilityDescriptor expectedReachability = new(
            "IVirtualMachine", "EthereumVirtualMachine", "VirtualMachine<EthereumGasPolicy>",
            "EthereumGasPolicy", "Amsterdam",
            "Directory.Build.targets selects *.std.cs when EnableZkEvm != true",
            "VirtualMachine<EthereumGasPolicy>.ExecuteOpcode");
        if (document.Reachability != expectedReachability)
            throw new ExtractionException("The serialized IR contains an unsupported standard-mainnet reachability root.");
        ExecutionModeDescriptor expectedExecutionMode = new(
            false,
            "Normal consensus execution only; VM.IsTracingAccess must be false because access-list tracing uses the distinct warm-cost path.");
        if (document.ExecutionMode != expectedExecutionMode)
            throw new ExtractionException("The serialized IR contains an unsupported persistent-storage execution mode.");
        if (document.Schedule != new GasScheduleDescriptor(0, 2100, 100, 10000, 11616, 97920, 2300))
            throw new ExtractionException("The serialized IR contains an unsupported Amsterdam persistent-storage schedule.");

        OpcodeDescriptor[] expectedOpcodes =
        [
            new("sload", "SLOAD", 0x54,
                "SLoadOpcode<TTracingInst,Eip8038On,OnFlag>",
                "EvmInstructions.InstructionSLoad<TGasPolicy,TTracingInst,Eip8038On,OnFlag>",
                1, 1, "always assigned; Amsterdam closes EIP-2929 and EIP-8038 on",
                ["advancePc", "chargeZeroBase", "popKey", "chargeAndWarmAccess", "readCurrent", "pushValue"]),
            new("sstore", "SSTORE", 0x55,
                "SStoreMeteredOpcode<TTracingInst,OnFlag,OnFlag,Eip8038On,OnFlag>",
                "EvmInstructions.InstructionSStoreMetered<TGasPolicy,TTracingInst,OnFlag,OnFlag,Eip8038On,OnFlag>",
                2, 0, "always assigned; Amsterdam closes EIP-2200, EIP-2929, EIP-8037, and EIP-8038 on",
                ["advancePc", "staticCheck", "stipendCheck", "popKey", "popValue", "chargeAndWarmAccess",
                 "readCurrent", "readOriginalOnChange", "priceAfterAccess", "chargeExecutionThenState",
                 "clearRefund", "clearRefundReversal", "stateRefill", "restoreOriginalRefund", "writeOnChange"]),
        ];
        if (document.Opcodes.Length != expectedOpcodes.Length)
            throw new ExtractionException("The serialized IR contains an unsupported opcode count.");
        for (int index = 0; index < expectedOpcodes.Length; index++)
        {
            OpcodeDescriptor actual = document.Opcodes[index];
            OpcodeDescriptor expected = expectedOpcodes[index];
            if ((actual with { OrderedEffects = expected.OrderedEffects }) != expected ||
                !actual.OrderedEffects.SequenceEqual(expected.OrderedEffects, StringComparer.Ordinal))
                throw new ExtractionException($"The serialized IR contains an unsupported {actual.Name} descriptor.");
        }

        DispatchSpecialization[] expectedSpecializations =
        [
            ExpectedSpecialization("sload", "NoTrace", "OffFlag", "OffFlag", "SLoadOpcode<OffFlag,Eip8038On,OnFlag>"),
            ExpectedSpecialization("sstore", "NoTrace", "OffFlag", "OffFlag", "SStoreMeteredOpcode<OffFlag,OnFlag,OnFlag,Eip8038On,OnFlag>"),
            ExpectedSpecialization("sload", "NoTraceCancelable", "OffFlag", "OnFlag", "SLoadOpcode<OffFlag,Eip8038On,OnFlag>"),
            ExpectedSpecialization("sstore", "NoTraceCancelable", "OffFlag", "OnFlag", "SStoreMeteredOpcode<OffFlag,OnFlag,OnFlag,Eip8038On,OnFlag>"),
            ExpectedSpecialization("sload", "Traced", "OnFlag", "OffFlag", "SLoadOpcode<OnFlag,Eip8038On,OnFlag>"),
            ExpectedSpecialization("sstore", "Traced", "OnFlag", "OffFlag", "SStoreMeteredOpcode<OnFlag,OnFlag,OnFlag,Eip8038On,OnFlag>"),
            ExpectedSpecialization("sload", "TracedCancelable", "OnFlag", "OnFlag", "SLoadOpcode<OnFlag,Eip8038On,OnFlag>"),
            ExpectedSpecialization("sstore", "TracedCancelable", "OnFlag", "OnFlag", "SStoreMeteredOpcode<OnFlag,OnFlag,OnFlag,Eip8038On,OnFlag>"),
        ];
        HashSet<(string Opcode, string Table)> keys = [];
        foreach (DispatchSpecialization specialization in document.Specializations)
        {
            if (!keys.Add((specialization.Opcode, specialization.Table)))
                throw new ExtractionException($"The serialized IR duplicates dispatch key {specialization.Opcode}/{specialization.Table}.");
            if (specialization.ClosedRoot.Contains("/", StringComparison.Ordinal))
                throw new ExtractionException("The serialized IR contains a placeholder dispatch root.");
        }
        if (!document.Specializations.SequenceEqual(expectedSpecializations))
            throw new ExtractionException("The serialized IR does not contain the eight exact SLOAD/SSTORE dispatch specializations.");

        string[] expectedDependencies =
        [
            "Eip803x.Generated.SStorePricingKernel with Eip803x.Refinement.SStorePricing",
            "Eip803x.Generated.StateGasChargeKernel with Eip803x.Refinement.StateGasCharge",
            "Eip803x.Generated.StateGasTransitionAdapterKernel with Eip803x.Refinement.StateGasTransitionAdapterKernel",
        ];
        if (!document.ComposedGeneratedDependencies.SequenceEqual(expectedDependencies, StringComparer.Ordinal) ||
            !document.OpenExtractionObligations.SequenceEqual(ExpectedOpenExtractionObligations, StringComparer.Ordinal))
            throw new ExtractionException("The serialized IR changed its dependency or trust-boundary declarations.");
    }

    private static DispatchSpecialization ExpectedSpecialization(
        string opcode, string table, string tracing, string cancellation, string handler) =>
        new(opcode, table, tracing, cancellation,
            $"VirtualMachine<EthereumGasPolicy>.ExecuteOpcode<{handler},{tracing},{cancellation},OnFlag>");

    private static string LeanString(string value) =>
        $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";
}
