// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System.Text;

namespace Nethermind.Evm.Lean.OrdinaryTransactionMachineExtractor;

/// <summary>Emits the small theorem-free ordinary success machine from the semantic IR.</summary>
/// <remarks>
/// The emitter deliberately owns the generated types and event vocabulary. It consumes source
/// identities and typed anchor identities from the IR, while effectful CLR calls remain explicit
/// opaque observations in <c>NormalReturnPremises</c> and <c>SettledEntry</c>.
/// </remarks>
internal static class LeanEmitter
{
    internal static byte[] Emit(IrDocument document, string irSha256)
    {
        List<string> lines = [];
        void Line(string text = "") => lines.Add(text);
        void LeanStringList(string name, IEnumerable<string> values)
        {
            Line($"def {name} : List String := [");
            foreach (string value in values) Line($"  \"{Escape(value)}\",");
            Line("]");
        }

        Line("-- SPDX-License-Identifier: LGPL-3.0-only");
        Line();
        Line("-- This file is generated. Do not edit.");
        Line($"-- Extractor version: {Escape(document.ExtractorVersion)}");
        Line($"-- Semantic IR SHA-256: {Escape(irSha256)}");
        Line($"-- Source closure SHA-256: {Escape(document.SourceClosureSha256)}");
        Line($"-- Compiler closure SHA-256: {Escape(document.CompilerClosureSha256)}");
        Line("-- Scope: adapter-supplied OnlyOkTerminal ordinary exact-Commit simple-transfer fold.");
        Line("-- C# execution, EVM frames, CREATE, BAL/parallel, roots, RLP, persistence and CLR behavior are excluded.");
        Line();
        Line("import ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel");
        Line();
        Line("namespace OrdinaryTransactionMachineExtractor.Generated");
        Line();
        Line("abbrev TerminalReceipt := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.Receipt");
        Line("abbrev TerminalGasTotals := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.GasTotals");
        Line("abbrev TerminalGas := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.Gas");
        Line("abbrev TerminalState := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.State");
        Line("abbrev TerminalBlock := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.BlockInput");
        Line("abbrev TerminalTransaction := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.TransactionInput");
        Line("abbrev TerminalStatus := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.Status");
        Line("abbrev TerminalResult := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.TransactionResult");
        Line("abbrev TerminalAddress := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.AddressOracle");
        Line("abbrev TerminalBytes := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.BytesOracle");
        Line("abbrev TerminalLog := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.LogOracle");
        Line("abbrev TerminalHash := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.HashOracle");
        Line("abbrev TerminalException := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.EvmExceptionOracle");
        Line("abbrev TerminalError := ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.ErrorOracle");
        Line();
        Line($"def semanticIrSha256 : String := \"{Escape(irSha256)}\"");
        Line($"def sourceClosureSha256 : String := \"{Escape(document.SourceClosureSha256)}\"");
        Line($"def compilerClosureSha256 : String := \"{Escape(document.CompilerClosureSha256)}\"");
        LeanStringList("sourcePaths", document.Sources.Select(static source => source.Path));
        LeanStringList("dependencyPaths", document.Dependencies.Select(static dependency => dependency.Path));
        LeanStringList("sourceAnchors", document.Machine.Anchors.Select(static anchor => anchor.Id));
        LeanStringList("semanticOperationIds", document.Machine.SemanticOperations.Select(static operation => operation.Id));
        LeanStringList("fieldwiseSeamIds", document.Machine.FieldwiseSeams.Select(static seam => seam.Id));
        LeanStringList("sourceStages", document.Machine.Stages);
        LeanStringList("excludedBranches", document.Machine.ExcludedBranches);
        Line();
        Line("structure Block where");
        Line("  terminal : TerminalBlock");
        Line("  headerGasUsed : Nat");
        Line("  standardMainnet : Bool");
        Line("  chainId : Nat");
        Line("  forkNumber : Nat");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("structure TracerSeed where");
        Line("  receipts : List TerminalReceipt");
        Line("  gasHistory : List TerminalGasTotals");
        Line("  cumulativeReceiptGas : Nat");
        Line("  headerGasUsed : Nat");
        Line("  currentIndex : Nat");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("structure MachineInput where");
        Line("  block : Block");
        Line("  optionsRaw : Nat");
        Line("  isSystem : Bool");
        Line("  parallel : Bool");
        Line("  balEnabled : Bool");
        Line("  isCreate : Bool");
        Line("  isCodeOverridable : Bool");
        Line("  hasAuthorizationList : Bool");
        Line("  forceSimpleTransferDisabled : Bool");
        Line("  recipientLive : Bool");
        Line("  recipientHasCode : Bool");
        Line("  recipientHasDelegation : Bool");
        Line("  tracerSeed : TracerSeed");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("structure EntryNormality where");
        Line("  startNewTxTrace : Bool");
        Line("  execute : Bool");
        Line("  endTxTrace : Bool");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("def EntryNormality.valid (entry : EntryNormality) : Bool :=");
        Line("  entry.startNewTxTrace && entry.execute && entry.endTxTrace");
        Line();
        Line("structure NormalReturnPremises where");
        Line("  setBlockExecutionContext : Bool");
        Line("  process : Bool");
        Line("  executeCore : Bool");
        Line("  ordinaryExecute : Bool");
        Line("  staticAdmission : Bool");
        Line("  statefulAdmission : Bool");
        Line("  nonceAndPreparation : Bool");
        Line("  preExecutionCommit : Bool");
        Line("  availableGas : Bool");
        Line("  executeSimpleTransfer : Bool");
        Line("  settlement : Bool");
        Line("  transactionCommit : Bool");
        Line("  finalizeTransaction : Bool");
        Line("  executorReturn : Bool");
        Line("  transactionsExecutedSubscriber : Bool");
        Line("  postTransactionCommitState : Bool");
        Line("  receiptTerminal : Bool");
        Line("  entries : List EntryNormality");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("def NormalReturnPremises.all (premises : NormalReturnPremises) : Bool :=");
        Line("  premises.setBlockExecutionContext && premises.process && premises.executeCore &&");
        Line("  premises.ordinaryExecute && premises.staticAdmission && premises.statefulAdmission &&");
        Line("  premises.nonceAndPreparation && premises.preExecutionCommit && premises.availableGas &&");
        Line("  premises.executeSimpleTransfer && premises.settlement && premises.transactionCommit &&");
        Line("  premises.finalizeTransaction && premises.executorReturn &&");
        Line("  premises.transactionsExecutedSubscriber && premises.postTransactionCommitState &&");
        Line("  premises.receiptTerminal");
        Line();
        Line("structure SettledEntry where");
        Line("  transaction : TerminalTransaction");
        Line("  receipt : TerminalReceipt");
        Line("  gasTotals : TerminalGasTotals");
        Line("  recipient : TerminalAddress");
        Line("  gas : TerminalGas");
        Line("  output : TerminalBytes");
        Line("  logs : List TerminalLog");
        Line("  stateRoot : Option TerminalHash");
        Line("  status : TerminalStatus");
        Line("  result : TerminalResult");
        Line("  nestedTracer : Bool");
        Line("  currentTxTracerIsTracingReceipt : Bool");
        Line("  wellFormed : Bool");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("def NormalReturnPremises.validFor (premises : NormalReturnPremises)");
        Line("    (entries : List SettledEntry) : Bool :=");
        Line("  premises.all && (premises.entries.length == entries.length) &&");
        Line("  (premises.entries.map EntryNormality.valid).all (fun value => value)");
        Line();
        Line("def resultIsOk : TerminalResult → Bool");
        Line("  | .ok => true");
        Line("  | .evmException _ _ => false");
        Line();
        Line("def statusIsSuccess : TerminalStatus → Bool");
        Line("  | .success => true");
        Line("  | .failure => false");
        Line();
        Line("def onlyOkTerminal (entry : SettledEntry) : Bool :=");
        Line("  entry.wellFormed && resultIsOk entry.result && statusIsSuccess entry.status");
        Line();
        Line("def lastReceipt : List TerminalReceipt → Option TerminalReceipt");
        Line("  | [] => none");
        Line("  | [last] => some last");
        Line("  | _ :: tail => lastReceipt tail");
        Line();
        Line("def lastGasTotals : List TerminalGasTotals → Option TerminalGasTotals");
        Line("  | [] => none");
        Line("  | [last] => some last");
        Line("  | _ :: tail => lastGasTotals tail");
        Line();
        Line("def receiptObservationMatches (actual expected : TerminalReceipt) : Bool :=");
        Line("  actual.logs == expected.logs && actual.txType == expected.txType &&");
        Line("  actual.gasUsedTotal == expected.gasUsedTotal && actual.statusCode == expected.statusCode &&");
        Line("  actual.recipient == expected.recipient && actual.blockHash == expected.blockHash &&");
        Line("  actual.blockNumber == expected.blockNumber && actual.index == expected.index &&");
        Line("  actual.gasUsed == expected.gasUsed &&");
        Line("  actual.effectiveGasPrice == expected.effectiveGasPrice && actual.sender == expected.sender &&");
        Line("  actual.contractAddress == expected.contractAddress && actual.txHash == expected.txHash &&");
        Line("  actual.postTransactionState == expected.postTransactionState &&");
        Line("  actual.blockGasUsed == expected.blockGasUsed && actual.executionGasUsed == expected.executionGasUsed &&");
        Line("  actual.storageGasUsed == expected.storageGasUsed && actual.error == expected.error");
        Line();
        Line("def gasTotalsObservationMatches (actual expected : TerminalGasTotals) : Bool :=");
        Line("  actual.executionGas == expected.executionGas && actual.stateGas == expected.stateGas");
        Line();
        Line("def freshSequentialTracer (seed : TracerSeed) (headerGasUsed : Nat) : TerminalState :=");
        Line("  { receipts := []");
        Line("    gasHistory := []");
        Line("    cumulativeReceiptGas := 0");
        Line("    headerGasUsed := headerGasUsed");
        Line("    parallel := false");
        Line("    currentIndex := 0 }");
        Line();
        Line("def startNewBlockTrace (input : MachineInput) : TerminalState :=");
        Line("  freshSequentialTracer input.tracerSeed input.block.headerGasUsed");
        Line();
        Line("def freshTracerInvariant (input : MachineInput) (state : TerminalState) : Prop :=");
        Line("  state.parallel = false ∧ state.currentIndex = 0 ∧ state.receipts = [] ∧");
        Line("  state.gasHistory = [] ∧ state.cumulativeReceiptGas = 0 ∧");
        Line("  state.headerGasUsed = input.block.headerGasUsed");
        Line();
        Line("def routeValid (input : MachineInput) : Bool :=");
        Line("  input.optionsRaw == 1 && input.block.standardMainnet && input.block.chainId == 1 &&");
        Line("  input.block.forkNumber == 25 && !input.isSystem && !input.parallel && !input.balEnabled &&");
        Line("  !input.isCreate && !input.isCodeOverridable && !input.hasAuthorizationList &&");
        Line("  !input.forceSimpleTransferDisabled && input.recipientLive && !input.recipientHasCode &&");
        Line("  !input.recipientHasDelegation");
        Line();
        Line("inductive Event where");
        Line("  | blockStart");
        Line("  | preTransactionCommit");
        Line("  | foldStart");
        Line("  | startNewTxTrace");
        Line("  | execute");
        Line("  | transactionCommit");
        Line("  | gasMutation");
        Line("  | receiptAppend");
        Line("  | nestedTracerForward");
        Line("  | currentTracerForward");
        Line("  | endTxTrace");
        Line("  | currentIndexIncrement");
        Line("  | foldReturn");
        Line("  | transactionsExecuted");
        Line("  | postTransactionCommit");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("def mapTerminalEvent : ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.Event → Event");
        Line("  | .gasMutation => .gasMutation");
        Line("  | .receiptAppend => .receiptAppend");
        Line("  | .nestedTracerForward => .nestedTracerForward");
        Line("  | .currentTracerForward => .currentTracerForward");
        Line();
        Line("def terminalForwardingEvents (entry : SettledEntry) : List Event :=");
        Line("  (ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.forwardingEvents");
        Line("    entry.nestedTracer entry.currentTxTracerIsTracingReceipt).map mapTerminalEvent");
        Line();
        Line("inductive RejectReason where");
        Line("  | route");
        Line("  | normalReturn");
        Line("  | malformedSettled");
        Line("  | invalidResult");
        Line("  | exceptionResult");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("inductive Outcome where");
        Line("  | rejected (reason : RejectReason) (state : TerminalState) (events : List Event)");
        Line("      (processed : List TerminalResult)");
        Line("  | completed (state : TerminalState) (events : List Event)");
        Line("      (results : List TerminalResult)");
        Line("  deriving DecidableEq, Repr");
        Line();
        Line("def foldEntries (block : Block) (state : TerminalState) (events : List Event)");
        Line("    (processed : List TerminalResult) : List SettledEntry → Outcome");
        Line("  | [] => .completed state events processed");
        Line("  | entry :: tail =>");
        Line("      if !entry.wellFormed then");
        Line("        .rejected .malformedSettled state events processed");
        Line("      else if !resultIsOk entry.result then");
        Line("        .rejected (match entry.result with | .ok => .invalidResult | .evmException _ _ => .exceptionResult)");
        Line("          state events processed");
        Line("      else if !statusIsSuccess entry.status then");
        Line("        .rejected .malformedSettled state events processed");
        Line("      else");
        Line("        let terminal :=");
        Line("          ReceiptTerminalFoldExtractor.Generated.ReceiptTerminalFoldKernel.markAsSuccess");
        Line("            state block.terminal entry.transaction entry.recipient entry.gas entry.output");
        Line("            entry.logs entry.stateRoot entry.nestedTracer entry.currentTxTracerIsTracingReceipt");
        Line("        let nextState := { terminal.state with currentIndex := state.currentIndex + 1 }");
        Line("        match lastReceipt terminal.state.receipts, lastGasTotals terminal.state.gasHistory with");
        Line("        | some receipt, some totals =>");
        Line("            if !receiptObservationMatches receipt entry.receipt ||");
        Line("                !gasTotalsObservationMatches totals entry.gasTotals then");
        Line("              .rejected .malformedSettled state events processed");
        Line("            else");
        Line("              let nextEvents := events ++ [Event.startNewTxTrace, Event.execute, Event.transactionCommit] ++");
        Line("                terminal.events.map mapTerminalEvent ++ [Event.endTxTrace, Event.currentIndexIncrement]");
        Line("              foldEntries block nextState nextEvents (processed ++ [entry.result]) tail");
        Line("        | _, _ => .rejected .malformedSettled state events processed");
        Line();
        Line("def run (input : MachineInput) (premises : NormalReturnPremises)");
        Line("    (entries : List SettledEntry) : Outcome :=");
        Line("  let initial := startNewBlockTrace input");
        Line("  let initialEvents := [Event.blockStart, Event.preTransactionCommit, Event.foldStart]");
        Line("  if !routeValid input then");
        Line("    .rejected .route initial initialEvents []");
        Line("  else if !premises.validFor entries then");
        Line("    .rejected .normalReturn initial initialEvents []");
        Line("  else");
        Line("    match foldEntries input.block initial initialEvents [] entries with");
        Line("    | .rejected reason state events processed =>");
        Line("        .rejected reason state (events ++ [Event.foldReturn]) processed");
        Line("    | .completed state events results =>");
        Line("        .completed state (events ++ [Event.foldReturn, Event.transactionsExecuted,");
        Line("          Event.postTransactionCommit]) results");
        Line();
        Line("def receiptIndices (state : TerminalState) : List Nat :=");
        Line("  state.receipts.map (fun receipt => receipt.index)");
        Line();
        Line("def receiptGasTotals (state : TerminalState) : List Nat :=");
        Line("  state.receipts.map (fun receipt => receipt.gasUsedTotal)");
        Line();
        Line("def sequentialIndexInvariant (state : TerminalState) : Prop :=");
        Line("  state.receiptIndices = List.range state.receipts.length");
        Line();
        Line("def gasHistoryLengthsMatch (state : TerminalState) : Prop :=");
        Line("  state.receipts.length = state.gasHistory.length");
        Line();
        Line("def onlyOkSuccess (input : MachineInput) (premises : NormalReturnPremises)");
        Line("    (entries : List SettledEntry) : Prop :=");
        Line("  routeValid input = true ∧ premises.validFor entries = true ∧");
        Line("  entries.all onlyOkTerminal = true");
        Line();
        Line("end OrdinaryTransactionMachineExtractor.Generated");
        Line();

        return new UTF8Encoding(encoderShouldEmitUTF8Identifier: false)
            .GetBytes(string.Join('\n', lines) + "\n");
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal);
}
