<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Nethermind.Evm.Test" />
    <PackageReference Include="FodyHelpers" PrivateAssets="all" />
  </ItemGroup>
</Project>
