// SPDX-FileCopyrightText: 2022 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using Nethermind.Config;

namespace Nethermind.Wallet;

public interface IWalletConfig : IConfig
{
    [ConfigItem(DefaultValue = "10", Description = "The number of autogenerated developer accounts to work with. Developer accounts have private keys from `00...01` to `00...n`.")]
    int DevAccounts { get; set; }
}
