<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../tests.props" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nethermind.FFI\Nethermind.FFI.csproj" />
    <ProjectReference Include="..\Nethermind.Core.Test\Nethermind.Core.Test.csproj" />
  </ItemGroup>

</Project>
