name = "PushOpcodeExtractor"
version = "0.1.0"
defaultTargets = ["PushOpcodeExtractor.Refinement.PushOpcode"]

[[lean_lib]]
name = "Eip803x"
srcDir = ".."

[[lean_lib]]
name = "PushOpcodeExtractor"
srcDir = ".."
