<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Nethermind.EraManifest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nethermind\Nethermind.Era1\Nethermind.Era1.csproj" />
  </ItemGroup>

</Project>
