name: Publish Debian amd64 image to docker registry

on:
  repository_dispatch:
    types: docker_amd64_debian

jobs:
  amd64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Unshallow fetching
        run: git fetch --unshallow
      - name: Settings
        id: settings
        run: |
          TAG=$(git describe --tags --always | cut -d- -f1)
          echo ::set-output name=tag_name::${TAG}
          echo ::set-output name=docker_username::${{ secrets.DOCKER_USERNAME }}
          echo ::set-output name=docker_image::nethermind/nethermind
      - name: Set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker Login
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.settings.outputs.docker_username }}" --password-stdin
      - name: Build & Push image to docker registry
        run: |
          docker buildx build --platform=linux/amd64 -t "${{ steps.settings.outputs.docker_image }}:latest" -t "${{ steps.settings.outputs.docker_image }}:${{ steps.settings.outputs.tag_name }}" -f Dockerfile . --push
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json