name: Publish ARM64 Image to Docker Registry

on:
  push:
    tags:
    - '*'

jobs:
  arm64_building:
    runs-on: [self-hosted, linux, ARM64]
    name: Build on ARM64
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - name: Publish to Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GIT_COMMIT: $(git log -1 --format=%h)
      with:
        name: nethermind/nethermind:arm64
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        build-args: GIT_COMMIT
        dockerfile: Dockerfile_alpine_arm64