name: BLS test

on:
  push:
    branches:
    - github-actions

jobs:
  neth-tests:
    name: bls
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Cloning required repositories
      run: |
        git clone git://github.com/NethermindEth/bls
        git clone git://github.com/herumi/mcl.git
    - name: Installing GMP for ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libgmp-dev
    - name: Installing GMP for osx
      if: matrix.os == 'macOS-latest'
      run: |
        brew install gmp
    - name: Cloning lib for Windows
      if: matrix.os == 'windows-latest'
      run: |
        git clone git://github.com/herumi/cybozulib_ext 
    - name: Building BLS for Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install make
        cd bls/
        make all
    - name: Building BLS for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd bls/
        make test
    - name: Building BLS for OSX
      if: matrix.os == 'macOS-latest'
      run: |
        cd bls/
        make all

