name: BLS test

on:
  push:
    branches:
    - github-actions

jobs:
  neth-tests:
    name: bls
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Cloning required repositories
      run: |
        git clone git://github.com/NethermindEth/bls.git
        git clone git://github.com/herumi/mcl.git
    - name: Installing GMP for ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libgmp-dev
    - name: Installing GMP for osx
      if: matrix.os == 'macOS-latest'
      run: |
        brew install gmp
    - name: Cloning lib for Windows
      if: matrix.os == 'windows-latest'
      run: |
        git clone git://github.com/herumi/cybozulib_ext.git
    - name: Building BLS for Windows
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd D:\a\nethermind\nethermind\mcl && call mklib.bat dll
        cd D:\a\nethermind\nethermind\mcl && call mk -d test\bls12_test.cpp
        cd D:\a\nethermind\nethermind\mcl && call bin\bls12_test.exe
        cd D:\a\nethermind\nethermind\bls && call mklib.bat dll
        cd D:\a\nethermind\nethermind\bls && call mk -d test\bls_c384_test.cpp
        cd D:\a\nethermind\nethermind\bls && call bin\bls_c384_test.exe
      shell: cmd
    - name: Building BLS for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd bls/
        make test
    - name: Building BLS for OSX
      if: matrix.os == 'macOS-latest'
      run: |
        cd bls/
        make all

