name: '[BUILD] Nethtest/Hive images and publisg them to Docker Hub'

on:
  push:
    branches:
      - master

jobs:
  build-secondary-dockers:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Unshallow fetching
        run: git fetch --unshallow
      - name: Settings
        id: settings
        run: |
          echo "BUILD_TIMESTAMP=$(date '+%s')" >> $GITHUB_OUTPUT
          echo "COMMIT_HASH=$(git describe --always --exclude=* --abbrev=40)" >> $GITHUB_OUTPUT
      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Logging to Docker Hub
        if: success()
        run: |
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Building & Pushing image to docker registry
        run: |
          docker buildx build --platform=linux/amd64 -t nethermindeth/nethtest -f Dockerfile.stateRunner . --push
          docker buildx build --platform=linux/amd64 -t nethermindeth/hive:latest -f Dockerfile --build-arg COMMIT_HASH=${{ steps.settings.outputs.COMMIT_HASH }} --build-arg BUILD_TIMESTAMP=${{ steps.settings.outputs.BUILD_TIMESTAMP}} . --push
      - name: Clearing
        if: always()
        run: |
          rm -f $HOME/.docker/config.json
