name: Build tools

on:
  push:
    branches: [test/satori]
  workflow_dispatch:
  

jobs:
  run:
    name: Build Satori
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          repository: VSadov/Satori
      - name: Build
        run: |
          ./build.sh clr -c Release
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: coreclr
          path: "${{ github.workspace }}/artifacts/bin/coreclr/*"

      

