name: Build solutions

on:
  
  push:
    branches: [test/nuget-lock]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [release]
        solution: [Nethermind, EthereumTests, Benchmarks]
    steps:
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
          tool-cache: false
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: ${{ matrix.solution == 'EthereumTests' }}
      - name: Set up .NET
        with:
          cache: true
          cache-dependency-path: src/Nethermind/Nethermind.Runner/packages.lock.json
        uses: actions/setup-dotnet@v4
      - name: Build ${{ matrix.solution }}.sln
        run: dotnet build src/Nethermind/${{ matrix.solution }}.sln -c ${{ matrix.config }}
