name: '[BUILD] Secp256k1 Libraries'

on:
  workflow_dispatch:

jobs:
  build-secp256k1:
    name: Building Secp256k1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
    - name: Cloning secp256k1 repository
      run: |
        git clone https://github.com/NethermindEth/secp256k1
    - name: Building secp256k1 for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install autoconf libtool
        cd secp256k1/
        ./autogen.sh
        ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
        make -j8
        strip .libs/libsecp256k1.so
    - uses: actions/upload-artifact@v1
      name: Uploading Linux artifact
      if: matrix.os == 'ubuntu-latest'
      with:
        name: linux_artifact_secp256k1
        path: secp256k1/.libs/libsecp256k1.so
    - name: Building secp256k1 for OSX
      if: matrix.os == 'macOS-latest'
      run: |
        brew install automake
        brew install libtool
        brew install gmp
        cd secp256k1/
        ./autogen.sh
        ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
        make -j8
    - uses: actions/upload-artifact@v1
      name: Uploading Darwin artifact
      if: matrix.os == 'macOS-latest'
      with:
        name: darwin_artifact_secp256k1
        path: secp256k1/.libs/libsecp256k1.dylib
    - uses: msys2/setup-msys2@v2
      if: matrix.os == 'windows-latest'
      with:
        update: true
        install: autoconf libtool make automake gcc mingw-w64-x86_64-gcc base-devel
      name: Setting up msys2 for Windows
    - run: |
        cat <<EOT >> run.sh
        mv secp256k1 64bit
        cd 64bit
        ./autogen.sh 
        echo "LDFLAGS = -no-undefined" >> Makefile.am
        ./configure --host=x86_64-w64-mingw32 --enable-module-recovery --enable-experimental --enable-module-ecdh --enable-shared --with-bignum=no
        make -j8
        strip .libs/libsecp256k1-0.dll
        mv .libs/libsecp256k1-0.dll .libs/secp256k1.dll
        EOT
      if: matrix.os == 'windows-latest'
      name: Creating script for secp256k1 build
      shell: bash
    - run: ./run.sh
      if: matrix.os == 'windows-latest'
      shell: msys2 {0}
      name: Running secp256k1 build for Windows x64
    - uses: actions/upload-artifact@v1
      name: Uploading Windows artifact
      if: matrix.os == 'windows-latest'
      with:
        name: windows_artifact_secp256k1
        path: 64bit/.libs/secp256k1.dll
