name: '[BUILD] GMP Libraries'

on:
  workflow_dispatch:

jobs:
  build-gmp:
    name: Building GMP libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
    - name: Building GMP for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y mercurial
        hg clone https://gmplib.org/repo/gmp-6.2/ gmp
        sudo apt-get install autoconf libtool
        cd gmp/
        ./.bootstrap
        ./configure --host=x86_64-linux-gnu --disable-static --enable-shared
        make -j8
        strip .libs/libgmp.so
    - uses: actions/upload-artifact@v1
      name: Uploading Linux artifact
      if: matrix.os == 'ubuntu-latest'
      with:
        name: linux_artifact_gmp
        path: gmp/.libs/libgmp.so
    - name: Building gmp for OSX
      if: matrix.os == 'macOS-latest'
      run: |
        brew install mercurial
        brew install automake
        brew install libtool
        hg clone https://gmplib.org/repo/gmp-6.2/ gmp
        cd gmp/
        ./.bootstrap
        ./configure --host=none-apple-darwin --disable-static --enable-shared
        make -j8
    - uses: actions/upload-artifact@v1
      name: Uploading Darwin artifact
      if: matrix.os == 'macOS-latest'
      with:
        name: darwin_artifact_gmp
        path: gmp/.libs/libgmp.dylib
    - uses: msys2/setup-msys2@v2
      if: matrix.os == 'windows-latest'
      with:
        update: true
        install: autoconf libtool make automake gcc mingw-w64-x86_64-gcc base-devel
    - run: |
        hg clone https://gmplib.org/repo/gmp-6.2/ gmp
      name: Clone gmp repo
      shell: bash
      if: matrix.os == 'windows-latest'
    - run: |
        cd gmp/
        ./.bootstrap
        ./configure --host=x86_64-w64-mingw32 --disable-static --enable-shared
        make -j8
        strip .libs/libgmp-10.dll
        mv .libs/libgmp-10.dll .libs/libgmp.dll
        strip .libs/libgmp.dll
      if: matrix.os == 'windows-latest'
      name: Building gmp for Windows
      shell: msys2 {0}
    - uses: actions/upload-artifact@v1
      name: Uploading Windows artifact
      if: matrix.os == 'windows-latest'
      with:
        name: windows_artifact_gmp
        path: gmp/.libs/libgmp.dll
