name: '[BUILD] Nethtest/Hive images and publisg them to Docker Hub'

on:
  push:
    branches:
      - master

jobs:
  build-secondary-dockers:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Unshallow fetching
        run: git fetch --unshallow
      - name: Settings
        id: settings
        run: |
          echo ::set-output name=docker_username::${{ secrets.DOCKER_USERNAME }}
          echo ::set-output name=docker_image_nethtest::nethermindeth/nethtest
          echo ::set-output name=docker_image_hive::nethermindeth/hive
      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Logging to Docker Hub
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.settings.outputs.docker_username }}" --password-stdin
      - name: Building & Pushing image to docker registry
        run: |
          docker buildx build --platform=linux/amd64 -t "${{ steps.settings.outputs.docker_image_nethtest }}" -f Dockerfile.stateRunner --build-arg GIT_COMMIT=$(git log -1 --format=%h) . --push
          docker buildx build --platform=linux/amd64 -t "${{ steps.settings.outputs.docker_image_hive }}:latest" -f Dockerfile --build-arg GIT_COMMIT=$(git log -1 --format=%h) . --push
      - name: Clearing
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json