name: "Surge Integration Tests"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "src/Nethermind/Nethermind.Taiko/**"
      - ".github/workflows/ci-surge.yml"
      - ".github/workflows/ci-l2-integration.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration_tests:
    uses: ./.github/workflows/ci-l2-integration.yml
    secrets: inherit
    with:
      mono-repo: NethermindEth/surge-taiko-mono
      mono-dir: surge-taiko-mono
      main-ref: surge-shasta
      pacaya-ref: jmadibekov/pacaya-dummy-verifiers-fix
      shasta-ref: surge-alethia-protocol-v3.0.0
