name: Code Lint

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Check code lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          large-packages: false
          tool-cache: false

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: src/Nethermind/Nethermind.Runner/packages.lock.json

      - name: Register problem matcher
        run: echo "::add-matcher::.github/problem-matchers/dotnet-format.json"

      - name: Check code quality
        env:
          MSBUILDDISABLEGITHUBACTIONSLOGGER: true
        run: |
          set -o pipefail
          dotnet build src/Nethermind/Nethermind.slnx \
            -p:EnforceCodeStyleInBuild=true \
            -p:TreatWarningsAsErrors=false \
            -p:GenerateDocumentationFile=true \
            -p:NoWarn=CS0419%3BCS1570%3BCS1572%3BCS1573%3BCS1574%3BCS1584%3BCS1587%3BCS1591%3BCS1658%3BCS1711%3BCS1712%3BCS1723%3BCS1734%3BCS1735%3BNU1701%3BNUnit1032 2>&1 | awk '!seen[$0]++' | tee /tmp/build.log
          ! grep -qP "warning (IDE|CA)\d+" /tmp/build.log
