name: Fast Sync Auto Update

on:
  repository_dispatch:
    types: update_configs


jobs:
  configs-updating:
    name: Updating Fast Sync Settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Installing dependencies
        run: |
          sudo apt update
          sudo apt-get install software-properties-common
          sudo apt install python3.7
          sudo apt-get install python3-pip
          pip3 install setuptools
          pip3 install emoji
      - name: Updating config files
        run: |
          python3 scripts/syncSettings.py ${{ secrets.ETHERSCAN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updating Fast Sync config files
          body: |
            Config files included: 
            - mainnet.cfg
            - goerli.cfg
            - rinkeby.cfg
            - ropsten.cfg

            Properties refreshed:
            - PivotNumber
            - PivotHash
            - PivotTotalDifficulty

            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          title: "Update Fast Sync configuration in Nethermind repository"
          labels: configs
          author-name: github-actions[bot]
          author-email: 41898282+github-actions[bot]@users.noreply.github.com
          committer-name: GitHub
          committer-email: noreply@github.com
          branch: configs-update
          branch-suffix: short-commit-hash
          base: master
      - name: Checking Outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
