name: Consensus Legacy Tests

on:
  push:
    tags:
    - '*'

jobs:
  blockchain-tests:
    name: Blockchain Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow --progress --prune origin +refs/heads/*:refs/remotes/origin/*
    - name: Updating submodules
      run: git submodule update --init src/Dirichlet src/rocksdb-sharp src/tests
    - name: Installing Linux packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libsnappy-dev libc6-dev libc6
    - name: Ethereum.Blockchain.Block.Legacy
      run: |
        dotnet test -c Release src/Nethermind/Ethereum.Blockchain.Block.Legacy.Test
  general-state-tests:
    name: General State Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - name: Updating submodules
      run: git submodule update --init src/Dirichlet src/rocksdb-sharp src/tests
    - name: Ethereum.Blockchain.Legacy
      run: |
        dotnet test -c Release src/Nethermind/Ethereum.Blockchain.Legacy.Test