name: Develop Rebase
on:
  push:
    branches:
      # All pushes to this branch will trigger the task.
      - master

jobs:
  rebase_branches:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Rebase develop on master
        run: |
          git fetch --all
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase --stat origin/master develop
          git push --force origin develop
