name: Develop Rebase
on:
  push:
    branches:
      # All pushes to this branch will trigger the task.
      - master

jobs:
  rebase_branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Rebase develop on master
        run: |
          git fetch --all
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          git rebase master
          git push --force -u origin developTest
