name: Publish Nethermind Image to Docker Registry

#on:
#  push:
#    tags:
#    - '*'
on: push  

jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GIT_COMMIT: $(git log -1 --format=%h)
      with:
        name: nethermind/nethermind
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        build-args: GIT_COMMIT
        dockerfile: Dockerfile
        auto_tag: true