name: "Hive consensus tests"

on:
  push:
    branches: [release/*]

  workflow_dispatch:
    inputs:
      parallelism:
        description: 'Number of concurrently running tests in each job.'
        required: true
        default: '8'
        type: choice
        options: ['1', '2', '3', '4', '8', '16']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_hive_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        master-image:
          - master-89c5835
          - master-0b49b10
          - master-9780259
          - master-6e5a865
          - master-0fa8e47
          - master-6ab6e65
          - master-82c78e7
          - master-0d9af1a
          - master-cedb007
          - master-4ba06ad
          - master-85294fe
          - master-5324473
          - master-a705c1a
          
    steps:
      - name: Set up parameters
        run: |
          echo "PARALLELISM=${{ github.event.inputs.parallelism || '8' }}" >> $GITHUB_ENV

      - name: Check out Nethermind repository
        uses: actions/checkout@v4
        with:
          path: nethermind

      - name: Install Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libsnappy-dev libc6-dev libc6 build-essential

      - name: Set up Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '>=1.17.0'

      - name: Check out Hive repository
        uses: actions/checkout@v4
        with:
          repository: ethereum/hive
          ref: master
          path: hive

      - name: Patch Hive Dockerfile
        run: |
          tag=${{ matrix.master-image }}
          sed -i -e "s|^ARG baseimage=.*|ARG baseimage=nethermindeth/nethermind|" -e "s|^ARG tag=.*|ARG tag=$tag|" hive/clients/nethermind/Dockerfile

      - name: Build Hive
        working-directory: hive
        run: go build .

      - name: Run hive for tests - ${{ matrix.master-image }}
        continue-on-error: true
        working-directory: hive
        run: |
          IFS=',' read -ra TEST_NAMES <<< "GeneralStateTests/stEIP1559/intrinsic"
          for testName in "${TEST_NAMES[@]}"
          do
            ./hive --client nethermind --sim ethereum/consensus --sim.limit /$testName --sim.parallelism $PARALLELISM
          done
      - name: Print results
        run: |
          chmod +x nethermind/scripts/hive-results.sh
          nethermind/scripts/hive-results.sh "hive/workspace/logs/*.json"
