name: "Hive consensus tests"

on:
  push:
    branches: [release/*]

  workflow_dispatch:
    inputs:
      parallelism:
        description: 'Number of concurrently running tests in each job.'
        required: true
        default: '8'
        type: choice
        options: ['1', '2', '3', '4', '8', '16']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_hive_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        master-image:
          - master-4ecedbc
          - master-abf7c73
          - master-4dd60d8
          - master-f733f71
          - master-ee96111
          - master-c666e5e
          - master-d15a540
          - master-3b213af
          - master-39d8076
          
    steps:
      - name: Set up parameters
        run: |
          echo "PARALLELISM=${{ github.event.inputs.parallelism || '8' }}" >> $GITHUB_ENV

      - name: Check out Nethermind repository
        uses: actions/checkout@v4
        with:
          path: nethermind

      - name: Install Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libsnappy-dev libc6-dev libc6 build-essential

      - name: Set up Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '>=1.17.0'

      - name: Check out Hive repository
        uses: actions/checkout@v4
        with:
          repository: ethereum/hive
          ref: master
          path: hive

      - name: Patch Hive Dockerfile
        run: |
          tag=${{ matrix.master-image }}
          sed -i -e "s|^ARG baseimage=.*|ARG baseimage=nethermindeth/nethermind|" -e "s|^ARG tag=.*|ARG tag=$tag|" hive/clients/nethermind/Dockerfile

      - name: Build Hive
        working-directory: hive
        run: go build .

      - name: Run hive for tests - ${{ matrix.master-image }}
        continue-on-error: true
        working-directory: hive
        run: |
          IFS=',' read -ra TEST_NAMES <<< "GeneralStateTests/stEIP1559/intrinsic"
          for testName in "${TEST_NAMES[@]}"
          do
            ./hive --client nethermind --sim ethereum/consensus --sim.limit /$testName --sim.parallelism $PARALLELISM
          done
      - name: Print results
        run: |
          chmod +x nethermind/scripts/hive-results.sh
          nethermind/scripts/hive-results.sh "hive/workspace/logs/*.json"
