name: 'Run a node with selected configuration. NodeName=\"DevNode-${{ github.actor }}-${{ github.ref }}\"'

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Select a network on which You want to run a node"
        default: "mainnet"
        required: true
        type: choice
        options:
          - mainnet
          - gnosis
          - sepolia
          - goerli
          - chiado
      cl_client:
        description: "Select Consensus Layer Client to run node against"
        default: ""
        required: true
        type: choice
        options:
          - lighthouse
          - lodestar
          #- nimbus
          - prysm
          - teku
      cl_custom_image:
        description: "In case of need to run non-default cl image (different than actually supported by Sedge) put it in there"
        default: ""
        required: false        
      config:
        description: "Select a config file which will be selected for tests."
        default: "default.json"
        required: true        
        type: choice
        options:
          - default.json
          - fastSync.json
          - fullSync.json
          - fuzzer.json
      timeout:
        description: "Timeout in hours before triggering the deletion of smoke test instances"
        default: "24"
        required: true
      additional_nethermind_flags:
        description: "Provide any additional flags to the Nethermind in space-separated format. Example: \"JsonRpc.Enabled=false Sync.SnapSync=false\"."
        default: ""
        required: false
      additional_cl_flags:
        description: "Provide any additional flags to the CL client in space-separated format."
        default: ""
        required: false
      
jobs:
  create_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Docker Build Action
      uses: actions/github-script@v5
      with:
        script: |
          await github.request('POST /repos/{owner}/{repo}/dispatches', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'build_docker_image',
            client_payload: {
              branch: '${{ github.ref }}',
              inputs: {
                repo: 'nethermindeth/nethermind',
                tag: '${{ github.ref }}',
                dockerfile: 'Dockerfile'
              }
            }
          })
          
  trigger_node_and_vm_creation:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Another Repo Action
      uses: actions/github-script@v5
      with:
        script: |
          await github.request('POST /repos/{owner}/{repo}/dispatches', {
            owner: context.repo.owner,
            repo: 'post-merge-smoke-tests',
            event_type: 'run_single_node',
            client_payload: {
              branch: 'main',
              inputs: {
                github_username: '${{ github.actor }}',
                config_file: ${{ inputs.config_file }},
                nethermind_branch: ${{ inputs.nethermind_branch }},
                network: ${{ inputs.network }},
                cl_client: ${{ inputs.cl_client }},
                cl_custom_image: ${{ inputs.cl_custom_image }},
                timeout: ${{ inputs.v }},
                additional_nethermind_flags: ${{ inputs.additional_nethermind_flags }},
                additional_cl_flags: ${{ inputs.additional_cl_flags }}
              }
            }
          })        
        token: ${{ secrets.POST_MERGE_SMOKE_TESTS_WORKFLOW_TOKEN }}
