name: 'No spacing issues check'

on:
  pull_request:
  workflow_dispatch:

jobs:
  spacing-check:
    name: Check spacing changes if any
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setting up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: running dotnet format check
      run: |
        dotnet format whitespace src/Nethermind/ --folder --verify-no-changes
