name: Alert when issue is opened by external contributor

on: 
  issues:
    types: opened

jobs:
  alert-team:
    name: Alert team about an issue reported by users
    runs-on: ubuntu-latest
    env: 
      USER: ${{ github.event.issue.user.login }}
      AUTHOR_ASSOCIATION: ${{ github.event.issue.author_association }}
      ISSUE_URL: ${{ github.event.issue.url }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
    steps:
    - name: Alert Nethermind Team
      if: ${{ env.AUTHOR_ASSOCIATION == 'NONE' }}
      run: |
        MESSAGE="An issue ${{ env.ISSUE_TITLE }} has been created by a user: ${{ env.USER }}" 
        MESSAGE_FORMATTED=$(echo $MESSAGE | tr -d '"')
        curl -X POST https://api.eu.opsgenie.com/v2/alerts -H "Content-Type: application/json" -H "Authorization: GenieKey ${{ secrets.OPSGENIE_KEY }}" -d '{
          "message": "$MESSAGE_FORMATTED",
          "description":"Github issue URL: ${{ env.ISSUE_URL }}",
          "tags": ["GithubIssues"]
        }'