name: Publish packages

on:
  push:
    branches: [test/release-sign]

jobs:
  publish-ppa:
    name: Publish on PPA
    runs-on: ubuntu-latest
    steps:
      - name: Check out Nethermind repository
        uses: actions/checkout@v6
      - name: Set up GPG
        env:
          GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
          GPG_SECRET_KEY: ${{ secrets.PPA_GPG_SECRET_KEY }}
          PPA_GPG_KEYID: ${{ secrets.PPA_GPG_KEYID }}
        run: |
          # echo $GPG_SECRET_KEY > SECRET_KEY
          # echo $GPG_PASSPHRASE > $GITHUB_WORKSPACE/PASSPHRASE
          # echo "Import GPG key"
          # base64 --decode -i SECRET_KEY | gpg --import --no-tty --batch --yes
          # echo "Import GPG owner trust"
          # echo ${{ secrets.GPG_OWNERTRUST }} | base64 --decode | gpg --import-ownertrust

          printf '%s' "$GPG_SECRET_KEY" | base64 --decode | gpg --import --no-tty --batch --yes
          printf '%s' "${{ secrets.GPG_OWNERTRUST }}" | base64 --decode | gpg --import-ownertrust
          # echo "$GPG_PASSPHRASE" > "$GITHUB_WORKSPACE/PASSPHRASE"
          gpg --fingerprint 24A774616F1E617E

      - name: Download ZIP assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: curl -sL "https://github.com/NethermindEth/nethermind/releases/download/1.35.7/nethermind-1.35.7-92050c1f-linux-x64.zip" -o neth.zip

      - name: Sign ZIPs
        run: |
          for f in *.zip; do
            gpg --batch --yes --no-tty --pinentry-mode loopback \
              --passphrase-file <(printf '%s' "$GPG_PASSPHRASE") \
              --output "$f.asc" --armor --detach-sign "$f"
          done

      - name: Upload test outcome
        uses: actions/upload-artifact@v4
        with:
          name: asc
          path: "neth.*"
