name: '[JSON-RPC] Compare Nethermind between clients and versions'

on:
  push:
    branches:
      - 'rpc-comparision-1.23.0'
  workflow_dispatch:
    inputs:
      allowed_ips:
        type: string
        description: "A comma-separated list of ips allowed to connect to the node"
        default: ''
        required: false
      what_to_compare:
        type: string
        description: "A space-separated list of branches. If empty, then selected branch will be used. If multiple specified, those will be compared to themselves."
        default: ""
        required: false
      compare_with:
        type: string
        description: "A space-separated list of additional comparers. If empty, then nothing else will be added to comparision. Possible options: 'infura', 'archive', 'feature/branch'"
        default: ""
        required: false

jobs:
  parse_input:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Set matrix for branches
        id: set-matrix
        run: |
          #what_to_compare="${{ github.event.inputs.what_to_compare }}"
          #compare_with="${{ github.event.inputs.compare_with }}"

          what_to_compare=""
          compare_with="infura"

          # Determine the primary branches to compare
          if [[ "$what_to_compare" == "" ]]; then
            current_branch=${GITHUB_REF#refs/heads/}
            branches=("$current_branch")
          else
            readarray -t branches <<< "$what_to_compare"
          fi

          # Add additional comparers if specified
          if [[ "$compare_with" != "" ]]; then
            IFS=' ' read -r -a additional_branches <<< "$compare_with"
            for branch in "${additional_branches[@]}"; do
              if [[ "$branch" != "infura" && "$branch" != "archive" ]]; then
                # Treat as additional branch
                branches+=("$branch")
              fi
            done
          fi

          # Convert array to JSON object with named array
          printf -v joined ', "%s"' "${branches[@]}"
          MATRIX="{\"branch\": [${joined:2}]}"  # Ensure the key name 'branch' is used

          echo $MATRIX > matrix.json
          cat matrix.json
          echo "matrix=$(jq -c . matrix.json)" >> $GITHUB_OUTPUT

  create_node:
    needs: parse_input
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.parse_input.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Run create_node job
        uses: NethermindEth/nethermind/.github/workflows/run-a-single-node-from-branch.yml
        with:
          allowed_ips: ${{ github.event.inputs.allowed_ips }}
          non_validator_mode: false
          additional_nethermind_flags: Pruning.Mode=None
  
  extract_rpc_url:
    name: Extract RPC url from artifacts generated by create_node 
    runs-on: ubuntu-latest
    needs: create_node
    outputs:
      rpc_urls: ${{ steps.aggregate_rpc_urls.outputs.rpc_urls }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract RPC URLs
        id: aggregate_rpc_urls
        run: |
          rpc_urls=""
          for matrix_val in ${{ fromJson(needs.create_node.result) }}
          do
            artifact_name="${{ github.actor }}-${matrix_val}-${{ needs.create_node.outputs.base_tag }}-smoketests"
            echo "Downloading artifact: $artifact_name"
            wget -O artifact.zip --header='Authorization: token ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}' \
                 "https://api.github.com/repos/NethermindEth/post-merge-smoke-tests/actions/artifacts/$artifact_name/zip"
            unzip artifact.zip
            rpc_url=$(cat ./terraform.tfstate | jq -r '.outputs.nodes_data.value[0].rpc_url')
            rpc_urls="$rpc_urls$rpc_url,"
            rm -rf artifact.zip terraform.tfstate
          done
          echo "rpc_urls=${rpc_urls%?}" >> $GITHUB_OUTPUT

  sleep:
    name: Sleep since syncing lasts longer than 6 hours (time limit for a job)
    runs-on: ubuntu-latest
    needs: extract_rpc_url
    steps: 
      - run: sleep 5h 30m

  wait_for_node_to_sync:
    name: Wait for the node to sync
    runs-on: ubuntu-latest
    needs: [sleep, extract_rpc_url]
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v3
      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard resolvconf
          sudo mkdir -p /etc/wireguard
          envsubst < scripts/wireguard.conf.template > wg0.conf
          sudo wg-quick up ./wg0.conf
        env:
          WIREGUARD_PRIVKEY: '${{ secrets.WIREGUARD_PRIVKEY }}'
          WIREGUARD_ADDRESS: '${{ secrets.WIREGUARD_ADDRESS }}'
          WIREGUARD_DNS: '${{ secrets.WIREGUARD_DNS }}'
          WIREGUARD_PUBKEY: '${{ secrets.WIREGUARD_PUBKEY }}'
          WIREGUARD_PRESHAREDKEY: '${{ secrets.WIREGUARD_PRESHAREDKEY }}'
          WIREGUARD_ALLOWED_IPS: '${{ secrets.WIREGUARD_ALLOWED_IPS }}'
          WIREGUARD_SERVER_IP: '${{ secrets.WIREGUARD_SERVER_IP }}'
          WIREGUARD_SERVER_PORT: '${{ secrets.WIREGUARD_SERVER_PORT }}'
      
      - name: Wait for the nodes to sync
        timeout-minutes: 600
        run: |
          rpc_urls=(${{ needs.extract_rpc_url.outputs.rpc_urls }})
          sync_complete_flag=0

          check_sync() {
            rpc_url=$1
            while curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' $rpc_url | jq -e '.result'; do
              sleep 300
            done
            echo "Node at $rpc_url synced."
            sync_complete_flag=$((sync_complete_flag+1))
          }

          for url in "${rpc_urls[@]}"; do
            check_sync "$url" &
          done

          # Wait for all nodes to sync
          while [ $sync_complete_flag -ne ${#rpc_urls[@]} ]; do
            sleep 60
          done

  compare:
    name: Compare JSON-RPC responses between clients and versions
    runs-on: ubuntu-latest
    needs: [extract_rpc_url, wait_for_node_to_sync]
    strategy:
      matrix:
        rpc_to_compare: [INFURA_ENDPOINT, NETHERMIND_ARCHIVE_ENDPOINT]
    steps:
      - uses: actions/checkout@v3
      - name: Install flood
        run: pip install git+https://github.com/piwonskp/flood.git
  
      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard resolvconf
          sudo mkdir -p /etc/wireguard
          envsubst < scripts/wireguard.conf.template > wg0.conf
          sudo wg-quick up ./wg0.conf
        env:
          WIREGUARD_PRIVKEY: '${{ secrets.WIREGUARD_PRIVKEY }}'
          WIREGUARD_ADDRESS: '${{ secrets.WIREGUARD_ADDRESS }}'
          WIREGUARD_DNS: '${{ secrets.WIREGUARD_DNS }}'
          WIREGUARD_PUBKEY: '${{ secrets.WIREGUARD_PUBKEY }}'
          WIREGUARD_PRESHAREDKEY: '${{ secrets.WIREGUARD_PRESHAREDKEY }}'
          WIREGUARD_ALLOWED_IPS: '${{ secrets.WIREGUARD_ALLOWED_IPS }}'
          WIREGUARD_SERVER_IP: '${{ secrets.WIREGUARD_SERVER_IP }}'
          WIREGUARD_SERVER_PORT: '${{ secrets.WIREGUARD_SERVER_PORT }}'
  
      - name: Test equality of responses
        run: flood all nethermind_current=${{ needs.extract_rpc_url.outputs.rpc_url }} ${{ matrix.rpc_to_compare }}=${{ secrets[matrix.rpc_to_compare] }} --equality
