name: '[RUN] Benchmark Performance Tests'

on:
  pull_request:
    branches: [ master ]

jobs:
  run-benchmarks:
    if: github.repository_owner == 'NethermindEth'
    name: Triggering Nethermind Benchmark Performance Run
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Configure environments
      id: envs
      env:
        SHA8: ${{ github.sha }}
        BRANCH: ${{ github.ref }}
      run: |
        echo $SHA8
        echo ${{ github.ref }}
        echo $BRANCH
        echo "::set-output name=sha8::$SHA8"
        echo "::set-output name=branch::$BRANCH"
    - name: Deploy Amazon EC2 instance for Benchmarking
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: Benchmark_${{ steps.envs.outputs.sha8 }}
        template: https://cf-templates-1tzgi56hs2v4n-eu-central-1.s3.eu-central-1.amazonaws.com/performance-test.yaml
        parameter-overrides: "BranchName=${{ steps.envs.outputs.branch }}"
