name: Stateless execution tests

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Nethermind
        working-directory: src/Nethermind/Nethermind.Stateless.ZiskGuest
        run: make build

      - name: Upload guest binary
        uses: actions/upload-artifact@v7
        with:
          name: nethermind
          path: src/Nethermind/Nethermind.Stateless.ZiskGuest/bin/nethermind
          if-no-files-found: error
          retention-days: 1

  test:
    name: Run ${{ matrix.input }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - input: 150026.ssz
            hash: 35b017badd31a71a27b174ecc5088c513324ff66f94b591c5d069325228f6a4e
          - input: 24721542.ssz
            hash: 10df0db9fc2f00e2475e7694d9b888f8b91671fc2701ae550d33e8a9e878cdb3
          - input: 24723632.ssz
            hash: c598c1a7938287da8c811e763b7576050c92af190d9b8d2662fbc39d0a694572
          - input: 24723668.ssz
            hash: f6aaf72032e8c9703aa820cb006d215c5adfc8749094f26c1200be2a5c08b615
          - input: 24772857.ssz
            hash: 6f9d6224a33d023ca982b3faf9118e46d07a8cdbe513d2efa5a4408cb2734915
          - input: 24777027.ssz
            hash: a159d8cfe2d8cd12a03e725ab607373b92e7fa0e005f51d2bf8a2081b0a50015
          - input: 24777988.ssz
            hash: 18c75b1a179bd1aaa09c02011b4c8cd7ab6bef55a56ffb797ca3a0360f2287e7
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Download guest binary
        uses: actions/download-artifact@v8
        with:
          name: nethermind
          path: src/Nethermind/Nethermind.Stateless.ZiskGuest/bin

      - name: Download input
        working-directory: src/Nethermind/Nethermind.Stateless.ZiskGuest/bin
        run: |
          curl -sSL "https://us-southeast-1.linodeobjects.com/zktests/${{ matrix.input }}" \
            -o "${{ matrix.input }}"
          echo "${{ matrix.hash }}  ${{ matrix.input }}" | sha256sum --status -c - || \
            { echo "Checksum failed"; exit 1; }

      - name: Run Nethermind guest
        timeout-minutes: 5
        working-directory: src/Nethermind/Nethermind.Stateless.ZiskGuest
        run: make run INPUT="${{ matrix.input }}"

  status:
    name: Status
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check result
        run: |
          [[ "${{ needs.test.result }}" == "success" ]]
