name: Stateless execution tests

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Nethermind
        working-directory: src/Nethermind/Nethermind.Stateless.ZiskGuest
        run: make build

      - name: Upload guest binary
        uses: actions/upload-artifact@v7
        with:
          name: nethermind
          path: src/Nethermind/Nethermind.Stateless.ZiskGuest/bin/nethermind
          if-no-files-found: error
          retention-days: 1

  test:
    name: Run ${{ matrix.input }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - input: 150026.ssz
            hash: c32830af208c1f05fa26c560d3ab51cf3dfd74769619937ec2fdf4f4c02ccaca
          - input: 24721542.ssz
            hash: 81ae6aed73eb9ba5fd2fbd584b43a14a6a009d2f8b4bea2508c3545f7ae39c8f
          - input: 24723632.ssz
            hash: c9ce44e17519539872b85bf6e085fc8388029b9cc632cbb52765e4fe764d4aa6
          - input: 24723668.ssz
            hash: c1ccbb893271092f8a9f599743e8a119f16e191342d493b6c184c6da3d8822a0
          - input: 24772857.ssz
            hash: ad971da9787b53a91652814b6e4db02178ba56c61827dc0af1ec1d8b4f036a21
          - input: 24777027.ssz
            hash: e3486cc868f2e61da5c3658d196aaac74d6b5a93bd719efbe3d229814adb53f4
          - input: 24777988.ssz
            hash: e928c63fdf95bbae3485c1e3a71313e87c43ff69b411c08be1302a90b06f2a54
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Download guest binary
        uses: actions/download-artifact@v8
        with:
          name: nethermind
          path: src/Nethermind/Nethermind.Stateless.ZiskGuest/bin

      - name: Download input
        working-directory: src/Nethermind/Nethermind.Stateless.ZiskGuest/bin
        run: |
          curl -sSL "https://us-southeast-1.linodeobjects.com/zktests/${{ matrix.input }}" \
            -o "${{ matrix.input }}"
          echo "${{ matrix.hash }}  ${{ matrix.input }}" | sha256sum --status -c - || \
            { echo "Checksum failed"; exit 1; }

      - name: Run Nethermind guest
        timeout-minutes: 5
        working-directory: src/Nethermind/Nethermind.Stateless.ZiskGuest
        run: make run INPUT="${{ matrix.input }}"

  status:
    name: Status
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check result
        run: |
          [[ "${{ needs.test.result }}" == "success" ]]
