name: Trivy scanner

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    - cron: '29 19 * * 4'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    env:
      IMAGE_TAG: nethermind:${{ github.sha }}
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG .

      - name: Scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 #v0.35.0
        with:
          image-ref: ${{ env.IMAGE_TAG }}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@0c0c5dc2f136b98cb0537075ccfa21f94cd9a63e #v2.24.3
        with:
          sarif_file: trivy-results.sarif
