name: "[UPDATE] DAppNode package"

on:
  repository_dispatch:
    types: dappnode

jobs:
  update-dappnode:
    name: Triggering the DAppNode Package update
    runs-on: ubuntu-latest
    steps:
      - name: Getting Tag
        id: get_tag
        run: echo ::set-output name=TAG::${{ github.event.client_payload.tag }}
      - name: Authenticate App
        id: gh-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Sending dispatch event to nethermind DAppNode Package repository
        env:
          DISPATCH_REPO: dappnode/DAppNodePackage-nethermind
        run: |
          curl -s -X POST -u "${{ steps.gh-app.outputs.token }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          --data '{"event_type":"new_release", "client_payload": { "tag":"${{ steps.get_tag.outputs.TAG }}"}}' \
          https://api.github.com/repos/$DISPATCH_REPO/dispatches
