name: "Update Homebrew"

on: 
  workflow_dispatch:

jobs:
  update-homebrew:
    name: Update Homebrew to latest version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with: 
          repository: NethermindEth/homebrew-nethermind
          path: homebrew-nethermind

      - name: Update Homebrew file with new version, commit and date
        run: ./nethermind/scripts/deployment/update-homebrew.sh

      - name: Commit and push changes
        run: |
          #add commit & push here
