name: '[UPDATE] GitBook Docs'

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    
jobs:
  update-gitbook:
    name: Triggering GitBook Docs update
    runs-on: ubuntu-latest
    steps:
    - name: Sending dispatch event to Nethermind docs repository
      env: 
        DISPATCH_REPO: NethermindEth/docs
      run: |
        curl -s -X POST -u "${{ secrets.REPOSITORY_DISPATCH_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" \
        --data '{"event_type":"docs_update"}' \
        https://api.github.com/repos/$DISPATCH_REPO/dispatches
